package com.syscom.safeaa.mybatis.model;

import com.syscom.safeaa.mybatis.vo.BaseModel;

public class Syscomresourceculture extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMRESOURCECULTURE.RESOURCEID
     *
     * @mbg.generated
     */
    private Integer resourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMRESOURCECULTURE.CULTURE
     *
     * @mbg.generated
     */
    private String culture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMRESOURCECULTURE.RESOURCENAME
     *
     * @mbg.generated
     */
    private String resourcename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMRESOURCECULTURE.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCOMRESOURCECULTURE
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCECULTURE
     *
     * @mbg.generated
     */
    public Syscomresourceculture(Integer resourceid, String culture, String resourcename, String remark) {
        this.resourceid = resourceid;
        this.culture = culture;
        this.resourcename = resourcename;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCECULTURE
     *
     * @mbg.generated
     */
    public Syscomresourceculture() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMRESOURCECULTURE.RESOURCEID
     *
     * @return the value of SYSCOMRESOURCECULTURE.RESOURCEID
     *
     * @mbg.generated
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMRESOURCECULTURE.RESOURCEID
     *
     * @param resourceid the value for SYSCOMRESOURCECULTURE.RESOURCEID
     *
     * @mbg.generated
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMRESOURCECULTURE.CULTURE
     *
     * @return the value of SYSCOMRESOURCECULTURE.CULTURE
     *
     * @mbg.generated
     */
    public String getCulture() {
        return culture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMRESOURCECULTURE.CULTURE
     *
     * @param culture the value for SYSCOMRESOURCECULTURE.CULTURE
     *
     * @mbg.generated
     */
    public void setCulture(String culture) {
        this.culture = culture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMRESOURCECULTURE.RESOURCENAME
     *
     * @return the value of SYSCOMRESOURCECULTURE.RESOURCENAME
     *
     * @mbg.generated
     */
    public String getResourcename() {
        return resourcename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMRESOURCECULTURE.RESOURCENAME
     *
     * @param resourcename the value for SYSCOMRESOURCECULTURE.RESOURCENAME
     *
     * @mbg.generated
     */
    public void setResourcename(String resourcename) {
        this.resourcename = resourcename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMRESOURCECULTURE.REMARK
     *
     * @return the value of SYSCOMRESOURCECULTURE.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMRESOURCECULTURE.REMARK
     *
     * @param remark the value for SYSCOMRESOURCECULTURE.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCECULTURE
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Syscomresourceculture other = (Syscomresourceculture) that;
        return (this.getResourceid() == null ? other.getResourceid() == null : this.getResourceid().equals(other.getResourceid()))
            && (this.getCulture() == null ? other.getCulture() == null : this.getCulture().equals(other.getCulture()))
            && (this.getResourcename() == null ? other.getResourcename() == null : this.getResourcename().equals(other.getResourcename()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCECULTURE
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getResourceid() == null) ? 0 : getResourceid().hashCode());
        result = prime * result + ((getCulture() == null) ? 0 : getCulture().hashCode());
        result = prime * result + ((getResourcename() == null) ? 0 : getResourcename().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCECULTURE
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", resourceid=").append(resourceid);
        sb.append(", culture=").append(culture);
        sb.append(", resourcename=").append(resourcename);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCECULTURE
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<RESOURCEID>").append(this.resourceid).append("</RESOURCEID>");
        sb.append("<CULTURE>").append(this.culture).append("</CULTURE>");
        sb.append("<RESOURCENAME>").append(this.resourcename).append("</RESOURCENAME>");
        sb.append("<REMARK>").append(this.remark).append("</REMARK>");
        return sb.toString();
    }
}