package com.syscom.safeaa.mybatis.model;

import com.syscom.safeaa.mybatis.vo.BaseModel;
import java.util.Date;

public class Syscomroleresource extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLERESOURCE.ROLEID
     *
     * @mbg.generated
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLERESOURCE.RESOURCEID
     *
     * @mbg.generated
     */
    private Integer resourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLERESOURCE.SAFEDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    private String safedefinefunctionlist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLERESOURCE.USERDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    private String userdefinefunctionlist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLERESOURCE.UPDATEUSERID
     *
     * @mbg.generated
     */
    private Integer updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLERESOURCE.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCOMROLERESOURCE
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCE
     *
     * @mbg.generated
     */
    public Syscomroleresource(Integer roleid, Integer resourceid, String safedefinefunctionlist, String userdefinefunctionlist, Integer updateuserid, Date updatetime) {
        this.roleid = roleid;
        this.resourceid = resourceid;
        this.safedefinefunctionlist = safedefinefunctionlist;
        this.userdefinefunctionlist = userdefinefunctionlist;
        this.updateuserid = updateuserid;
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCE
     *
     * @mbg.generated
     */
    public Syscomroleresource() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLERESOURCE.ROLEID
     *
     * @return the value of SYSCOMROLERESOURCE.ROLEID
     *
     * @mbg.generated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLERESOURCE.ROLEID
     *
     * @param roleid the value for SYSCOMROLERESOURCE.ROLEID
     *
     * @mbg.generated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLERESOURCE.RESOURCEID
     *
     * @return the value of SYSCOMROLERESOURCE.RESOURCEID
     *
     * @mbg.generated
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLERESOURCE.RESOURCEID
     *
     * @param resourceid the value for SYSCOMROLERESOURCE.RESOURCEID
     *
     * @mbg.generated
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLERESOURCE.SAFEDEFINEFUNCTIONLIST
     *
     * @return the value of SYSCOMROLERESOURCE.SAFEDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    public String getSafedefinefunctionlist() {
        return safedefinefunctionlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLERESOURCE.SAFEDEFINEFUNCTIONLIST
     *
     * @param safedefinefunctionlist the value for SYSCOMROLERESOURCE.SAFEDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    public void setSafedefinefunctionlist(String safedefinefunctionlist) {
        this.safedefinefunctionlist = safedefinefunctionlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLERESOURCE.USERDEFINEFUNCTIONLIST
     *
     * @return the value of SYSCOMROLERESOURCE.USERDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    public String getUserdefinefunctionlist() {
        return userdefinefunctionlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLERESOURCE.USERDEFINEFUNCTIONLIST
     *
     * @param userdefinefunctionlist the value for SYSCOMROLERESOURCE.USERDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    public void setUserdefinefunctionlist(String userdefinefunctionlist) {
        this.userdefinefunctionlist = userdefinefunctionlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLERESOURCE.UPDATEUSERID
     *
     * @return the value of SYSCOMROLERESOURCE.UPDATEUSERID
     *
     * @mbg.generated
     */
    public Integer getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLERESOURCE.UPDATEUSERID
     *
     * @param updateuserid the value for SYSCOMROLERESOURCE.UPDATEUSERID
     *
     * @mbg.generated
     */
    public void setUpdateuserid(Integer updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLERESOURCE.UPDATETIME
     *
     * @return the value of SYSCOMROLERESOURCE.UPDATETIME
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLERESOURCE.UPDATETIME
     *
     * @param updatetime the value for SYSCOMROLERESOURCE.UPDATETIME
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCE
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Syscomroleresource other = (Syscomroleresource) that;
        return (this.getRoleid() == null ? other.getRoleid() == null : this.getRoleid().equals(other.getRoleid()))
            && (this.getResourceid() == null ? other.getResourceid() == null : this.getResourceid().equals(other.getResourceid()))
            && (this.getSafedefinefunctionlist() == null ? other.getSafedefinefunctionlist() == null : this.getSafedefinefunctionlist().equals(other.getSafedefinefunctionlist()))
            && (this.getUserdefinefunctionlist() == null ? other.getUserdefinefunctionlist() == null : this.getUserdefinefunctionlist().equals(other.getUserdefinefunctionlist()))
            && (this.getUpdateuserid() == null ? other.getUpdateuserid() == null : this.getUpdateuserid().equals(other.getUpdateuserid()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCE
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleid() == null) ? 0 : getRoleid().hashCode());
        result = prime * result + ((getResourceid() == null) ? 0 : getResourceid().hashCode());
        result = prime * result + ((getSafedefinefunctionlist() == null) ? 0 : getSafedefinefunctionlist().hashCode());
        result = prime * result + ((getUserdefinefunctionlist() == null) ? 0 : getUserdefinefunctionlist().hashCode());
        result = prime * result + ((getUpdateuserid() == null) ? 0 : getUpdateuserid().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCE
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleid=").append(roleid);
        sb.append(", resourceid=").append(resourceid);
        sb.append(", safedefinefunctionlist=").append(safedefinefunctionlist);
        sb.append(", userdefinefunctionlist=").append(userdefinefunctionlist);
        sb.append(", updateuserid=").append(updateuserid);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCE
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<ROLEID>").append(this.roleid).append("</ROLEID>");
        sb.append("<RESOURCEID>").append(this.resourceid).append("</RESOURCEID>");
        sb.append("<SAFEDEFINEFUNCTIONLIST>").append(this.safedefinefunctionlist).append("</SAFEDEFINEFUNCTIONLIST>");
        sb.append("<USERDEFINEFUNCTIONLIST>").append(this.userdefinefunctionlist).append("</USERDEFINEFUNCTIONLIST>");
        sb.append("<UPDATEUSERID>").append(this.updateuserid).append("</UPDATEUSERID>");
        sb.append("<UPDATETIME>").append(this.updatetime).append("</UPDATETIME>");
        return sb.toString();
    }
}