package com.syscom.safeaa.mybatis.model;

import java.util.Date;

import com.syscom.safeaa.mybatis.vo.BaseModel;

public class Syscompolicy extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMPOLICY.POLICYID
     *
     * @mbg.generated
     */
    private Integer policyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMPOLICY.POLICYNO
     *
     * @mbg.generated
     */
    private String policyno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMPOLICY.ALLOWLOCAL
     *
     * @mbg.generated
     */
    private Short allowlocal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMPOLICY.GETVALUETYPE
     *
     * @mbg.generated
     */
    private String getvaluetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMPOLICY.DEFAULTPOLICYVALUE
     *
     * @mbg.generated
     */
    private String defaultpolicyvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMPOLICY.INVALIDMESSAGEID
     *
     * @mbg.generated
     */
    private String invalidmessageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMPOLICY.EFFECTDATE
     *
     * @mbg.generated
     */
    private Date effectdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMPOLICY.EXPIREDDATE
     *
     * @mbg.generated
     */
    private Date expireddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMPOLICY.UPDATEUSERID
     *
     * @mbg.generated
     */
    private Integer updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMPOLICY.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCOMPOLICY
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMPOLICY
     *
     * @mbg.generated
     */
    public Syscompolicy(Integer policyid, String policyno, Short allowlocal, String getvaluetype, String defaultpolicyvalue, String invalidmessageid, Date effectdate, Date expireddate, Integer updateuserid, Date updatetime) {
        this.policyid = policyid;
        this.policyno = policyno;
        this.allowlocal = allowlocal;
        this.getvaluetype = getvaluetype;
        this.defaultpolicyvalue = defaultpolicyvalue;
        this.invalidmessageid = invalidmessageid;
        this.effectdate = effectdate;
        this.expireddate = expireddate;
        this.updateuserid = updateuserid;
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMPOLICY
     *
     * @mbg.generated
     */
    public Syscompolicy() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMPOLICY.POLICYID
     *
     * @return the value of SYSCOMPOLICY.POLICYID
     *
     * @mbg.generated
     */
    public Integer getPolicyid() {
        return policyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMPOLICY.POLICYID
     *
     * @param policyid the value for SYSCOMPOLICY.POLICYID
     *
     * @mbg.generated
     */
    public void setPolicyid(Integer policyid) {
        this.policyid = policyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMPOLICY.POLICYNO
     *
     * @return the value of SYSCOMPOLICY.POLICYNO
     *
     * @mbg.generated
     */
    public String getPolicyno() {
        return policyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMPOLICY.POLICYNO
     *
     * @param policyno the value for SYSCOMPOLICY.POLICYNO
     *
     * @mbg.generated
     */
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMPOLICY.ALLOWLOCAL
     *
     * @return the value of SYSCOMPOLICY.ALLOWLOCAL
     *
     * @mbg.generated
     */
    public Short getAllowlocal() {
        return allowlocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMPOLICY.ALLOWLOCAL
     *
     * @param allowlocal the value for SYSCOMPOLICY.ALLOWLOCAL
     *
     * @mbg.generated
     */
    public void setAllowlocal(Short allowlocal) {
        this.allowlocal = allowlocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMPOLICY.GETVALUETYPE
     *
     * @return the value of SYSCOMPOLICY.GETVALUETYPE
     *
     * @mbg.generated
     */
    public String getGetvaluetype() {
        return getvaluetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMPOLICY.GETVALUETYPE
     *
     * @param getvaluetype the value for SYSCOMPOLICY.GETVALUETYPE
     *
     * @mbg.generated
     */
    public void setGetvaluetype(String getvaluetype) {
        this.getvaluetype = getvaluetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMPOLICY.DEFAULTPOLICYVALUE
     *
     * @return the value of SYSCOMPOLICY.DEFAULTPOLICYVALUE
     *
     * @mbg.generated
     */
    public String getDefaultpolicyvalue() {
        return defaultpolicyvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMPOLICY.DEFAULTPOLICYVALUE
     *
     * @param defaultpolicyvalue the value for SYSCOMPOLICY.DEFAULTPOLICYVALUE
     *
     * @mbg.generated
     */
    public void setDefaultpolicyvalue(String defaultpolicyvalue) {
        this.defaultpolicyvalue = defaultpolicyvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMPOLICY.INVALIDMESSAGEID
     *
     * @return the value of SYSCOMPOLICY.INVALIDMESSAGEID
     *
     * @mbg.generated
     */
    public String getInvalidmessageid() {
        return invalidmessageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMPOLICY.INVALIDMESSAGEID
     *
     * @param invalidmessageid the value for SYSCOMPOLICY.INVALIDMESSAGEID
     *
     * @mbg.generated
     */
    public void setInvalidmessageid(String invalidmessageid) {
        this.invalidmessageid = invalidmessageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMPOLICY.EFFECTDATE
     *
     * @return the value of SYSCOMPOLICY.EFFECTDATE
     *
     * @mbg.generated
     */
    public Date getEffectdate() {
        return effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMPOLICY.EFFECTDATE
     *
     * @param effectdate the value for SYSCOMPOLICY.EFFECTDATE
     *
     * @mbg.generated
     */
    public void setEffectdate(Date effectdate) {
        this.effectdate = effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMPOLICY.EXPIREDDATE
     *
     * @return the value of SYSCOMPOLICY.EXPIREDDATE
     *
     * @mbg.generated
     */
    public Date getExpireddate() {
        return expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMPOLICY.EXPIREDDATE
     *
     * @param expireddate the value for SYSCOMPOLICY.EXPIREDDATE
     *
     * @mbg.generated
     */
    public void setExpireddate(Date expireddate) {
        this.expireddate = expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMPOLICY.UPDATEUSERID
     *
     * @return the value of SYSCOMPOLICY.UPDATEUSERID
     *
     * @mbg.generated
     */
    public Integer getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMPOLICY.UPDATEUSERID
     *
     * @param updateuserid the value for SYSCOMPOLICY.UPDATEUSERID
     *
     * @mbg.generated
     */
    public void setUpdateuserid(Integer updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMPOLICY.UPDATETIME
     *
     * @return the value of SYSCOMPOLICY.UPDATETIME
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMPOLICY.UPDATETIME
     *
     * @param updatetime the value for SYSCOMPOLICY.UPDATETIME
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMPOLICY
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Syscompolicy other = (Syscompolicy) that;
        return (this.getPolicyid() == null ? other.getPolicyid() == null : this.getPolicyid().equals(other.getPolicyid()))
            && (this.getPolicyno() == null ? other.getPolicyno() == null : this.getPolicyno().equals(other.getPolicyno()))
            && (this.getAllowlocal() == null ? other.getAllowlocal() == null : this.getAllowlocal().equals(other.getAllowlocal()))
            && (this.getGetvaluetype() == null ? other.getGetvaluetype() == null : this.getGetvaluetype().equals(other.getGetvaluetype()))
            && (this.getDefaultpolicyvalue() == null ? other.getDefaultpolicyvalue() == null : this.getDefaultpolicyvalue().equals(other.getDefaultpolicyvalue()))
            && (this.getInvalidmessageid() == null ? other.getInvalidmessageid() == null : this.getInvalidmessageid().equals(other.getInvalidmessageid()))
            && (this.getEffectdate() == null ? other.getEffectdate() == null : this.getEffectdate().equals(other.getEffectdate()))
            && (this.getExpireddate() == null ? other.getExpireddate() == null : this.getExpireddate().equals(other.getExpireddate()))
            && (this.getUpdateuserid() == null ? other.getUpdateuserid() == null : this.getUpdateuserid().equals(other.getUpdateuserid()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMPOLICY
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
//        final int 31 = 31;
        int result = 1;
        result = 31 * result + ((getPolicyid() == null) ? 0 : getPolicyid().hashCode());
        result = 31 * result + ((getPolicyno() == null) ? 0 : getPolicyno().hashCode());
        result = 31 * result + ((getAllowlocal() == null) ? 0 : getAllowlocal().hashCode());
        result = 31 * result + ((getGetvaluetype() == null) ? 0 : getGetvaluetype().hashCode());
        result = 31 * result + ((getDefaultpolicyvalue() == null) ? 0 : getDefaultpolicyvalue().hashCode());
        result = 31 * result + ((getInvalidmessageid() == null) ? 0 : getInvalidmessageid().hashCode());
        result = 31 * result + ((getEffectdate() == null) ? 0 : getEffectdate().hashCode());
        result = 31 * result + ((getExpireddate() == null) ? 0 : getExpireddate().hashCode());
        result = 31 * result + ((getUpdateuserid() == null) ? 0 : getUpdateuserid().hashCode());
        result = 31 * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMPOLICY
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", policyid=").append(policyid);
        sb.append(", policyno=").append(policyno);
        sb.append(", allowlocal=").append(allowlocal);
        sb.append(", getvaluetype=").append(getvaluetype);
        sb.append(", defaultpolicyvalue=").append(defaultpolicyvalue);
        sb.append(", invalidmessageid=").append(invalidmessageid);
        sb.append(", effectdate=").append(effectdate);
        sb.append(", expireddate=").append(expireddate);
        sb.append(", updateuserid=").append(updateuserid);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMPOLICY
     *
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<POLICYID>").append(this.policyid).append("</POLICYID>");
        sb.append("<POLICYNO>").append(this.policyno).append("</POLICYNO>");
        sb.append("<ALLOWLOCAL>").append(this.allowlocal).append("</ALLOWLOCAL>");
        sb.append("<GETVALUETYPE>").append(this.getvaluetype).append("</GETVALUETYPE>");
        sb.append("<DEFAULTPOLICYVALUE>").append(this.defaultpolicyvalue).append("</DEFAULTPOLICYVALUE>");
        sb.append("<INVALIDMESSAGEID>").append(this.invalidmessageid).append("</INVALIDMESSAGEID>");
        sb.append("<EFFECTDATE>").append(this.effectdate).append("</EFFECTDATE>");
        sb.append("<EXPIREDDATE>").append(this.expireddate).append("</EXPIREDDATE>");
        sb.append("<UPDATEUSERID>").append(this.updateuserid).append("</UPDATEUSERID>");
        sb.append("<UPDATETIME>").append(this.updatetime).append("</UPDATETIME>");
        return sb.toString();
    }
}