package com.syscom.safeaa.mybatis.model;

import com.syscom.safeaa.mybatis.vo.BaseModel;
import java.util.Date;

public class Syscomroledeputy extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLEDEPUTY.ROLEID
     *
     * @mbg.generated
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLEDEPUTY.DEPUTYROLEID
     *
     * @mbg.generated
     */
    private Integer deputyroleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLEDEPUTY.EFFECTDATE
     *
     * @mbg.generated
     */
    private Date effectdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLEDEPUTY.EXPIREDDATE
     *
     * @mbg.generated
     */
    private Date expireddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLEDEPUTY.UPDATEUSERID
     *
     * @mbg.generated
     */
    private Integer updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLEDEPUTY.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCOMROLEDEPUTY
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEDEPUTY
     *
     * @mbg.generated
     */
    public Syscomroledeputy(Integer roleid, Integer deputyroleid, Date effectdate, Date expireddate, Integer updateuserid, Date updatetime) {
        this.roleid = roleid;
        this.deputyroleid = deputyroleid;
        this.effectdate = effectdate;
        this.expireddate = expireddate;
        this.updateuserid = updateuserid;
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEDEPUTY
     *
     * @mbg.generated
     */
    public Syscomroledeputy() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLEDEPUTY.ROLEID
     *
     * @return the value of SYSCOMROLEDEPUTY.ROLEID
     *
     * @mbg.generated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLEDEPUTY.ROLEID
     *
     * @param roleid the value for SYSCOMROLEDEPUTY.ROLEID
     *
     * @mbg.generated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLEDEPUTY.DEPUTYROLEID
     *
     * @return the value of SYSCOMROLEDEPUTY.DEPUTYROLEID
     *
     * @mbg.generated
     */
    public Integer getDeputyroleid() {
        return deputyroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLEDEPUTY.DEPUTYROLEID
     *
     * @param deputyroleid the value for SYSCOMROLEDEPUTY.DEPUTYROLEID
     *
     * @mbg.generated
     */
    public void setDeputyroleid(Integer deputyroleid) {
        this.deputyroleid = deputyroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLEDEPUTY.EFFECTDATE
     *
     * @return the value of SYSCOMROLEDEPUTY.EFFECTDATE
     *
     * @mbg.generated
     */
    public Date getEffectdate() {
        return effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLEDEPUTY.EFFECTDATE
     *
     * @param effectdate the value for SYSCOMROLEDEPUTY.EFFECTDATE
     *
     * @mbg.generated
     */
    public void setEffectdate(Date effectdate) {
        this.effectdate = effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLEDEPUTY.EXPIREDDATE
     *
     * @return the value of SYSCOMROLEDEPUTY.EXPIREDDATE
     *
     * @mbg.generated
     */
    public Date getExpireddate() {
        return expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLEDEPUTY.EXPIREDDATE
     *
     * @param expireddate the value for SYSCOMROLEDEPUTY.EXPIREDDATE
     *
     * @mbg.generated
     */
    public void setExpireddate(Date expireddate) {
        this.expireddate = expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLEDEPUTY.UPDATEUSERID
     *
     * @return the value of SYSCOMROLEDEPUTY.UPDATEUSERID
     *
     * @mbg.generated
     */
    public Integer getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLEDEPUTY.UPDATEUSERID
     *
     * @param updateuserid the value for SYSCOMROLEDEPUTY.UPDATEUSERID
     *
     * @mbg.generated
     */
    public void setUpdateuserid(Integer updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLEDEPUTY.UPDATETIME
     *
     * @return the value of SYSCOMROLEDEPUTY.UPDATETIME
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLEDEPUTY.UPDATETIME
     *
     * @param updatetime the value for SYSCOMROLEDEPUTY.UPDATETIME
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEDEPUTY
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Syscomroledeputy other = (Syscomroledeputy) that;
        return (this.getRoleid() == null ? other.getRoleid() == null : this.getRoleid().equals(other.getRoleid()))
            && (this.getDeputyroleid() == null ? other.getDeputyroleid() == null : this.getDeputyroleid().equals(other.getDeputyroleid()))
            && (this.getEffectdate() == null ? other.getEffectdate() == null : this.getEffectdate().equals(other.getEffectdate()))
            && (this.getExpireddate() == null ? other.getExpireddate() == null : this.getExpireddate().equals(other.getExpireddate()))
            && (this.getUpdateuserid() == null ? other.getUpdateuserid() == null : this.getUpdateuserid().equals(other.getUpdateuserid()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEDEPUTY
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleid() == null) ? 0 : getRoleid().hashCode());
        result = prime * result + ((getDeputyroleid() == null) ? 0 : getDeputyroleid().hashCode());
        result = prime * result + ((getEffectdate() == null) ? 0 : getEffectdate().hashCode());
        result = prime * result + ((getExpireddate() == null) ? 0 : getExpireddate().hashCode());
        result = prime * result + ((getUpdateuserid() == null) ? 0 : getUpdateuserid().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEDEPUTY
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleid=").append(roleid);
        sb.append(", deputyroleid=").append(deputyroleid);
        sb.append(", effectdate=").append(effectdate);
        sb.append(", expireddate=").append(expireddate);
        sb.append(", updateuserid=").append(updateuserid);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEDEPUTY
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<ROLEID>").append(this.roleid).append("</ROLEID>");
        sb.append("<DEPUTYROLEID>").append(this.deputyroleid).append("</DEPUTYROLEID>");
        sb.append("<EFFECTDATE>").append(this.effectdate).append("</EFFECTDATE>");
        sb.append("<EXPIREDDATE>").append(this.expireddate).append("</EXPIREDDATE>");
        sb.append("<UPDATEUSERID>").append(this.updateuserid).append("</UPDATEUSERID>");
        sb.append("<UPDATETIME>").append(this.updatetime).append("</UPDATETIME>");
        return sb.toString();
    }
}