package com.syscom.safeaa.mybatis.model;

import com.syscom.safeaa.mybatis.vo.BaseModel;
import java.util.Date;

public class Syscomtemplate extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMTEMPLATE.TEMPLATEID
     *
     * @mbg.generated
     */
    private Integer templateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMTEMPLATE.TEMPLATENO
     *
     * @mbg.generated
     */
    private String templateno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMTEMPLATE.ISGLOBALSCOPE
     *
     * @mbg.generated
     */
    private Short isglobalscope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMTEMPLATE.EFFECTDATE
     *
     * @mbg.generated
     */
    private Date effectdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMTEMPLATE.EXPIREDDATE
     *
     * @mbg.generated
     */
    private Date expireddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMTEMPLATE.UPDATEUSERID
     *
     * @mbg.generated
     */
    private Integer updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMTEMPLATE.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCOMTEMPLATE
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATE
     *
     * @mbg.generated
     */
    public Syscomtemplate(Integer templateid, String templateno, Short isglobalscope, Date effectdate, Date expireddate, Integer updateuserid, Date updatetime) {
        this.templateid = templateid;
        this.templateno = templateno;
        this.isglobalscope = isglobalscope;
        this.effectdate = effectdate;
        this.expireddate = expireddate;
        this.updateuserid = updateuserid;
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATE
     *
     * @mbg.generated
     */
    public Syscomtemplate() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMTEMPLATE.TEMPLATEID
     *
     * @return the value of SYSCOMTEMPLATE.TEMPLATEID
     *
     * @mbg.generated
     */
    public Integer getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMTEMPLATE.TEMPLATEID
     *
     * @param templateid the value for SYSCOMTEMPLATE.TEMPLATEID
     *
     * @mbg.generated
     */
    public void setTemplateid(Integer templateid) {
        this.templateid = templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMTEMPLATE.TEMPLATENO
     *
     * @return the value of SYSCOMTEMPLATE.TEMPLATENO
     *
     * @mbg.generated
     */
    public String getTemplateno() {
        return templateno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMTEMPLATE.TEMPLATENO
     *
     * @param templateno the value for SYSCOMTEMPLATE.TEMPLATENO
     *
     * @mbg.generated
     */
    public void setTemplateno(String templateno) {
        this.templateno = templateno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMTEMPLATE.ISGLOBALSCOPE
     *
     * @return the value of SYSCOMTEMPLATE.ISGLOBALSCOPE
     *
     * @mbg.generated
     */
    public Short getIsglobalscope() {
        return isglobalscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMTEMPLATE.ISGLOBALSCOPE
     *
     * @param isglobalscope the value for SYSCOMTEMPLATE.ISGLOBALSCOPE
     *
     * @mbg.generated
     */
    public void setIsglobalscope(Short isglobalscope) {
        this.isglobalscope = isglobalscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMTEMPLATE.EFFECTDATE
     *
     * @return the value of SYSCOMTEMPLATE.EFFECTDATE
     *
     * @mbg.generated
     */
    public Date getEffectdate() {
        return effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMTEMPLATE.EFFECTDATE
     *
     * @param effectdate the value for SYSCOMTEMPLATE.EFFECTDATE
     *
     * @mbg.generated
     */
    public void setEffectdate(Date effectdate) {
        this.effectdate = effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMTEMPLATE.EXPIREDDATE
     *
     * @return the value of SYSCOMTEMPLATE.EXPIREDDATE
     *
     * @mbg.generated
     */
    public Date getExpireddate() {
        return expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMTEMPLATE.EXPIREDDATE
     *
     * @param expireddate the value for SYSCOMTEMPLATE.EXPIREDDATE
     *
     * @mbg.generated
     */
    public void setExpireddate(Date expireddate) {
        this.expireddate = expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMTEMPLATE.UPDATEUSERID
     *
     * @return the value of SYSCOMTEMPLATE.UPDATEUSERID
     *
     * @mbg.generated
     */
    public Integer getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMTEMPLATE.UPDATEUSERID
     *
     * @param updateuserid the value for SYSCOMTEMPLATE.UPDATEUSERID
     *
     * @mbg.generated
     */
    public void setUpdateuserid(Integer updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMTEMPLATE.UPDATETIME
     *
     * @return the value of SYSCOMTEMPLATE.UPDATETIME
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMTEMPLATE.UPDATETIME
     *
     * @param updatetime the value for SYSCOMTEMPLATE.UPDATETIME
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATE
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Syscomtemplate other = (Syscomtemplate) that;
        return (this.getTemplateid() == null ? other.getTemplateid() == null : this.getTemplateid().equals(other.getTemplateid()))
            && (this.getTemplateno() == null ? other.getTemplateno() == null : this.getTemplateno().equals(other.getTemplateno()))
            && (this.getIsglobalscope() == null ? other.getIsglobalscope() == null : this.getIsglobalscope().equals(other.getIsglobalscope()))
            && (this.getEffectdate() == null ? other.getEffectdate() == null : this.getEffectdate().equals(other.getEffectdate()))
            && (this.getExpireddate() == null ? other.getExpireddate() == null : this.getExpireddate().equals(other.getExpireddate()))
            && (this.getUpdateuserid() == null ? other.getUpdateuserid() == null : this.getUpdateuserid().equals(other.getUpdateuserid()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATE
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTemplateid() == null) ? 0 : getTemplateid().hashCode());
        result = prime * result + ((getTemplateno() == null) ? 0 : getTemplateno().hashCode());
        result = prime * result + ((getIsglobalscope() == null) ? 0 : getIsglobalscope().hashCode());
        result = prime * result + ((getEffectdate() == null) ? 0 : getEffectdate().hashCode());
        result = prime * result + ((getExpireddate() == null) ? 0 : getExpireddate().hashCode());
        result = prime * result + ((getUpdateuserid() == null) ? 0 : getUpdateuserid().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATE
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", templateid=").append(templateid);
        sb.append(", templateno=").append(templateno);
        sb.append(", isglobalscope=").append(isglobalscope);
        sb.append(", effectdate=").append(effectdate);
        sb.append(", expireddate=").append(expireddate);
        sb.append(", updateuserid=").append(updateuserid);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATE
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<TEMPLATEID>").append(this.templateid).append("</TEMPLATEID>");
        sb.append("<TEMPLATENO>").append(this.templateno).append("</TEMPLATENO>");
        sb.append("<ISGLOBALSCOPE>").append(this.isglobalscope).append("</ISGLOBALSCOPE>");
        sb.append("<EFFECTDATE>").append(this.effectdate).append("</EFFECTDATE>");
        sb.append("<EXPIREDDATE>").append(this.expireddate).append("</EXPIREDDATE>");
        sb.append("<UPDATEUSERID>").append(this.updateuserid).append("</UPDATEUSERID>");
        sb.append("<UPDATETIME>").append(this.updatetime).append("</UPDATETIME>");
        return sb.toString();
    }
}