package com.syscom.safeaa.mybatis.model;

import com.syscom.safeaa.mybatis.vo.BaseModel;
import java.util.Date;

public class Syscomuser extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSER.USERID
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSER.LOGONID
     *
     * @mbg.generated
     */
    private String logonid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSER.USERNAME
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSER.EMPLOYEEID
     *
     * @mbg.generated
     */
    private String employeeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSER.IDNO
     *
     * @mbg.generated
     */
    private String idno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSER.BIRTHDAY
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSER.EFFECTDATE
     *
     * @mbg.generated
     */
    private Date effectdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSER.EXPIREDDATE
     *
     * @mbg.generated
     */
    private Date expireddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSER.EMAILADDRESS
     *
     * @mbg.generated
     */
    private String emailaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSER.UPDATEUSERID
     *
     * @mbg.generated
     */
    private Integer updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSER.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSER.EMPID
     *
     * @mbg.generated
     */
    private Integer empid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCOMUSER
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSER
     *
     * @mbg.generated
     */
    public Syscomuser(Integer userid, String logonid, String username, String employeeid, String idno, String birthday, Date effectdate, Date expireddate, String emailaddress, Integer updateuserid, Date updatetime, Integer empid) {
        this.userid = userid;
        this.logonid = logonid;
        this.username = username;
        this.employeeid = employeeid;
        this.idno = idno;
        this.birthday = birthday;
        this.effectdate = effectdate;
        this.expireddate = expireddate;
        this.emailaddress = emailaddress;
        this.updateuserid = updateuserid;
        this.updatetime = updatetime;
        this.empid = empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSER
     *
     * @mbg.generated
     */
    public Syscomuser() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSER.USERID
     *
     * @return the value of SYSCOMUSER.USERID
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSER.USERID
     *
     * @param userid the value for SYSCOMUSER.USERID
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSER.LOGONID
     *
     * @return the value of SYSCOMUSER.LOGONID
     *
     * @mbg.generated
     */
    public String getLogonid() {
        return logonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSER.LOGONID
     *
     * @param logonid the value for SYSCOMUSER.LOGONID
     *
     * @mbg.generated
     */
    public void setLogonid(String logonid) {
        this.logonid = logonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSER.USERNAME
     *
     * @return the value of SYSCOMUSER.USERNAME
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSER.USERNAME
     *
     * @param username the value for SYSCOMUSER.USERNAME
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSER.EMPLOYEEID
     *
     * @return the value of SYSCOMUSER.EMPLOYEEID
     *
     * @mbg.generated
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSER.EMPLOYEEID
     *
     * @param employeeid the value for SYSCOMUSER.EMPLOYEEID
     *
     * @mbg.generated
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSER.IDNO
     *
     * @return the value of SYSCOMUSER.IDNO
     *
     * @mbg.generated
     */
    public String getIdno() {
        return idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSER.IDNO
     *
     * @param idno the value for SYSCOMUSER.IDNO
     *
     * @mbg.generated
     */
    public void setIdno(String idno) {
        this.idno = idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSER.BIRTHDAY
     *
     * @return the value of SYSCOMUSER.BIRTHDAY
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSER.BIRTHDAY
     *
     * @param birthday the value for SYSCOMUSER.BIRTHDAY
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSER.EFFECTDATE
     *
     * @return the value of SYSCOMUSER.EFFECTDATE
     *
     * @mbg.generated
     */
    public Date getEffectdate() {
        return effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSER.EFFECTDATE
     *
     * @param effectdate the value for SYSCOMUSER.EFFECTDATE
     *
     * @mbg.generated
     */
    public void setEffectdate(Date effectdate) {
        this.effectdate = effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSER.EXPIREDDATE
     *
     * @return the value of SYSCOMUSER.EXPIREDDATE
     *
     * @mbg.generated
     */
    public Date getExpireddate() {
        return expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSER.EXPIREDDATE
     *
     * @param expireddate the value for SYSCOMUSER.EXPIREDDATE
     *
     * @mbg.generated
     */
    public void setExpireddate(Date expireddate) {
        this.expireddate = expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSER.EMAILADDRESS
     *
     * @return the value of SYSCOMUSER.EMAILADDRESS
     *
     * @mbg.generated
     */
    public String getEmailaddress() {
        return emailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSER.EMAILADDRESS
     *
     * @param emailaddress the value for SYSCOMUSER.EMAILADDRESS
     *
     * @mbg.generated
     */
    public void setEmailaddress(String emailaddress) {
        this.emailaddress = emailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSER.UPDATEUSERID
     *
     * @return the value of SYSCOMUSER.UPDATEUSERID
     *
     * @mbg.generated
     */
    public Integer getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSER.UPDATEUSERID
     *
     * @param updateuserid the value for SYSCOMUSER.UPDATEUSERID
     *
     * @mbg.generated
     */
    public void setUpdateuserid(Integer updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSER.UPDATETIME
     *
     * @return the value of SYSCOMUSER.UPDATETIME
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSER.UPDATETIME
     *
     * @param updatetime the value for SYSCOMUSER.UPDATETIME
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSER.EMPID
     *
     * @return the value of SYSCOMUSER.EMPID
     *
     * @mbg.generated
     */
    public Integer getEmpid() {
        return empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSER.EMPID
     *
     * @param empid the value for SYSCOMUSER.EMPID
     *
     * @mbg.generated
     */
    public void setEmpid(Integer empid) {
        this.empid = empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSER
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Syscomuser other = (Syscomuser) that;
        return (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getLogonid() == null ? other.getLogonid() == null : this.getLogonid().equals(other.getLogonid()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getEmployeeid() == null ? other.getEmployeeid() == null : this.getEmployeeid().equals(other.getEmployeeid()))
            && (this.getIdno() == null ? other.getIdno() == null : this.getIdno().equals(other.getIdno()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getEffectdate() == null ? other.getEffectdate() == null : this.getEffectdate().equals(other.getEffectdate()))
            && (this.getExpireddate() == null ? other.getExpireddate() == null : this.getExpireddate().equals(other.getExpireddate()))
            && (this.getEmailaddress() == null ? other.getEmailaddress() == null : this.getEmailaddress().equals(other.getEmailaddress()))
            && (this.getUpdateuserid() == null ? other.getUpdateuserid() == null : this.getUpdateuserid().equals(other.getUpdateuserid()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()))
            && (this.getEmpid() == null ? other.getEmpid() == null : this.getEmpid().equals(other.getEmpid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSER
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getLogonid() == null) ? 0 : getLogonid().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getEmployeeid() == null) ? 0 : getEmployeeid().hashCode());
        result = prime * result + ((getIdno() == null) ? 0 : getIdno().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getEffectdate() == null) ? 0 : getEffectdate().hashCode());
        result = prime * result + ((getExpireddate() == null) ? 0 : getExpireddate().hashCode());
        result = prime * result + ((getEmailaddress() == null) ? 0 : getEmailaddress().hashCode());
        result = prime * result + ((getUpdateuserid() == null) ? 0 : getUpdateuserid().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        result = prime * result + ((getEmpid() == null) ? 0 : getEmpid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSER
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", logonid=").append(logonid);
        sb.append(", username=").append(username);
        sb.append(", employeeid=").append(employeeid);
        sb.append(", idno=").append(idno);
        sb.append(", birthday=").append(birthday);
        sb.append(", effectdate=").append(effectdate);
        sb.append(", expireddate=").append(expireddate);
        sb.append(", emailaddress=").append(emailaddress);
        sb.append(", updateuserid=").append(updateuserid);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", empid=").append(empid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSER
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<USERID>").append(this.userid).append("</USERID>");
        sb.append("<LOGONID>").append(this.logonid).append("</LOGONID>");
        sb.append("<USERNAME>").append(this.username).append("</USERNAME>");
        sb.append("<EMPLOYEEID>").append(this.employeeid).append("</EMPLOYEEID>");
        sb.append("<IDNO>").append(this.idno).append("</IDNO>");
        sb.append("<BIRTHDAY>").append(this.birthday).append("</BIRTHDAY>");
        sb.append("<EFFECTDATE>").append(this.effectdate).append("</EFFECTDATE>");
        sb.append("<EXPIREDDATE>").append(this.expireddate).append("</EXPIREDDATE>");
        sb.append("<EMAILADDRESS>").append(this.emailaddress).append("</EMAILADDRESS>");
        sb.append("<UPDATEUSERID>").append(this.updateuserid).append("</UPDATEUSERID>");
        sb.append("<UPDATETIME>").append(this.updatetime).append("</UPDATETIME>");
        sb.append("<EMPID>").append(this.empid).append("</EMPID>");
        return sb.toString();
    }
}