package com.syscom.safeaa.mybatis.model;

import com.syscom.safeaa.mybatis.vo.BaseModel;

public class Syscompolicyculture extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMPOLICYCULTURE.POLICYID
     *
     * @mbg.generated
     */
    private Integer policyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMPOLICYCULTURE.CULTURE
     *
     * @mbg.generated
     */
    private String culture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMPOLICYCULTURE.POLICYNAME
     *
     * @mbg.generated
     */
    private String policyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMPOLICYCULTURE.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCOMPOLICYCULTURE
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMPOLICYCULTURE
     *
     * @mbg.generated
     */
    public Syscompolicyculture(Integer policyid, String culture, String policyname, String remark) {
        this.policyid = policyid;
        this.culture = culture;
        this.policyname = policyname;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMPOLICYCULTURE
     *
     * @mbg.generated
     */
    public Syscompolicyculture() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMPOLICYCULTURE.POLICYID
     *
     * @return the value of SYSCOMPOLICYCULTURE.POLICYID
     *
     * @mbg.generated
     */
    public Integer getPolicyid() {
        return policyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMPOLICYCULTURE.POLICYID
     *
     * @param policyid the value for SYSCOMPOLICYCULTURE.POLICYID
     *
     * @mbg.generated
     */
    public void setPolicyid(Integer policyid) {
        this.policyid = policyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMPOLICYCULTURE.CULTURE
     *
     * @return the value of SYSCOMPOLICYCULTURE.CULTURE
     *
     * @mbg.generated
     */
    public String getCulture() {
        return culture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMPOLICYCULTURE.CULTURE
     *
     * @param culture the value for SYSCOMPOLICYCULTURE.CULTURE
     *
     * @mbg.generated
     */
    public void setCulture(String culture) {
        this.culture = culture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMPOLICYCULTURE.POLICYNAME
     *
     * @return the value of SYSCOMPOLICYCULTURE.POLICYNAME
     *
     * @mbg.generated
     */
    public String getPolicyname() {
        return policyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMPOLICYCULTURE.POLICYNAME
     *
     * @param policyname the value for SYSCOMPOLICYCULTURE.POLICYNAME
     *
     * @mbg.generated
     */
    public void setPolicyname(String policyname) {
        this.policyname = policyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMPOLICYCULTURE.REMARK
     *
     * @return the value of SYSCOMPOLICYCULTURE.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMPOLICYCULTURE.REMARK
     *
     * @param remark the value for SYSCOMPOLICYCULTURE.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMPOLICYCULTURE
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Syscompolicyculture other = (Syscompolicyculture) that;
        return (this.getPolicyid() == null ? other.getPolicyid() == null : this.getPolicyid().equals(other.getPolicyid()))
            && (this.getCulture() == null ? other.getCulture() == null : this.getCulture().equals(other.getCulture()))
            && (this.getPolicyname() == null ? other.getPolicyname() == null : this.getPolicyname().equals(other.getPolicyname()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMPOLICYCULTURE
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPolicyid() == null) ? 0 : getPolicyid().hashCode());
        result = prime * result + ((getCulture() == null) ? 0 : getCulture().hashCode());
        result = prime * result + ((getPolicyname() == null) ? 0 : getPolicyname().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMPOLICYCULTURE
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", policyid=").append(policyid);
        sb.append(", culture=").append(culture);
        sb.append(", policyname=").append(policyname);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMPOLICYCULTURE
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<POLICYID>").append(this.policyid).append("</POLICYID>");
        sb.append("<CULTURE>").append(this.culture).append("</CULTURE>");
        sb.append("<POLICYNAME>").append(this.policyname).append("</POLICYNAME>");
        sb.append("<REMARK>").append(this.remark).append("</REMARK>");
        return sb.toString();
    }
}