package com.syscom.safeaa.mybatis.model;

import java.util.Date;

import com.syscom.safeaa.mybatis.vo.BaseModel;

public class Syscomuserstatus extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.USERID
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.LOGONTIME
     *
     * @mbg.generated
     */
    private Date logontime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.LOGONIP
     *
     * @mbg.generated
     */
    private String logonip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.ISLOGON
     *
     * @mbg.generated
     */
    private Short islogon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.LOGONCHANGESSCODE
     *
     * @mbg.generated
     */
    private Short logonchangesscode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.LASTSSCODECHANGETIME
     *
     * @mbg.generated
     */
    private Date lastsscodechangetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.SSCODEERRORCOUNT
     *
     * @mbg.generated
     */
    private Integer sscodeerrorcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.LASTLOGONTIME
     *
     * @mbg.generated
     */
    private Date lastlogontime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.LASTLOGONIP
     *
     * @mbg.generated
     */
    private String lastlogonip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.LASTLOGOFFTIME
     *
     * @mbg.generated
     */
    private Date lastlogofftime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.SSCODE
     *
     * @mbg.generated
     */
    private String sscode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.SSCODEFORMAT
     *
     * @mbg.generated
     */
    private Integer sscodeformat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.SSCODESALT
     *
     * @mbg.generated
     */
    private String sscodesalt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.PKISERIALNO
     *
     * @mbg.generated
     */
    private String pkiserialno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.SSCODEHINTQUESTION
     *
     * @mbg.generated
     */
    private String sscodehintquestion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.SSCODEHINTANSWER
     *
     * @mbg.generated
     */
    private String sscodehintanswer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.FAILEDPSWANSATTEMPTCOUNT
     *
     * @mbg.generated
     */
    private Integer failedpswansattemptcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.ISLOCKOUT
     *
     * @mbg.generated
     */
    private Short islockout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.LASTLOCKOUTTIME
     *
     * @mbg.generated
     */
    private Date lastlockouttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.FAILEDPSWATTEMPTTIME
     *
     * @mbg.generated
     */
    private Date failedpswattempttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.FAILEDPSWANSATTEMPTTIME
     *
     * @mbg.generated
     */
    private Date failedpswansattempttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.SSCODEEFFECTDATE
     *
     * @mbg.generated
     */
    private Date sscodeeffectdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.APDEFINE1
     *
     * @mbg.generated
     */
    private String apdefine1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERSTATUS.APDEFINE2
     *
     * @mbg.generated
     */
    private String apdefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCOMUSERSTATUS
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSERSTATUS
     *
     * @mbg.generated
     */
    public Syscomuserstatus(Integer userid, Date logontime, String logonip, Short islogon, Short logonchangesscode, Date lastsscodechangetime, Integer sscodeerrorcount, Date lastlogontime, String lastlogonip, Date lastlogofftime, String sscode, Integer sscodeformat, String sscodesalt, String pkiserialno, String sscodehintquestion, String sscodehintanswer, Integer failedpswansattemptcount, Short islockout, Date lastlockouttime, Date failedpswattempttime, Date failedpswansattempttime, Date sscodeeffectdate, String apdefine1, String apdefine2) {
        this.userid = userid;
        this.logontime = logontime;
        this.logonip = logonip;
        this.islogon = islogon;
        this.logonchangesscode = logonchangesscode;
        this.lastsscodechangetime = lastsscodechangetime;
        this.sscodeerrorcount = sscodeerrorcount;
        this.lastlogontime = lastlogontime;
        this.lastlogonip = lastlogonip;
        this.lastlogofftime = lastlogofftime;
        this.sscode = sscode;
        this.sscodeformat = sscodeformat;
        this.sscodesalt = sscodesalt;
        this.pkiserialno = pkiserialno;
        this.sscodehintquestion = sscodehintquestion;
        this.sscodehintanswer = sscodehintanswer;
        this.failedpswansattemptcount = failedpswansattemptcount;
        this.islockout = islockout;
        this.lastlockouttime = lastlockouttime;
        this.failedpswattempttime = failedpswattempttime;
        this.failedpswansattempttime = failedpswansattempttime;
        this.sscodeeffectdate = sscodeeffectdate;
        this.apdefine1 = apdefine1;
        this.apdefine2 = apdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSERSTATUS
     *
     * @mbg.generated
     */
    public Syscomuserstatus() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.USERID
     *
     * @return the value of SYSCOMUSERSTATUS.USERID
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.USERID
     *
     * @param userid the value for SYSCOMUSERSTATUS.USERID
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.LOGONTIME
     *
     * @return the value of SYSCOMUSERSTATUS.LOGONTIME
     *
     * @mbg.generated
     */
    public Date getLogontime() {
        return logontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.LOGONTIME
     *
     * @param logontime the value for SYSCOMUSERSTATUS.LOGONTIME
     *
     * @mbg.generated
     */
    public void setLogontime(Date logontime) {
        this.logontime = logontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.LOGONIP
     *
     * @return the value of SYSCOMUSERSTATUS.LOGONIP
     *
     * @mbg.generated
     */
    public String getLogonip() {
        return logonip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.LOGONIP
     *
     * @param logonip the value for SYSCOMUSERSTATUS.LOGONIP
     *
     * @mbg.generated
     */
    public void setLogonip(String logonip) {
        this.logonip = logonip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.ISLOGON
     *
     * @return the value of SYSCOMUSERSTATUS.ISLOGON
     *
     * @mbg.generated
     */
    public Short getIslogon() {
        return islogon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.ISLOGON
     *
     * @param islogon the value for SYSCOMUSERSTATUS.ISLOGON
     *
     * @mbg.generated
     */
    public void setIslogon(Short islogon) {
        this.islogon = islogon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.LOGONCHANGESSCODE
     *
     * @return the value of SYSCOMUSERSTATUS.LOGONCHANGESSCODE
     *
     * @mbg.generated
     */
    public Short getLogonchangesscode() {
        return logonchangesscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.LOGONCHANGESSCODE
     *
     * @param logonchangesscode the value for SYSCOMUSERSTATUS.LOGONCHANGESSCODE
     *
     * @mbg.generated
     */
    public void setLogonchangesscode(Short logonchangesscode) {
        this.logonchangesscode = logonchangesscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.LASTSSCODECHANGETIME
     *
     * @return the value of SYSCOMUSERSTATUS.LASTSSCODECHANGETIME
     *
     * @mbg.generated
     */
    public Date getLastsscodechangetime() {
        return lastsscodechangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.LASTSSCODECHANGETIME
     *
     * @param lastsscodechangetime the value for SYSCOMUSERSTATUS.LASTSSCODECHANGETIME
     *
     * @mbg.generated
     */
    public void setLastsscodechangetime(Date lastsscodechangetime) {
        this.lastsscodechangetime = lastsscodechangetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.SSCODEERRORCOUNT
     *
     * @return the value of SYSCOMUSERSTATUS.SSCODEERRORCOUNT
     *
     * @mbg.generated
     */
    public Integer getSscodeerrorcount() {
        return sscodeerrorcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.SSCODEERRORCOUNT
     *
     * @param sscodeerrorcount the value for SYSCOMUSERSTATUS.SSCODEERRORCOUNT
     *
     * @mbg.generated
     */
    public void setSscodeerrorcount(Integer sscodeerrorcount) {
        this.sscodeerrorcount = sscodeerrorcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.LASTLOGONTIME
     *
     * @return the value of SYSCOMUSERSTATUS.LASTLOGONTIME
     *
     * @mbg.generated
     */
    public Date getLastlogontime() {
        return lastlogontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.LASTLOGONTIME
     *
     * @param lastlogontime the value for SYSCOMUSERSTATUS.LASTLOGONTIME
     *
     * @mbg.generated
     */
    public void setLastlogontime(Date lastlogontime) {
        this.lastlogontime = lastlogontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.LASTLOGONIP
     *
     * @return the value of SYSCOMUSERSTATUS.LASTLOGONIP
     *
     * @mbg.generated
     */
    public String getLastlogonip() {
        return lastlogonip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.LASTLOGONIP
     *
     * @param lastlogonip the value for SYSCOMUSERSTATUS.LASTLOGONIP
     *
     * @mbg.generated
     */
    public void setLastlogonip(String lastlogonip) {
        this.lastlogonip = lastlogonip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.LASTLOGOFFTIME
     *
     * @return the value of SYSCOMUSERSTATUS.LASTLOGOFFTIME
     *
     * @mbg.generated
     */
    public Date getLastlogofftime() {
        return lastlogofftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.LASTLOGOFFTIME
     *
     * @param lastlogofftime the value for SYSCOMUSERSTATUS.LASTLOGOFFTIME
     *
     * @mbg.generated
     */
    public void setLastlogofftime(Date lastlogofftime) {
        this.lastlogofftime = lastlogofftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.SSCODE
     *
     * @return the value of SYSCOMUSERSTATUS.SSCODE
     *
     * @mbg.generated
     */
    public String getSscode() {
        return sscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.SSCODE
     *
     * @param sscode the value for SYSCOMUSERSTATUS.SSCODE
     *
     * @mbg.generated
     */
    public void setSscode(String sscode) {
        this.sscode = sscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.SSCODEFORMAT
     *
     * @return the value of SYSCOMUSERSTATUS.SSCODEFORMAT
     *
     * @mbg.generated
     */
    public Integer getSscodeformat() {
        return sscodeformat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.SSCODEFORMAT
     *
     * @param sscodeformat the value for SYSCOMUSERSTATUS.SSCODEFORMAT
     *
     * @mbg.generated
     */
    public void setSscodeformat(Integer sscodeformat) {
        this.sscodeformat = sscodeformat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.SSCODESALT
     *
     * @return the value of SYSCOMUSERSTATUS.SSCODESALT
     *
     * @mbg.generated
     */
    public String getSscodesalt() {
        return sscodesalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.SSCODESALT
     *
     * @param sscodesalt the value for SYSCOMUSERSTATUS.SSCODESALT
     *
     * @mbg.generated
     */
    public void setSscodesalt(String sscodesalt) {
        this.sscodesalt = sscodesalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.PKISERIALNO
     *
     * @return the value of SYSCOMUSERSTATUS.PKISERIALNO
     *
     * @mbg.generated
     */
    public String getPkiserialno() {
        return pkiserialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.PKISERIALNO
     *
     * @param pkiserialno the value for SYSCOMUSERSTATUS.PKISERIALNO
     *
     * @mbg.generated
     */
    public void setPkiserialno(String pkiserialno) {
        this.pkiserialno = pkiserialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.SSCODEHINTQUESTION
     *
     * @return the value of SYSCOMUSERSTATUS.SSCODEHINTQUESTION
     *
     * @mbg.generated
     */
    public String getSscodehintquestion() {
        return sscodehintquestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.SSCODEHINTQUESTION
     *
     * @param sscodehintquestion the value for SYSCOMUSERSTATUS.SSCODEHINTQUESTION
     *
     * @mbg.generated
     */
    public void setSscodehintquestion(String sscodehintquestion) {
        this.sscodehintquestion = sscodehintquestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.SSCODEHINTANSWER
     *
     * @return the value of SYSCOMUSERSTATUS.SSCODEHINTANSWER
     *
     * @mbg.generated
     */
    public String getSscodehintanswer() {
        return sscodehintanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.SSCODEHINTANSWER
     *
     * @param sscodehintanswer the value for SYSCOMUSERSTATUS.SSCODEHINTANSWER
     *
     * @mbg.generated
     */
    public void setSscodehintanswer(String sscodehintanswer) {
        this.sscodehintanswer = sscodehintanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.FAILEDPSWANSATTEMPTCOUNT
     *
     * @return the value of SYSCOMUSERSTATUS.FAILEDPSWANSATTEMPTCOUNT
     *
     * @mbg.generated
     */
    public Integer getFailedpswansattemptcount() {
        return failedpswansattemptcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.FAILEDPSWANSATTEMPTCOUNT
     *
     * @param failedpswansattemptcount the value for SYSCOMUSERSTATUS.FAILEDPSWANSATTEMPTCOUNT
     *
     * @mbg.generated
     */
    public void setFailedpswansattemptcount(Integer failedpswansattemptcount) {
        this.failedpswansattemptcount = failedpswansattemptcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.ISLOCKOUT
     *
     * @return the value of SYSCOMUSERSTATUS.ISLOCKOUT
     *
     * @mbg.generated
     */
    public Short getIslockout() {
        return islockout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.ISLOCKOUT
     *
     * @param islockout the value for SYSCOMUSERSTATUS.ISLOCKOUT
     *
     * @mbg.generated
     */
    public void setIslockout(Short islockout) {
        this.islockout = islockout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.LASTLOCKOUTTIME
     *
     * @return the value of SYSCOMUSERSTATUS.LASTLOCKOUTTIME
     *
     * @mbg.generated
     */
    public Date getLastlockouttime() {
        return lastlockouttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.LASTLOCKOUTTIME
     *
     * @param lastlockouttime the value for SYSCOMUSERSTATUS.LASTLOCKOUTTIME
     *
     * @mbg.generated
     */
    public void setLastlockouttime(Date lastlockouttime) {
        this.lastlockouttime = lastlockouttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.FAILEDPSWATTEMPTTIME
     *
     * @return the value of SYSCOMUSERSTATUS.FAILEDPSWATTEMPTTIME
     *
     * @mbg.generated
     */
    public Date getFailedpswattempttime() {
        return failedpswattempttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.FAILEDPSWATTEMPTTIME
     *
     * @param failedpswattempttime the value for SYSCOMUSERSTATUS.FAILEDPSWATTEMPTTIME
     *
     * @mbg.generated
     */
    public void setFailedpswattempttime(Date failedpswattempttime) {
        this.failedpswattempttime = failedpswattempttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.FAILEDPSWANSATTEMPTTIME
     *
     * @return the value of SYSCOMUSERSTATUS.FAILEDPSWANSATTEMPTTIME
     *
     * @mbg.generated
     */
    public Date getFailedpswansattempttime() {
        return failedpswansattempttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.FAILEDPSWANSATTEMPTTIME
     *
     * @param failedpswansattempttime the value for SYSCOMUSERSTATUS.FAILEDPSWANSATTEMPTTIME
     *
     * @mbg.generated
     */
    public void setFailedpswansattempttime(Date failedpswansattempttime) {
        this.failedpswansattempttime = failedpswansattempttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.SSCODEEFFECTDATE
     *
     * @return the value of SYSCOMUSERSTATUS.SSCODEEFFECTDATE
     *
     * @mbg.generated
     */
    public Date getSscodeeffectdate() {
        return sscodeeffectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.SSCODEEFFECTDATE
     *
     * @param sscodeeffectdate the value for SYSCOMUSERSTATUS.SSCODEEFFECTDATE
     *
     * @mbg.generated
     */
    public void setSscodeeffectdate(Date sscodeeffectdate) {
        this.sscodeeffectdate = sscodeeffectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.APDEFINE1
     *
     * @return the value of SYSCOMUSERSTATUS.APDEFINE1
     *
     * @mbg.generated
     */
    public String getApdefine1() {
        return apdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.APDEFINE1
     *
     * @param apdefine1 the value for SYSCOMUSERSTATUS.APDEFINE1
     *
     * @mbg.generated
     */
    public void setApdefine1(String apdefine1) {
        this.apdefine1 = apdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERSTATUS.APDEFINE2
     *
     * @return the value of SYSCOMUSERSTATUS.APDEFINE2
     *
     * @mbg.generated
     */
    public String getApdefine2() {
        return apdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERSTATUS.APDEFINE2
     *
     * @param apdefine2 the value for SYSCOMUSERSTATUS.APDEFINE2
     *
     * @mbg.generated
     */
    public void setApdefine2(String apdefine2) {
        this.apdefine2 = apdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSERSTATUS
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Syscomuserstatus other = (Syscomuserstatus) that;
        return (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getLogontime() == null ? other.getLogontime() == null : this.getLogontime().equals(other.getLogontime()))
            && (this.getLogonip() == null ? other.getLogonip() == null : this.getLogonip().equals(other.getLogonip()))
            && (this.getIslogon() == null ? other.getIslogon() == null : this.getIslogon().equals(other.getIslogon()))
            && (this.getLogonchangesscode() == null ? other.getLogonchangesscode() == null : this.getLogonchangesscode().equals(other.getLogonchangesscode()))
            && (this.getLastsscodechangetime() == null ? other.getLastsscodechangetime() == null : this.getLastsscodechangetime().equals(other.getLastsscodechangetime()))
            && (this.getSscodeerrorcount() == null ? other.getSscodeerrorcount() == null : this.getSscodeerrorcount().equals(other.getSscodeerrorcount()))
            && (this.getLastlogontime() == null ? other.getLastlogontime() == null : this.getLastlogontime().equals(other.getLastlogontime()))
            && (this.getLastlogonip() == null ? other.getLastlogonip() == null : this.getLastlogonip().equals(other.getLastlogonip()))
            && (this.getLastlogofftime() == null ? other.getLastlogofftime() == null : this.getLastlogofftime().equals(other.getLastlogofftime()))
            && (this.getSscode() == null ? other.getSscode() == null : this.getSscode().equals(other.getSscode()))
            && (this.getSscodeformat() == null ? other.getSscodeformat() == null : this.getSscodeformat().equals(other.getSscodeformat()))
            && (this.getSscodesalt() == null ? other.getSscodesalt() == null : this.getSscodesalt().equals(other.getSscodesalt()))
            && (this.getPkiserialno() == null ? other.getPkiserialno() == null : this.getPkiserialno().equals(other.getPkiserialno()))
            && (this.getSscodehintquestion() == null ? other.getSscodehintquestion() == null : this.getSscodehintquestion().equals(other.getSscodehintquestion()))
            && (this.getSscodehintanswer() == null ? other.getSscodehintanswer() == null : this.getSscodehintanswer().equals(other.getSscodehintanswer()))
            && (this.getFailedpswansattemptcount() == null ? other.getFailedpswansattemptcount() == null : this.getFailedpswansattemptcount().equals(other.getFailedpswansattemptcount()))
            && (this.getIslockout() == null ? other.getIslockout() == null : this.getIslockout().equals(other.getIslockout()))
            && (this.getLastlockouttime() == null ? other.getLastlockouttime() == null : this.getLastlockouttime().equals(other.getLastlockouttime()))
            && (this.getFailedpswattempttime() == null ? other.getFailedpswattempttime() == null : this.getFailedpswattempttime().equals(other.getFailedpswattempttime()))
            && (this.getFailedpswansattempttime() == null ? other.getFailedpswansattempttime() == null : this.getFailedpswansattempttime().equals(other.getFailedpswansattempttime()))
            && (this.getSscodeeffectdate() == null ? other.getSscodeeffectdate() == null : this.getSscodeeffectdate().equals(other.getSscodeeffectdate()))
            && (this.getApdefine1() == null ? other.getApdefine1() == null : this.getApdefine1().equals(other.getApdefine1()))
            && (this.getApdefine2() == null ? other.getApdefine2() == null : this.getApdefine2().equals(other.getApdefine2()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSERSTATUS
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
//        final int prime = 31;
        int result = 1;
        result = 31 * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = 31 * result + ((getLogontime() == null) ? 0 : getLogontime().hashCode());
        result = 31 * result + ((getLogonip() == null) ? 0 : getLogonip().hashCode());
        result = 31 * result + ((getIslogon() == null) ? 0 : getIslogon().hashCode());
        result = 31 * result + ((getLogonchangesscode() == null) ? 0 : getLogonchangesscode().hashCode());
        result = 31 * result + ((getLastsscodechangetime() == null) ? 0 : getLastsscodechangetime().hashCode());
        result = 31 * result + ((getSscodeerrorcount() == null) ? 0 : getSscodeerrorcount().hashCode());
        result = 31 * result + ((getLastlogontime() == null) ? 0 : getLastlogontime().hashCode());
        result = 31 * result + ((getLastlogonip() == null) ? 0 : getLastlogonip().hashCode());
        result = 31 * result + ((getLastlogofftime() == null) ? 0 : getLastlogofftime().hashCode());
        result = 31 * result + ((getSscode() == null) ? 0 : getSscode().hashCode());
        result = 31 * result + ((getSscodeformat() == null) ? 0 : getSscodeformat().hashCode());
        result = 31 * result + ((getSscodesalt() == null) ? 0 : getSscodesalt().hashCode());
        result = 31 * result + ((getPkiserialno() == null) ? 0 : getPkiserialno().hashCode());
        result = 31 * result + ((getSscodehintquestion() == null) ? 0 : getSscodehintquestion().hashCode());
        result = 31 * result + ((getSscodehintanswer() == null) ? 0 : getSscodehintanswer().hashCode());
        result = 31 * result + ((getFailedpswansattemptcount() == null) ? 0 : getFailedpswansattemptcount().hashCode());
        result = 31 * result + ((getIslockout() == null) ? 0 : getIslockout().hashCode());
        result = 31 * result + ((getLastlockouttime() == null) ? 0 : getLastlockouttime().hashCode());
        result = 31 * result + ((getFailedpswattempttime() == null) ? 0 : getFailedpswattempttime().hashCode());
        result = 31 * result + ((getFailedpswansattempttime() == null) ? 0 : getFailedpswansattempttime().hashCode());
        result = 31 * result + ((getSscodeeffectdate() == null) ? 0 : getSscodeeffectdate().hashCode());
        result = 31 * result + ((getApdefine1() == null) ? 0 : getApdefine1().hashCode());
        result = 31 * result + ((getApdefine2() == null) ? 0 : getApdefine2().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSERSTATUS
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", logontime=").append(logontime);
        sb.append(", logonip=").append(logonip);
        sb.append(", islogon=").append(islogon);
        sb.append(", logonchangesscode=").append(logonchangesscode);
        sb.append(", lastsscodechangetime=").append(lastsscodechangetime);
        sb.append(", sscodeerrorcount=").append(sscodeerrorcount);
        sb.append(", lastlogontime=").append(lastlogontime);
        sb.append(", lastlogonip=").append(lastlogonip);
        sb.append(", lastlogofftime=").append(lastlogofftime);
        sb.append(", sscode=").append(sscode);
        sb.append(", sscodeformat=").append(sscodeformat);
        sb.append(", sscodesalt=").append(sscodesalt);
        sb.append(", pkiserialno=").append(pkiserialno);
        sb.append(", sscodehintquestion=").append(sscodehintquestion);
        sb.append(", sscodehintanswer=").append(sscodehintanswer);
        sb.append(", failedpswansattemptcount=").append(failedpswansattemptcount);
        sb.append(", islockout=").append(islockout);
        sb.append(", lastlockouttime=").append(lastlockouttime);
        sb.append(", failedpswattempttime=").append(failedpswattempttime);
        sb.append(", failedpswansattempttime=").append(failedpswansattempttime);
        sb.append(", sscodeeffectdate=").append(sscodeeffectdate);
        sb.append(", apdefine1=").append(apdefine1);
        sb.append(", apdefine2=").append(apdefine2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSERSTATUS
     *
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<USERID>").append(this.userid).append("</USERID>");
        sb.append("<LOGONTIME>").append(this.logontime).append("</LOGONTIME>");
        sb.append("<LOGONIP>").append(this.logonip).append("</LOGONIP>");
        sb.append("<ISLOGON>").append(this.islogon).append("</ISLOGON>");
        sb.append("<LOGONCHANGESSCODE>").append(this.logonchangesscode).append("</LOGONCHANGESSCODE>");
        sb.append("<LASTSSCODECHANGETIME>").append(this.lastsscodechangetime).append("</LASTSSCODECHANGETIME>");
        sb.append("<SSCODEERRORCOUNT>").append(this.sscodeerrorcount).append("</SSCODEERRORCOUNT>");
        sb.append("<LASTLOGONTIME>").append(this.lastlogontime).append("</LASTLOGONTIME>");
        sb.append("<LASTLOGONIP>").append(this.lastlogonip).append("</LASTLOGONIP>");
        sb.append("<LASTLOGOFFTIME>").append(this.lastlogofftime).append("</LASTLOGOFFTIME>");
        sb.append("<SSCODE>").append(this.sscode).append("</SSCODE>");
        sb.append("<SSCODEFORMAT>").append(this.sscodeformat).append("</SSCODEFORMAT>");
        sb.append("<SSCODESALT>").append(this.sscodesalt).append("</SSCODESALT>");
        sb.append("<PKISERIALNO>").append(this.pkiserialno).append("</PKISERIALNO>");
        sb.append("<SSCODEHINTQUESTION>").append(this.sscodehintquestion).append("</SSCODEHINTQUESTION>");
        sb.append("<SSCODEHINTANSWER>").append(this.sscodehintanswer).append("</SSCODEHINTANSWER>");
        sb.append("<FAILEDPSWANSATTEMPTCOUNT>").append(this.failedpswansattemptcount).append("</FAILEDPSWANSATTEMPTCOUNT>");
        sb.append("<ISLOCKOUT>").append(this.islockout).append("</ISLOCKOUT>");
        sb.append("<LASTLOCKOUTTIME>").append(this.lastlockouttime).append("</LASTLOCKOUTTIME>");
        sb.append("<FAILEDPSWATTEMPTTIME>").append(this.failedpswattempttime).append("</FAILEDPSWATTEMPTTIME>");
        sb.append("<FAILEDPSWANSATTEMPTTIME>").append(this.failedpswansattempttime).append("</FAILEDPSWANSATTEMPTTIME>");
        sb.append("<SSCODEEFFECTDATE>").append(this.sscodeeffectdate).append("</SSCODEEFFECTDATE>");
        sb.append("<APDEFINE1>").append(this.apdefine1).append("</APDEFINE1>");
        sb.append("<APDEFINE2>").append(this.apdefine2).append("</APDEFINE2>");
        return sb.toString();
    }
}