package com.syscom.safeaa.mybatis.model;

import java.util.Date;

import com.syscom.safeaa.mybatis.vo.BaseModel;

public class Syscomauditlog extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMAUDITLOG.LOGID
     *
     * @mbg.generated
     */
    private String logid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMAUDITLOG.USERID
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMAUDITLOG.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMAUDITLOG.AUDITTYPE
     *
     * @mbg.generated
     */
    private Integer audittype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMAUDITLOG.RESULT
     *
     * @mbg.generated
     */
    private Short result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMAUDITLOG.AUDITTARGET
     *
     * @mbg.generated
     */
    private String audittarget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMAUDITLOG.UPDATELOGONIP
     *
     * @mbg.generated
     */
    private String updatelogonip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMAUDITLOG.APPLICATIONID
     *
     * @mbg.generated
     */
    private String applicationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMAUDITLOG.INCLUDEPERSONALDATA
     *
     * @mbg.generated
     */
    private Short includepersonaldata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMAUDITLOG.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMAUDITLOG.APDEFINE1
     *
     * @mbg.generated
     */
    private String apdefine1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMAUDITLOG.APDEFINE2
     *
     * @mbg.generated
     */
    private String apdefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCOMAUDITLOG
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMAUDITLOG
     *
     * @mbg.generated
     */
    public Syscomauditlog(String logid, Integer userid, Date updatetime, Integer audittype, Short result, String audittarget, String updatelogonip, String applicationid, Short includepersonaldata, String remark, String apdefine1, String apdefine2) {
        this.logid = logid;
        this.userid = userid;
        this.updatetime = updatetime;
        this.audittype = audittype;
        this.result = result;
        this.audittarget = audittarget;
        this.updatelogonip = updatelogonip;
        this.applicationid = applicationid;
        this.includepersonaldata = includepersonaldata;
        this.remark = remark;
        this.apdefine1 = apdefine1;
        this.apdefine2 = apdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMAUDITLOG
     *
     * @mbg.generated
     */
    public Syscomauditlog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMAUDITLOG.LOGID
     *
     * @return the value of SYSCOMAUDITLOG.LOGID
     *
     * @mbg.generated
     */
    public String getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMAUDITLOG.LOGID
     *
     * @param logid the value for SYSCOMAUDITLOG.LOGID
     *
     * @mbg.generated
     */
    public void setLogid(String logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMAUDITLOG.USERID
     *
     * @return the value of SYSCOMAUDITLOG.USERID
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMAUDITLOG.USERID
     *
     * @param userid the value for SYSCOMAUDITLOG.USERID
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMAUDITLOG.UPDATETIME
     *
     * @return the value of SYSCOMAUDITLOG.UPDATETIME
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMAUDITLOG.UPDATETIME
     *
     * @param updatetime the value for SYSCOMAUDITLOG.UPDATETIME
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMAUDITLOG.AUDITTYPE
     *
     * @return the value of SYSCOMAUDITLOG.AUDITTYPE
     *
     * @mbg.generated
     */
    public Integer getAudittype() {
        return audittype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMAUDITLOG.AUDITTYPE
     *
     * @param audittype the value for SYSCOMAUDITLOG.AUDITTYPE
     *
     * @mbg.generated
     */
    public void setAudittype(Integer audittype) {
        this.audittype = audittype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMAUDITLOG.RESULT
     *
     * @return the value of SYSCOMAUDITLOG.RESULT
     *
     * @mbg.generated
     */
    public Short getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMAUDITLOG.RESULT
     *
     * @param result the value for SYSCOMAUDITLOG.RESULT
     *
     * @mbg.generated
     */
    public void setResult(Short result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMAUDITLOG.AUDITTARGET
     *
     * @return the value of SYSCOMAUDITLOG.AUDITTARGET
     *
     * @mbg.generated
     */
    public String getAudittarget() {
        return audittarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMAUDITLOG.AUDITTARGET
     *
     * @param audittarget the value for SYSCOMAUDITLOG.AUDITTARGET
     *
     * @mbg.generated
     */
    public void setAudittarget(String audittarget) {
        this.audittarget = audittarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMAUDITLOG.UPDATELOGONIP
     *
     * @return the value of SYSCOMAUDITLOG.UPDATELOGONIP
     *
     * @mbg.generated
     */
    public String getUpdatelogonip() {
        return updatelogonip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMAUDITLOG.UPDATELOGONIP
     *
     * @param updatelogonip the value for SYSCOMAUDITLOG.UPDATELOGONIP
     *
     * @mbg.generated
     */
    public void setUpdatelogonip(String updatelogonip) {
        this.updatelogonip = updatelogonip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMAUDITLOG.APPLICATIONID
     *
     * @return the value of SYSCOMAUDITLOG.APPLICATIONID
     *
     * @mbg.generated
     */
    public String getApplicationid() {
        return applicationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMAUDITLOG.APPLICATIONID
     *
     * @param applicationid the value for SYSCOMAUDITLOG.APPLICATIONID
     *
     * @mbg.generated
     */
    public void setApplicationid(String applicationid) {
        this.applicationid = applicationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMAUDITLOG.INCLUDEPERSONALDATA
     *
     * @return the value of SYSCOMAUDITLOG.INCLUDEPERSONALDATA
     *
     * @mbg.generated
     */
    public Short getIncludepersonaldata() {
        return includepersonaldata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMAUDITLOG.INCLUDEPERSONALDATA
     *
     * @param includepersonaldata the value for SYSCOMAUDITLOG.INCLUDEPERSONALDATA
     *
     * @mbg.generated
     */
    public void setIncludepersonaldata(Short includepersonaldata) {
        this.includepersonaldata = includepersonaldata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMAUDITLOG.REMARK
     *
     * @return the value of SYSCOMAUDITLOG.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMAUDITLOG.REMARK
     *
     * @param remark the value for SYSCOMAUDITLOG.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMAUDITLOG.APDEFINE1
     *
     * @return the value of SYSCOMAUDITLOG.APDEFINE1
     *
     * @mbg.generated
     */
    public String getApdefine1() {
        return apdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMAUDITLOG.APDEFINE1
     *
     * @param apdefine1 the value for SYSCOMAUDITLOG.APDEFINE1
     *
     * @mbg.generated
     */
    public void setApdefine1(String apdefine1) {
        this.apdefine1 = apdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMAUDITLOG.APDEFINE2
     *
     * @return the value of SYSCOMAUDITLOG.APDEFINE2
     *
     * @mbg.generated
     */
    public String getApdefine2() {
        return apdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMAUDITLOG.APDEFINE2
     *
     * @param apdefine2 the value for SYSCOMAUDITLOG.APDEFINE2
     *
     * @mbg.generated
     */
    public void setApdefine2(String apdefine2) {
        this.apdefine2 = apdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMAUDITLOG
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Syscomauditlog other = (Syscomauditlog) that;
        return (this.getLogid() == null ? other.getLogid() == null : this.getLogid().equals(other.getLogid()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()))
            && (this.getAudittype() == null ? other.getAudittype() == null : this.getAudittype().equals(other.getAudittype()))
            && (this.getResult() == null ? other.getResult() == null : this.getResult().equals(other.getResult()))
            && (this.getAudittarget() == null ? other.getAudittarget() == null : this.getAudittarget().equals(other.getAudittarget()))
            && (this.getUpdatelogonip() == null ? other.getUpdatelogonip() == null : this.getUpdatelogonip().equals(other.getUpdatelogonip()))
            && (this.getApplicationid() == null ? other.getApplicationid() == null : this.getApplicationid().equals(other.getApplicationid()))
            && (this.getIncludepersonaldata() == null ? other.getIncludepersonaldata() == null : this.getIncludepersonaldata().equals(other.getIncludepersonaldata()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getApdefine1() == null ? other.getApdefine1() == null : this.getApdefine1().equals(other.getApdefine1()))
            && (this.getApdefine2() == null ? other.getApdefine2() == null : this.getApdefine2().equals(other.getApdefine2()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMAUDITLOG
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
//        final int prime = 31;
        int result = 1;
        result = 31 * result + ((getLogid() == null) ? 0 : getLogid().hashCode());
        result = 31 * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = 31 * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        result = 31 * result + ((getAudittype() == null) ? 0 : getAudittype().hashCode());
        result = 31 * result + ((getResult() == null) ? 0 : getResult().hashCode());
        result = 31 * result + ((getAudittarget() == null) ? 0 : getAudittarget().hashCode());
        result = 31 * result + ((getUpdatelogonip() == null) ? 0 : getUpdatelogonip().hashCode());
        result = 31 * result + ((getApplicationid() == null) ? 0 : getApplicationid().hashCode());
        result = 31 * result + ((getIncludepersonaldata() == null) ? 0 : getIncludepersonaldata().hashCode());
        result = 31 * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = 31 * result + ((getApdefine1() == null) ? 0 : getApdefine1().hashCode());
        result = 31 * result + ((getApdefine2() == null) ? 0 : getApdefine2().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMAUDITLOG
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", logid=").append(logid);
        sb.append(", userid=").append(userid);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", audittype=").append(audittype);
        sb.append(", result=").append(result);
        sb.append(", audittarget=").append(audittarget);
        sb.append(", updatelogonip=").append(updatelogonip);
        sb.append(", applicationid=").append(applicationid);
        sb.append(", includepersonaldata=").append(includepersonaldata);
        sb.append(", remark=").append(remark);
        sb.append(", apdefine1=").append(apdefine1);
        sb.append(", apdefine2=").append(apdefine2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMAUDITLOG
     *
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<LOGID>").append(this.logid).append("</LOGID>");
        sb.append("<USERID>").append(this.userid).append("</USERID>");
        sb.append("<UPDATETIME>").append(this.updatetime).append("</UPDATETIME>");
        sb.append("<AUDITTYPE>").append(this.audittype).append("</AUDITTYPE>");
        sb.append("<RESULT>").append(this.result).append("</RESULT>");
        sb.append("<AUDITTARGET>").append(this.audittarget).append("</AUDITTARGET>");
        sb.append("<UPDATELOGONIP>").append(this.updatelogonip).append("</UPDATELOGONIP>");
        sb.append("<APPLICATIONID>").append(this.applicationid).append("</APPLICATIONID>");
        sb.append("<INCLUDEPERSONALDATA>").append(this.includepersonaldata).append("</INCLUDEPERSONALDATA>");
        sb.append("<REMARK>").append(this.remark).append("</REMARK>");
        sb.append("<APDEFINE1>").append(this.apdefine1).append("</APDEFINE1>");
        sb.append("<APDEFINE2>").append(this.apdefine2).append("</APDEFINE2>");
        return sb.toString();
    }
}