package com.syscom.safeaa.mybatis.model;

import com.syscom.safeaa.mybatis.vo.BaseModel;
import java.util.Date;

public class Syscomtemplatemembers extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMTEMPLATEMEMBERS.TEMPLATEID
     *
     * @mbg.generated
     */
    private Integer templateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMTEMPLATEMEMBERS.POLICYID
     *
     * @mbg.generated
     */
    private Integer policyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMTEMPLATEMEMBERS.POLICYVALUE
     *
     * @mbg.generated
     */
    private String policyvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMTEMPLATEMEMBERS.EFFECTDATE
     *
     * @mbg.generated
     */
    private Date effectdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMTEMPLATEMEMBERS.EXPIREDDATE
     *
     * @mbg.generated
     */
    private Date expireddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMTEMPLATEMEMBERS.UPDATEUSERID
     *
     * @mbg.generated
     */
    private Integer updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMTEMPLATEMEMBERS.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCOMTEMPLATEMEMBERS
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATEMEMBERS
     *
     * @mbg.generated
     */
    public Syscomtemplatemembers(Integer templateid, Integer policyid, String policyvalue, Date effectdate, Date expireddate, Integer updateuserid, Date updatetime) {
        this.templateid = templateid;
        this.policyid = policyid;
        this.policyvalue = policyvalue;
        this.effectdate = effectdate;
        this.expireddate = expireddate;
        this.updateuserid = updateuserid;
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATEMEMBERS
     *
     * @mbg.generated
     */
    public Syscomtemplatemembers() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMTEMPLATEMEMBERS.TEMPLATEID
     *
     * @return the value of SYSCOMTEMPLATEMEMBERS.TEMPLATEID
     *
     * @mbg.generated
     */
    public Integer getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMTEMPLATEMEMBERS.TEMPLATEID
     *
     * @param templateid the value for SYSCOMTEMPLATEMEMBERS.TEMPLATEID
     *
     * @mbg.generated
     */
    public void setTemplateid(Integer templateid) {
        this.templateid = templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMTEMPLATEMEMBERS.POLICYID
     *
     * @return the value of SYSCOMTEMPLATEMEMBERS.POLICYID
     *
     * @mbg.generated
     */
    public Integer getPolicyid() {
        return policyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMTEMPLATEMEMBERS.POLICYID
     *
     * @param policyid the value for SYSCOMTEMPLATEMEMBERS.POLICYID
     *
     * @mbg.generated
     */
    public void setPolicyid(Integer policyid) {
        this.policyid = policyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMTEMPLATEMEMBERS.POLICYVALUE
     *
     * @return the value of SYSCOMTEMPLATEMEMBERS.POLICYVALUE
     *
     * @mbg.generated
     */
    public String getPolicyvalue() {
        return policyvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMTEMPLATEMEMBERS.POLICYVALUE
     *
     * @param policyvalue the value for SYSCOMTEMPLATEMEMBERS.POLICYVALUE
     *
     * @mbg.generated
     */
    public void setPolicyvalue(String policyvalue) {
        this.policyvalue = policyvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMTEMPLATEMEMBERS.EFFECTDATE
     *
     * @return the value of SYSCOMTEMPLATEMEMBERS.EFFECTDATE
     *
     * @mbg.generated
     */
    public Date getEffectdate() {
        return effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMTEMPLATEMEMBERS.EFFECTDATE
     *
     * @param effectdate the value for SYSCOMTEMPLATEMEMBERS.EFFECTDATE
     *
     * @mbg.generated
     */
    public void setEffectdate(Date effectdate) {
        this.effectdate = effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMTEMPLATEMEMBERS.EXPIREDDATE
     *
     * @return the value of SYSCOMTEMPLATEMEMBERS.EXPIREDDATE
     *
     * @mbg.generated
     */
    public Date getExpireddate() {
        return expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMTEMPLATEMEMBERS.EXPIREDDATE
     *
     * @param expireddate the value for SYSCOMTEMPLATEMEMBERS.EXPIREDDATE
     *
     * @mbg.generated
     */
    public void setExpireddate(Date expireddate) {
        this.expireddate = expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMTEMPLATEMEMBERS.UPDATEUSERID
     *
     * @return the value of SYSCOMTEMPLATEMEMBERS.UPDATEUSERID
     *
     * @mbg.generated
     */
    public Integer getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMTEMPLATEMEMBERS.UPDATEUSERID
     *
     * @param updateuserid the value for SYSCOMTEMPLATEMEMBERS.UPDATEUSERID
     *
     * @mbg.generated
     */
    public void setUpdateuserid(Integer updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMTEMPLATEMEMBERS.UPDATETIME
     *
     * @return the value of SYSCOMTEMPLATEMEMBERS.UPDATETIME
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMTEMPLATEMEMBERS.UPDATETIME
     *
     * @param updatetime the value for SYSCOMTEMPLATEMEMBERS.UPDATETIME
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATEMEMBERS
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Syscomtemplatemembers other = (Syscomtemplatemembers) that;
        return (this.getTemplateid() == null ? other.getTemplateid() == null : this.getTemplateid().equals(other.getTemplateid()))
            && (this.getPolicyid() == null ? other.getPolicyid() == null : this.getPolicyid().equals(other.getPolicyid()))
            && (this.getPolicyvalue() == null ? other.getPolicyvalue() == null : this.getPolicyvalue().equals(other.getPolicyvalue()))
            && (this.getEffectdate() == null ? other.getEffectdate() == null : this.getEffectdate().equals(other.getEffectdate()))
            && (this.getExpireddate() == null ? other.getExpireddate() == null : this.getExpireddate().equals(other.getExpireddate()))
            && (this.getUpdateuserid() == null ? other.getUpdateuserid() == null : this.getUpdateuserid().equals(other.getUpdateuserid()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATEMEMBERS
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTemplateid() == null) ? 0 : getTemplateid().hashCode());
        result = prime * result + ((getPolicyid() == null) ? 0 : getPolicyid().hashCode());
        result = prime * result + ((getPolicyvalue() == null) ? 0 : getPolicyvalue().hashCode());
        result = prime * result + ((getEffectdate() == null) ? 0 : getEffectdate().hashCode());
        result = prime * result + ((getExpireddate() == null) ? 0 : getExpireddate().hashCode());
        result = prime * result + ((getUpdateuserid() == null) ? 0 : getUpdateuserid().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATEMEMBERS
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", templateid=").append(templateid);
        sb.append(", policyid=").append(policyid);
        sb.append(", policyvalue=").append(policyvalue);
        sb.append(", effectdate=").append(effectdate);
        sb.append(", expireddate=").append(expireddate);
        sb.append(", updateuserid=").append(updateuserid);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATEMEMBERS
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<TEMPLATEID>").append(this.templateid).append("</TEMPLATEID>");
        sb.append("<POLICYID>").append(this.policyid).append("</POLICYID>");
        sb.append("<POLICYVALUE>").append(this.policyvalue).append("</POLICYVALUE>");
        sb.append("<EFFECTDATE>").append(this.effectdate).append("</EFFECTDATE>");
        sb.append("<EXPIREDDATE>").append(this.expireddate).append("</EXPIREDDATE>");
        sb.append("<UPDATEUSERID>").append(this.updateuserid).append("</UPDATEUSERID>");
        sb.append("<UPDATETIME>").append(this.updatetime).append("</UPDATETIME>");
        return sb.toString();
    }
}