package com.syscom.safeaa.mybatis.model;

import java.util.Date;

import com.syscom.safeaa.mybatis.vo.BaseModel;

public class Syscomgroupmembers extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.GROUPID
     *
     * @mbg.generated
     */
    private Integer groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.CHILDID
     *
     * @mbg.generated
     */
    private Integer childid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.CHILDTYPE
     *
     * @mbg.generated
     */
    private String childtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.LOCATIONNO
     *
     * @mbg.generated
     */
    private Integer locationno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.EFFECTDATE
     *
     * @mbg.generated
     */
    private Date effectdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.EXPIREDDATE
     *
     * @mbg.generated
     */
    private Date expireddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.UPDATEUSERID
     *
     * @mbg.generated
     */
    private Integer updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.SAFEDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    private String safedefinefunctionlist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.USERDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    private String userdefinefunctionlist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCOMGROUPMEMBERS
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPMEMBERS
     *
     * @mbg.generated
     */
    public Syscomgroupmembers(Integer groupid, Integer childid, String childtype, Integer locationno, Date effectdate, Date expireddate, Integer updateuserid, Date updatetime, String safedefinefunctionlist, String userdefinefunctionlist) {
        this.groupid = groupid;
        this.childid = childid;
        this.childtype = childtype;
        this.locationno = locationno;
        this.effectdate = effectdate;
        this.expireddate = expireddate;
        this.updateuserid = updateuserid;
        this.updatetime = updatetime;
        this.safedefinefunctionlist = safedefinefunctionlist;
        this.userdefinefunctionlist = userdefinefunctionlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPMEMBERS
     *
     * @mbg.generated
     */
    public Syscomgroupmembers() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.GROUPID
     *
     * @return the value of SYSCOMGROUPMEMBERS.GROUPID
     *
     * @mbg.generated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.GROUPID
     *
     * @param groupid the value for SYSCOMGROUPMEMBERS.GROUPID
     *
     * @mbg.generated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.CHILDID
     *
     * @return the value of SYSCOMGROUPMEMBERS.CHILDID
     *
     * @mbg.generated
     */
    public Integer getChildid() {
        return childid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.CHILDID
     *
     * @param childid the value for SYSCOMGROUPMEMBERS.CHILDID
     *
     * @mbg.generated
     */
    public void setChildid(Integer childid) {
        this.childid = childid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.CHILDTYPE
     *
     * @return the value of SYSCOMGROUPMEMBERS.CHILDTYPE
     *
     * @mbg.generated
     */
    public String getChildtype() {
        return childtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.CHILDTYPE
     *
     * @param childtype the value for SYSCOMGROUPMEMBERS.CHILDTYPE
     *
     * @mbg.generated
     */
    public void setChildtype(String childtype) {
        this.childtype = childtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.LOCATIONNO
     *
     * @return the value of SYSCOMGROUPMEMBERS.LOCATIONNO
     *
     * @mbg.generated
     */
    public Integer getLocationno() {
        return locationno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.LOCATIONNO
     *
     * @param locationno the value for SYSCOMGROUPMEMBERS.LOCATIONNO
     *
     * @mbg.generated
     */
    public void setLocationno(Integer locationno) {
        this.locationno = locationno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.EFFECTDATE
     *
     * @return the value of SYSCOMGROUPMEMBERS.EFFECTDATE
     *
     * @mbg.generated
     */
    public Date getEffectdate() {
        return effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.EFFECTDATE
     *
     * @param effectdate the value for SYSCOMGROUPMEMBERS.EFFECTDATE
     *
     * @mbg.generated
     */
    public void setEffectdate(Date effectdate) {
        this.effectdate = effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.EXPIREDDATE
     *
     * @return the value of SYSCOMGROUPMEMBERS.EXPIREDDATE
     *
     * @mbg.generated
     */
    public Date getExpireddate() {
        return expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.EXPIREDDATE
     *
     * @param expireddate the value for SYSCOMGROUPMEMBERS.EXPIREDDATE
     *
     * @mbg.generated
     */
    public void setExpireddate(Date expireddate) {
        this.expireddate = expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.UPDATEUSERID
     *
     * @return the value of SYSCOMGROUPMEMBERS.UPDATEUSERID
     *
     * @mbg.generated
     */
    public Integer getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.UPDATEUSERID
     *
     * @param updateuserid the value for SYSCOMGROUPMEMBERS.UPDATEUSERID
     *
     * @mbg.generated
     */
    public void setUpdateuserid(Integer updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.UPDATETIME
     *
     * @return the value of SYSCOMGROUPMEMBERS.UPDATETIME
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.UPDATETIME
     *
     * @param updatetime the value for SYSCOMGROUPMEMBERS.UPDATETIME
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.SAFEDEFINEFUNCTIONLIST
     *
     * @return the value of SYSCOMGROUPMEMBERS.SAFEDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    public String getSafedefinefunctionlist() {
        return safedefinefunctionlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.SAFEDEFINEFUNCTIONLIST
     *
     * @param safedefinefunctionlist the value for SYSCOMGROUPMEMBERS.SAFEDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    public void setSafedefinefunctionlist(String safedefinefunctionlist) {
        this.safedefinefunctionlist = safedefinefunctionlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.USERDEFINEFUNCTIONLIST
     *
     * @return the value of SYSCOMGROUPMEMBERS.USERDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    public String getUserdefinefunctionlist() {
        return userdefinefunctionlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.USERDEFINEFUNCTIONLIST
     *
     * @param userdefinefunctionlist the value for SYSCOMGROUPMEMBERS.USERDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    public void setUserdefinefunctionlist(String userdefinefunctionlist) {
        this.userdefinefunctionlist = userdefinefunctionlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPMEMBERS
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Syscomgroupmembers other = (Syscomgroupmembers) that;
        return (this.getGroupid() == null ? other.getGroupid() == null : this.getGroupid().equals(other.getGroupid()))
            && (this.getChildid() == null ? other.getChildid() == null : this.getChildid().equals(other.getChildid()))
            && (this.getChildtype() == null ? other.getChildtype() == null : this.getChildtype().equals(other.getChildtype()))
            && (this.getLocationno() == null ? other.getLocationno() == null : this.getLocationno().equals(other.getLocationno()))
            && (this.getEffectdate() == null ? other.getEffectdate() == null : this.getEffectdate().equals(other.getEffectdate()))
            && (this.getExpireddate() == null ? other.getExpireddate() == null : this.getExpireddate().equals(other.getExpireddate()))
            && (this.getUpdateuserid() == null ? other.getUpdateuserid() == null : this.getUpdateuserid().equals(other.getUpdateuserid()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()))
            && (this.getSafedefinefunctionlist() == null ? other.getSafedefinefunctionlist() == null : this.getSafedefinefunctionlist().equals(other.getSafedefinefunctionlist()))
            && (this.getUserdefinefunctionlist() == null ? other.getUserdefinefunctionlist() == null : this.getUserdefinefunctionlist().equals(other.getUserdefinefunctionlist()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPMEMBERS
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
//        final int prime = 31;
        int result = 1;
        result = 31 * result + ((getGroupid() == null) ? 0 : getGroupid().hashCode());
        result = 31 * result + ((getChildid() == null) ? 0 : getChildid().hashCode());
        result = 31 * result + ((getChildtype() == null) ? 0 : getChildtype().hashCode());
        result = 31 * result + ((getLocationno() == null) ? 0 : getLocationno().hashCode());
        result = 31 * result + ((getEffectdate() == null) ? 0 : getEffectdate().hashCode());
        result = 31 * result + ((getExpireddate() == null) ? 0 : getExpireddate().hashCode());
        result = 31 * result + ((getUpdateuserid() == null) ? 0 : getUpdateuserid().hashCode());
        result = 31 * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        result = 31 * result + ((getSafedefinefunctionlist() == null) ? 0 : getSafedefinefunctionlist().hashCode());
        result = 31 * result + ((getUserdefinefunctionlist() == null) ? 0 : getUserdefinefunctionlist().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPMEMBERS
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupid=").append(groupid);
        sb.append(", childid=").append(childid);
        sb.append(", childtype=").append(childtype);
        sb.append(", locationno=").append(locationno);
        sb.append(", effectdate=").append(effectdate);
        sb.append(", expireddate=").append(expireddate);
        sb.append(", updateuserid=").append(updateuserid);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", safedefinefunctionlist=").append(safedefinefunctionlist);
        sb.append(", userdefinefunctionlist=").append(userdefinefunctionlist);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPMEMBERS
     *
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<GROUPID>").append(this.groupid).append("</GROUPID>");
        sb.append("<CHILDID>").append(this.childid).append("</CHILDID>");
        sb.append("<CHILDTYPE>").append(this.childtype).append("</CHILDTYPE>");
        sb.append("<LOCATIONNO>").append(this.locationno).append("</LOCATIONNO>");
        sb.append("<EFFECTDATE>").append(this.effectdate).append("</EFFECTDATE>");
        sb.append("<EXPIREDDATE>").append(this.expireddate).append("</EXPIREDDATE>");
        sb.append("<UPDATEUSERID>").append(this.updateuserid).append("</UPDATEUSERID>");
        sb.append("<UPDATETIME>").append(this.updatetime).append("</UPDATETIME>");
        sb.append("<SAFEDEFINEFUNCTIONLIST>").append(this.safedefinefunctionlist).append("</SAFEDEFINEFUNCTIONLIST>");
        sb.append("<USERDEFINEFUNCTIONLIST>").append(this.userdefinefunctionlist).append("</USERDEFINEFUNCTIONLIST>");
        return sb.toString();
    }
}