package com.syscom.safeaa.mybatis.model;

import java.util.Date;

import com.syscom.safeaa.mybatis.vo.BaseModel;

public class Syscomroledeny extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLEDENY.ROLEID
     *
     * @mbg.generated
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLEDENY.CHILDID
     *
     * @mbg.generated
     */
    private Integer childid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLEDENY.CHILDTYPE
     *
     * @mbg.generated
     */
    private String childtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLEDENY.UPDATEUSERID
     *
     * @mbg.generated
     */
    private Integer updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLEDENY.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCOMROLEDENY
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEDENY
     *
     * @mbg.generated
     */
    public Syscomroledeny(Integer roleid, Integer childid, String childtype, Integer updateuserid, Date updatetime) {
        this.roleid = roleid;
        this.childid = childid;
        this.childtype = childtype;
        this.updateuserid = updateuserid;
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEDENY
     *
     * @mbg.generated
     */
    public Syscomroledeny() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLEDENY.ROLEID
     *
     * @return the value of SYSCOMROLEDENY.ROLEID
     *
     * @mbg.generated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLEDENY.ROLEID
     *
     * @param roleid the value for SYSCOMROLEDENY.ROLEID
     *
     * @mbg.generated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLEDENY.CHILDID
     *
     * @return the value of SYSCOMROLEDENY.CHILDID
     *
     * @mbg.generated
     */
    public Integer getChildid() {
        return childid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLEDENY.CHILDID
     *
     * @param childid the value for SYSCOMROLEDENY.CHILDID
     *
     * @mbg.generated
     */
    public void setChildid(Integer childid) {
        this.childid = childid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLEDENY.CHILDTYPE
     *
     * @return the value of SYSCOMROLEDENY.CHILDTYPE
     *
     * @mbg.generated
     */
    public String getChildtype() {
        return childtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLEDENY.CHILDTYPE
     *
     * @param childtype the value for SYSCOMROLEDENY.CHILDTYPE
     *
     * @mbg.generated
     */
    public void setChildtype(String childtype) {
        this.childtype = childtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLEDENY.UPDATEUSERID
     *
     * @return the value of SYSCOMROLEDENY.UPDATEUSERID
     *
     * @mbg.generated
     */
    public Integer getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLEDENY.UPDATEUSERID
     *
     * @param updateuserid the value for SYSCOMROLEDENY.UPDATEUSERID
     *
     * @mbg.generated
     */
    public void setUpdateuserid(Integer updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLEDENY.UPDATETIME
     *
     * @return the value of SYSCOMROLEDENY.UPDATETIME
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLEDENY.UPDATETIME
     *
     * @param updatetime the value for SYSCOMROLEDENY.UPDATETIME
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEDENY
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Syscomroledeny other = (Syscomroledeny) that;
        return (this.getRoleid() == null ? other.getRoleid() == null : this.getRoleid().equals(other.getRoleid()))
            && (this.getChildid() == null ? other.getChildid() == null : this.getChildid().equals(other.getChildid()))
            && (this.getChildtype() == null ? other.getChildtype() == null : this.getChildtype().equals(other.getChildtype()))
            && (this.getUpdateuserid() == null ? other.getUpdateuserid() == null : this.getUpdateuserid().equals(other.getUpdateuserid()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEDENY
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
//        final int 31 = 31;
        int result = 1;
        result = 31 * result + ((getRoleid() == null) ? 0 : getRoleid().hashCode());
        result = 31 * result + ((getChildid() == null) ? 0 : getChildid().hashCode());
        result = 31 * result + ((getChildtype() == null) ? 0 : getChildtype().hashCode());
        result = 31 * result + ((getUpdateuserid() == null) ? 0 : getUpdateuserid().hashCode());
        result = 31 * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEDENY
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleid=").append(roleid);
        sb.append(", childid=").append(childid);
        sb.append(", childtype=").append(childtype);
        sb.append(", updateuserid=").append(updateuserid);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEDENY
     *
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<ROLEID>").append(this.roleid).append("</ROLEID>");
        sb.append("<CHILDID>").append(this.childid).append("</CHILDID>");
        sb.append("<CHILDTYPE>").append(this.childtype).append("</CHILDTYPE>");
        sb.append("<UPDATEUSERID>").append(this.updateuserid).append("</UPDATEUSERID>");
        sb.append("<UPDATETIME>").append(this.updatetime).append("</UPDATETIME>");
        return sb.toString();
    }
}