package com.syscom.safeaa.mybatis.model;

import com.syscom.safeaa.mybatis.vo.BaseModel;
import java.util.Date;

public class Syscomuserdeputy extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERDEPUTY.USERID
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERDEPUTY.ROLEID
     *
     * @mbg.generated
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERDEPUTY.DEPUTYUSERID
     *
     * @mbg.generated
     */
    private Integer deputyuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERDEPUTY.EFFECTDATE
     *
     * @mbg.generated
     */
    private Date effectdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERDEPUTY.EXPIREDDATE
     *
     * @mbg.generated
     */
    private Date expireddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERDEPUTY.UPDATEUSERID
     *
     * @mbg.generated
     */
    private Integer updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMUSERDEPUTY.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCOMUSERDEPUTY
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSERDEPUTY
     *
     * @mbg.generated
     */
    public Syscomuserdeputy(Integer userid, Integer roleid, Integer deputyuserid, Date effectdate, Date expireddate, Integer updateuserid, Date updatetime) {
        this.userid = userid;
        this.roleid = roleid;
        this.deputyuserid = deputyuserid;
        this.effectdate = effectdate;
        this.expireddate = expireddate;
        this.updateuserid = updateuserid;
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSERDEPUTY
     *
     * @mbg.generated
     */
    public Syscomuserdeputy() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERDEPUTY.USERID
     *
     * @return the value of SYSCOMUSERDEPUTY.USERID
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERDEPUTY.USERID
     *
     * @param userid the value for SYSCOMUSERDEPUTY.USERID
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERDEPUTY.ROLEID
     *
     * @return the value of SYSCOMUSERDEPUTY.ROLEID
     *
     * @mbg.generated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERDEPUTY.ROLEID
     *
     * @param roleid the value for SYSCOMUSERDEPUTY.ROLEID
     *
     * @mbg.generated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERDEPUTY.DEPUTYUSERID
     *
     * @return the value of SYSCOMUSERDEPUTY.DEPUTYUSERID
     *
     * @mbg.generated
     */
    public Integer getDeputyuserid() {
        return deputyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERDEPUTY.DEPUTYUSERID
     *
     * @param deputyuserid the value for SYSCOMUSERDEPUTY.DEPUTYUSERID
     *
     * @mbg.generated
     */
    public void setDeputyuserid(Integer deputyuserid) {
        this.deputyuserid = deputyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERDEPUTY.EFFECTDATE
     *
     * @return the value of SYSCOMUSERDEPUTY.EFFECTDATE
     *
     * @mbg.generated
     */
    public Date getEffectdate() {
        return effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERDEPUTY.EFFECTDATE
     *
     * @param effectdate the value for SYSCOMUSERDEPUTY.EFFECTDATE
     *
     * @mbg.generated
     */
    public void setEffectdate(Date effectdate) {
        this.effectdate = effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERDEPUTY.EXPIREDDATE
     *
     * @return the value of SYSCOMUSERDEPUTY.EXPIREDDATE
     *
     * @mbg.generated
     */
    public Date getExpireddate() {
        return expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERDEPUTY.EXPIREDDATE
     *
     * @param expireddate the value for SYSCOMUSERDEPUTY.EXPIREDDATE
     *
     * @mbg.generated
     */
    public void setExpireddate(Date expireddate) {
        this.expireddate = expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERDEPUTY.UPDATEUSERID
     *
     * @return the value of SYSCOMUSERDEPUTY.UPDATEUSERID
     *
     * @mbg.generated
     */
    public Integer getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERDEPUTY.UPDATEUSERID
     *
     * @param updateuserid the value for SYSCOMUSERDEPUTY.UPDATEUSERID
     *
     * @mbg.generated
     */
    public void setUpdateuserid(Integer updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMUSERDEPUTY.UPDATETIME
     *
     * @return the value of SYSCOMUSERDEPUTY.UPDATETIME
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMUSERDEPUTY.UPDATETIME
     *
     * @param updatetime the value for SYSCOMUSERDEPUTY.UPDATETIME
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSERDEPUTY
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Syscomuserdeputy other = (Syscomuserdeputy) that;
        return (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getRoleid() == null ? other.getRoleid() == null : this.getRoleid().equals(other.getRoleid()))
            && (this.getDeputyuserid() == null ? other.getDeputyuserid() == null : this.getDeputyuserid().equals(other.getDeputyuserid()))
            && (this.getEffectdate() == null ? other.getEffectdate() == null : this.getEffectdate().equals(other.getEffectdate()))
            && (this.getExpireddate() == null ? other.getExpireddate() == null : this.getExpireddate().equals(other.getExpireddate()))
            && (this.getUpdateuserid() == null ? other.getUpdateuserid() == null : this.getUpdateuserid().equals(other.getUpdateuserid()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSERDEPUTY
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getRoleid() == null) ? 0 : getRoleid().hashCode());
        result = prime * result + ((getDeputyuserid() == null) ? 0 : getDeputyuserid().hashCode());
        result = prime * result + ((getEffectdate() == null) ? 0 : getEffectdate().hashCode());
        result = prime * result + ((getExpireddate() == null) ? 0 : getExpireddate().hashCode());
        result = prime * result + ((getUpdateuserid() == null) ? 0 : getUpdateuserid().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSERDEPUTY
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", roleid=").append(roleid);
        sb.append(", deputyuserid=").append(deputyuserid);
        sb.append(", effectdate=").append(effectdate);
        sb.append(", expireddate=").append(expireddate);
        sb.append(", updateuserid=").append(updateuserid);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSERDEPUTY
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<USERID>").append(this.userid).append("</USERID>");
        sb.append("<ROLEID>").append(this.roleid).append("</ROLEID>");
        sb.append("<DEPUTYUSERID>").append(this.deputyuserid).append("</DEPUTYUSERID>");
        sb.append("<EFFECTDATE>").append(this.effectdate).append("</EFFECTDATE>");
        sb.append("<EXPIREDDATE>").append(this.expireddate).append("</EXPIREDDATE>");
        sb.append("<UPDATEUSERID>").append(this.updateuserid).append("</UPDATEUSERID>");
        sb.append("<UPDATETIME>").append(this.updatetime).append("</UPDATETIME>");
        return sb.toString();
    }
}