package com.syscom.safeaa.mybatis.model;

import com.syscom.safeaa.mybatis.vo.BaseModel;
import java.util.Date;

public class Syscomroletemplate extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLETEMPLATE.ROLEID
     *
     * @mbg.generated
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLETEMPLATE.TEMPLATEID
     *
     * @mbg.generated
     */
    private Integer templateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLETEMPLATE.UPDATEUSERID
     *
     * @mbg.generated
     */
    private Integer updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLETEMPLATE.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCOMROLETEMPLATE
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLETEMPLATE
     *
     * @mbg.generated
     */
    public Syscomroletemplate(Integer roleid, Integer templateid, Integer updateuserid, Date updatetime) {
        this.roleid = roleid;
        this.templateid = templateid;
        this.updateuserid = updateuserid;
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLETEMPLATE
     *
     * @mbg.generated
     */
    public Syscomroletemplate() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLETEMPLATE.ROLEID
     *
     * @return the value of SYSCOMROLETEMPLATE.ROLEID
     *
     * @mbg.generated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLETEMPLATE.ROLEID
     *
     * @param roleid the value for SYSCOMROLETEMPLATE.ROLEID
     *
     * @mbg.generated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLETEMPLATE.TEMPLATEID
     *
     * @return the value of SYSCOMROLETEMPLATE.TEMPLATEID
     *
     * @mbg.generated
     */
    public Integer getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLETEMPLATE.TEMPLATEID
     *
     * @param templateid the value for SYSCOMROLETEMPLATE.TEMPLATEID
     *
     * @mbg.generated
     */
    public void setTemplateid(Integer templateid) {
        this.templateid = templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLETEMPLATE.UPDATEUSERID
     *
     * @return the value of SYSCOMROLETEMPLATE.UPDATEUSERID
     *
     * @mbg.generated
     */
    public Integer getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLETEMPLATE.UPDATEUSERID
     *
     * @param updateuserid the value for SYSCOMROLETEMPLATE.UPDATEUSERID
     *
     * @mbg.generated
     */
    public void setUpdateuserid(Integer updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLETEMPLATE.UPDATETIME
     *
     * @return the value of SYSCOMROLETEMPLATE.UPDATETIME
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLETEMPLATE.UPDATETIME
     *
     * @param updatetime the value for SYSCOMROLETEMPLATE.UPDATETIME
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLETEMPLATE
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Syscomroletemplate other = (Syscomroletemplate) that;
        return (this.getRoleid() == null ? other.getRoleid() == null : this.getRoleid().equals(other.getRoleid()))
            && (this.getTemplateid() == null ? other.getTemplateid() == null : this.getTemplateid().equals(other.getTemplateid()))
            && (this.getUpdateuserid() == null ? other.getUpdateuserid() == null : this.getUpdateuserid().equals(other.getUpdateuserid()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLETEMPLATE
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleid() == null) ? 0 : getRoleid().hashCode());
        result = prime * result + ((getTemplateid() == null) ? 0 : getTemplateid().hashCode());
        result = prime * result + ((getUpdateuserid() == null) ? 0 : getUpdateuserid().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLETEMPLATE
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleid=").append(roleid);
        sb.append(", templateid=").append(templateid);
        sb.append(", updateuserid=").append(updateuserid);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLETEMPLATE
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<ROLEID>").append(this.roleid).append("</ROLEID>");
        sb.append("<TEMPLATEID>").append(this.templateid).append("</TEMPLATEID>");
        sb.append("<UPDATEUSERID>").append(this.updateuserid).append("</UPDATEUSERID>");
        sb.append("<UPDATETIME>").append(this.updatetime).append("</UPDATETIME>");
        return sb.toString();
    }
}