package com.syscom.safeaa.mybatis.model;

import com.syscom.safeaa.mybatis.vo.BaseModel;
import java.util.Date;

public class Syscomroleresourcedeny extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLERESOURCEDENY.ROLEID
     *
     * @mbg.generated
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLERESOURCEDENY.RESOURCEID
     *
     * @mbg.generated
     */
    private Integer resourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLERESOURCEDENY.UPDATEUSERID
     *
     * @mbg.generated
     */
    private Integer updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLERESOURCEDENY.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCOMROLERESOURCEDENY
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCEDENY
     *
     * @mbg.generated
     */
    public Syscomroleresourcedeny(Integer roleid, Integer resourceid, Integer updateuserid, Date updatetime) {
        this.roleid = roleid;
        this.resourceid = resourceid;
        this.updateuserid = updateuserid;
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCEDENY
     *
     * @mbg.generated
     */
    public Syscomroleresourcedeny() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLERESOURCEDENY.ROLEID
     *
     * @return the value of SYSCOMROLERESOURCEDENY.ROLEID
     *
     * @mbg.generated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLERESOURCEDENY.ROLEID
     *
     * @param roleid the value for SYSCOMROLERESOURCEDENY.ROLEID
     *
     * @mbg.generated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLERESOURCEDENY.RESOURCEID
     *
     * @return the value of SYSCOMROLERESOURCEDENY.RESOURCEID
     *
     * @mbg.generated
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLERESOURCEDENY.RESOURCEID
     *
     * @param resourceid the value for SYSCOMROLERESOURCEDENY.RESOURCEID
     *
     * @mbg.generated
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLERESOURCEDENY.UPDATEUSERID
     *
     * @return the value of SYSCOMROLERESOURCEDENY.UPDATEUSERID
     *
     * @mbg.generated
     */
    public Integer getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLERESOURCEDENY.UPDATEUSERID
     *
     * @param updateuserid the value for SYSCOMROLERESOURCEDENY.UPDATEUSERID
     *
     * @mbg.generated
     */
    public void setUpdateuserid(Integer updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMROLERESOURCEDENY.UPDATETIME
     *
     * @return the value of SYSCOMROLERESOURCEDENY.UPDATETIME
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMROLERESOURCEDENY.UPDATETIME
     *
     * @param updatetime the value for SYSCOMROLERESOURCEDENY.UPDATETIME
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCEDENY
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Syscomroleresourcedeny other = (Syscomroleresourcedeny) that;
        return (this.getRoleid() == null ? other.getRoleid() == null : this.getRoleid().equals(other.getRoleid()))
            && (this.getResourceid() == null ? other.getResourceid() == null : this.getResourceid().equals(other.getResourceid()))
            && (this.getUpdateuserid() == null ? other.getUpdateuserid() == null : this.getUpdateuserid().equals(other.getUpdateuserid()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCEDENY
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleid() == null) ? 0 : getRoleid().hashCode());
        result = prime * result + ((getResourceid() == null) ? 0 : getResourceid().hashCode());
        result = prime * result + ((getUpdateuserid() == null) ? 0 : getUpdateuserid().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCEDENY
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleid=").append(roleid);
        sb.append(", resourceid=").append(resourceid);
        sb.append(", updateuserid=").append(updateuserid);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCEDENY
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<ROLEID>").append(this.roleid).append("</ROLEID>");
        sb.append("<RESOURCEID>").append(this.resourceid).append("</RESOURCEID>");
        sb.append("<UPDATEUSERID>").append(this.updateuserid).append("</UPDATEUSERID>");
        sb.append("<UPDATETIME>").append(this.updatetime).append("</UPDATETIME>");
        return sb.toString();
    }
}