package com.syscom.safeaa.mybatis.model;

import com.syscom.safeaa.mybatis.vo.BaseModel;

public class Syscomtemplateculture extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMTEMPLATECULTURE.TEMPLATEID
     *
     * @mbg.generated
     */
    private Integer templateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMTEMPLATECULTURE.CULTURE
     *
     * @mbg.generated
     */
    private String culture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMTEMPLATECULTURE.TEMPLATENAME
     *
     * @mbg.generated
     */
    private String templatename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMTEMPLATECULTURE.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCOMTEMPLATECULTURE
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATECULTURE
     *
     * @mbg.generated
     */
    public Syscomtemplateculture(Integer templateid, String culture, String templatename, String remark) {
        this.templateid = templateid;
        this.culture = culture;
        this.templatename = templatename;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATECULTURE
     *
     * @mbg.generated
     */
    public Syscomtemplateculture() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMTEMPLATECULTURE.TEMPLATEID
     *
     * @return the value of SYSCOMTEMPLATECULTURE.TEMPLATEID
     *
     * @mbg.generated
     */
    public Integer getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMTEMPLATECULTURE.TEMPLATEID
     *
     * @param templateid the value for SYSCOMTEMPLATECULTURE.TEMPLATEID
     *
     * @mbg.generated
     */
    public void setTemplateid(Integer templateid) {
        this.templateid = templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMTEMPLATECULTURE.CULTURE
     *
     * @return the value of SYSCOMTEMPLATECULTURE.CULTURE
     *
     * @mbg.generated
     */
    public String getCulture() {
        return culture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMTEMPLATECULTURE.CULTURE
     *
     * @param culture the value for SYSCOMTEMPLATECULTURE.CULTURE
     *
     * @mbg.generated
     */
    public void setCulture(String culture) {
        this.culture = culture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMTEMPLATECULTURE.TEMPLATENAME
     *
     * @return the value of SYSCOMTEMPLATECULTURE.TEMPLATENAME
     *
     * @mbg.generated
     */
    public String getTemplatename() {
        return templatename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMTEMPLATECULTURE.TEMPLATENAME
     *
     * @param templatename the value for SYSCOMTEMPLATECULTURE.TEMPLATENAME
     *
     * @mbg.generated
     */
    public void setTemplatename(String templatename) {
        this.templatename = templatename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMTEMPLATECULTURE.REMARK
     *
     * @return the value of SYSCOMTEMPLATECULTURE.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMTEMPLATECULTURE.REMARK
     *
     * @param remark the value for SYSCOMTEMPLATECULTURE.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATECULTURE
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Syscomtemplateculture other = (Syscomtemplateculture) that;
        return (this.getTemplateid() == null ? other.getTemplateid() == null : this.getTemplateid().equals(other.getTemplateid()))
            && (this.getCulture() == null ? other.getCulture() == null : this.getCulture().equals(other.getCulture()))
            && (this.getTemplatename() == null ? other.getTemplatename() == null : this.getTemplatename().equals(other.getTemplatename()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATECULTURE
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTemplateid() == null) ? 0 : getTemplateid().hashCode());
        result = prime * result + ((getCulture() == null) ? 0 : getCulture().hashCode());
        result = prime * result + ((getTemplatename() == null) ? 0 : getTemplatename().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATECULTURE
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", templateid=").append(templateid);
        sb.append(", culture=").append(culture);
        sb.append(", templatename=").append(templatename);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATECULTURE
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<TEMPLATEID>").append(this.templateid).append("</TEMPLATEID>");
        sb.append("<CULTURE>").append(this.culture).append("</CULTURE>");
        sb.append("<TEMPLATENAME>").append(this.templatename).append("</TEMPLATENAME>");
        sb.append("<REMARK>").append(this.remark).append("</REMARK>");
        return sb.toString();
    }
}