package com.syscom.safeaa.mybatis.model;

import com.syscom.safeaa.mybatis.vo.BaseModel;
import java.util.Date;

public class Syscomresource extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMRESOURCE.RESOURCEID
     *
     * @mbg.generated
     */
    private Integer resourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMRESOURCE.RESOURCENO
     *
     * @mbg.generated
     */
    private String resourceno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMRESOURCE.SAFEDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    private String safedefinefunctionlist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMRESOURCE.USERDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    private String userdefinefunctionlist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMRESOURCE.RESOURCEURL
     *
     * @mbg.generated
     */
    private String resourceurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMRESOURCE.EFFECTDATE
     *
     * @mbg.generated
     */
    private Date effectdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMRESOURCE.EXPIREDDATE
     *
     * @mbg.generated
     */
    private Date expireddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMRESOURCE.UPDATEUSERID
     *
     * @mbg.generated
     */
    private Integer updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMRESOURCE.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMRESOURCE.APPLICATIONID
     *
     * @mbg.generated
     */
    private String applicationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMRESOURCE.INCLUDEPERSONALDATA
     *
     * @mbg.generated
     */
    private Short includepersonaldata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMRESOURCE.APDEFINE1
     *
     * @mbg.generated
     */
    private String apdefine1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMRESOURCE.APDEFINE2
     *
     * @mbg.generated
     */
    private String apdefine2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCOMRESOURCE
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCE
     *
     * @mbg.generated
     */
    public Syscomresource(Integer resourceid, String resourceno, String safedefinefunctionlist, String userdefinefunctionlist, String resourceurl, Date effectdate, Date expireddate, Integer updateuserid, Date updatetime, String applicationid, Short includepersonaldata, String apdefine1, String apdefine2) {
        this.resourceid = resourceid;
        this.resourceno = resourceno;
        this.safedefinefunctionlist = safedefinefunctionlist;
        this.userdefinefunctionlist = userdefinefunctionlist;
        this.resourceurl = resourceurl;
        this.effectdate = effectdate;
        this.expireddate = expireddate;
        this.updateuserid = updateuserid;
        this.updatetime = updatetime;
        this.applicationid = applicationid;
        this.includepersonaldata = includepersonaldata;
        this.apdefine1 = apdefine1;
        this.apdefine2 = apdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCE
     *
     * @mbg.generated
     */
    public Syscomresource() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMRESOURCE.RESOURCEID
     *
     * @return the value of SYSCOMRESOURCE.RESOURCEID
     *
     * @mbg.generated
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMRESOURCE.RESOURCEID
     *
     * @param resourceid the value for SYSCOMRESOURCE.RESOURCEID
     *
     * @mbg.generated
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMRESOURCE.RESOURCENO
     *
     * @return the value of SYSCOMRESOURCE.RESOURCENO
     *
     * @mbg.generated
     */
    public String getResourceno() {
        return resourceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMRESOURCE.RESOURCENO
     *
     * @param resourceno the value for SYSCOMRESOURCE.RESOURCENO
     *
     * @mbg.generated
     */
    public void setResourceno(String resourceno) {
        this.resourceno = resourceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMRESOURCE.SAFEDEFINEFUNCTIONLIST
     *
     * @return the value of SYSCOMRESOURCE.SAFEDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    public String getSafedefinefunctionlist() {
        return safedefinefunctionlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMRESOURCE.SAFEDEFINEFUNCTIONLIST
     *
     * @param safedefinefunctionlist the value for SYSCOMRESOURCE.SAFEDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    public void setSafedefinefunctionlist(String safedefinefunctionlist) {
        this.safedefinefunctionlist = safedefinefunctionlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMRESOURCE.USERDEFINEFUNCTIONLIST
     *
     * @return the value of SYSCOMRESOURCE.USERDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    public String getUserdefinefunctionlist() {
        return userdefinefunctionlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMRESOURCE.USERDEFINEFUNCTIONLIST
     *
     * @param userdefinefunctionlist the value for SYSCOMRESOURCE.USERDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    public void setUserdefinefunctionlist(String userdefinefunctionlist) {
        this.userdefinefunctionlist = userdefinefunctionlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMRESOURCE.RESOURCEURL
     *
     * @return the value of SYSCOMRESOURCE.RESOURCEURL
     *
     * @mbg.generated
     */
    public String getResourceurl() {
        return resourceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMRESOURCE.RESOURCEURL
     *
     * @param resourceurl the value for SYSCOMRESOURCE.RESOURCEURL
     *
     * @mbg.generated
     */
    public void setResourceurl(String resourceurl) {
        this.resourceurl = resourceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMRESOURCE.EFFECTDATE
     *
     * @return the value of SYSCOMRESOURCE.EFFECTDATE
     *
     * @mbg.generated
     */
    public Date getEffectdate() {
        return effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMRESOURCE.EFFECTDATE
     *
     * @param effectdate the value for SYSCOMRESOURCE.EFFECTDATE
     *
     * @mbg.generated
     */
    public void setEffectdate(Date effectdate) {
        this.effectdate = effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMRESOURCE.EXPIREDDATE
     *
     * @return the value of SYSCOMRESOURCE.EXPIREDDATE
     *
     * @mbg.generated
     */
    public Date getExpireddate() {
        return expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMRESOURCE.EXPIREDDATE
     *
     * @param expireddate the value for SYSCOMRESOURCE.EXPIREDDATE
     *
     * @mbg.generated
     */
    public void setExpireddate(Date expireddate) {
        this.expireddate = expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMRESOURCE.UPDATEUSERID
     *
     * @return the value of SYSCOMRESOURCE.UPDATEUSERID
     *
     * @mbg.generated
     */
    public Integer getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMRESOURCE.UPDATEUSERID
     *
     * @param updateuserid the value for SYSCOMRESOURCE.UPDATEUSERID
     *
     * @mbg.generated
     */
    public void setUpdateuserid(Integer updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMRESOURCE.UPDATETIME
     *
     * @return the value of SYSCOMRESOURCE.UPDATETIME
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMRESOURCE.UPDATETIME
     *
     * @param updatetime the value for SYSCOMRESOURCE.UPDATETIME
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMRESOURCE.APPLICATIONID
     *
     * @return the value of SYSCOMRESOURCE.APPLICATIONID
     *
     * @mbg.generated
     */
    public String getApplicationid() {
        return applicationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMRESOURCE.APPLICATIONID
     *
     * @param applicationid the value for SYSCOMRESOURCE.APPLICATIONID
     *
     * @mbg.generated
     */
    public void setApplicationid(String applicationid) {
        this.applicationid = applicationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMRESOURCE.INCLUDEPERSONALDATA
     *
     * @return the value of SYSCOMRESOURCE.INCLUDEPERSONALDATA
     *
     * @mbg.generated
     */
    public Short getIncludepersonaldata() {
        return includepersonaldata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMRESOURCE.INCLUDEPERSONALDATA
     *
     * @param includepersonaldata the value for SYSCOMRESOURCE.INCLUDEPERSONALDATA
     *
     * @mbg.generated
     */
    public void setIncludepersonaldata(Short includepersonaldata) {
        this.includepersonaldata = includepersonaldata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMRESOURCE.APDEFINE1
     *
     * @return the value of SYSCOMRESOURCE.APDEFINE1
     *
     * @mbg.generated
     */
    public String getApdefine1() {
        return apdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMRESOURCE.APDEFINE1
     *
     * @param apdefine1 the value for SYSCOMRESOURCE.APDEFINE1
     *
     * @mbg.generated
     */
    public void setApdefine1(String apdefine1) {
        this.apdefine1 = apdefine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMRESOURCE.APDEFINE2
     *
     * @return the value of SYSCOMRESOURCE.APDEFINE2
     *
     * @mbg.generated
     */
    public String getApdefine2() {
        return apdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMRESOURCE.APDEFINE2
     *
     * @param apdefine2 the value for SYSCOMRESOURCE.APDEFINE2
     *
     * @mbg.generated
     */
    public void setApdefine2(String apdefine2) {
        this.apdefine2 = apdefine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCE
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Syscomresource other = (Syscomresource) that;
        return (this.getResourceid() == null ? other.getResourceid() == null : this.getResourceid().equals(other.getResourceid()))
            && (this.getResourceno() == null ? other.getResourceno() == null : this.getResourceno().equals(other.getResourceno()))
            && (this.getSafedefinefunctionlist() == null ? other.getSafedefinefunctionlist() == null : this.getSafedefinefunctionlist().equals(other.getSafedefinefunctionlist()))
            && (this.getUserdefinefunctionlist() == null ? other.getUserdefinefunctionlist() == null : this.getUserdefinefunctionlist().equals(other.getUserdefinefunctionlist()))
            && (this.getResourceurl() == null ? other.getResourceurl() == null : this.getResourceurl().equals(other.getResourceurl()))
            && (this.getEffectdate() == null ? other.getEffectdate() == null : this.getEffectdate().equals(other.getEffectdate()))
            && (this.getExpireddate() == null ? other.getExpireddate() == null : this.getExpireddate().equals(other.getExpireddate()))
            && (this.getUpdateuserid() == null ? other.getUpdateuserid() == null : this.getUpdateuserid().equals(other.getUpdateuserid()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()))
            && (this.getApplicationid() == null ? other.getApplicationid() == null : this.getApplicationid().equals(other.getApplicationid()))
            && (this.getIncludepersonaldata() == null ? other.getIncludepersonaldata() == null : this.getIncludepersonaldata().equals(other.getIncludepersonaldata()))
            && (this.getApdefine1() == null ? other.getApdefine1() == null : this.getApdefine1().equals(other.getApdefine1()))
            && (this.getApdefine2() == null ? other.getApdefine2() == null : this.getApdefine2().equals(other.getApdefine2()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCE
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getResourceid() == null) ? 0 : getResourceid().hashCode());
        result = prime * result + ((getResourceno() == null) ? 0 : getResourceno().hashCode());
        result = prime * result + ((getSafedefinefunctionlist() == null) ? 0 : getSafedefinefunctionlist().hashCode());
        result = prime * result + ((getUserdefinefunctionlist() == null) ? 0 : getUserdefinefunctionlist().hashCode());
        result = prime * result + ((getResourceurl() == null) ? 0 : getResourceurl().hashCode());
        result = prime * result + ((getEffectdate() == null) ? 0 : getEffectdate().hashCode());
        result = prime * result + ((getExpireddate() == null) ? 0 : getExpireddate().hashCode());
        result = prime * result + ((getUpdateuserid() == null) ? 0 : getUpdateuserid().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        result = prime * result + ((getApplicationid() == null) ? 0 : getApplicationid().hashCode());
        result = prime * result + ((getIncludepersonaldata() == null) ? 0 : getIncludepersonaldata().hashCode());
        result = prime * result + ((getApdefine1() == null) ? 0 : getApdefine1().hashCode());
        result = prime * result + ((getApdefine2() == null) ? 0 : getApdefine2().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCE
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", resourceid=").append(resourceid);
        sb.append(", resourceno=").append(resourceno);
        sb.append(", safedefinefunctionlist=").append(safedefinefunctionlist);
        sb.append(", userdefinefunctionlist=").append(userdefinefunctionlist);
        sb.append(", resourceurl=").append(resourceurl);
        sb.append(", effectdate=").append(effectdate);
        sb.append(", expireddate=").append(expireddate);
        sb.append(", updateuserid=").append(updateuserid);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", applicationid=").append(applicationid);
        sb.append(", includepersonaldata=").append(includepersonaldata);
        sb.append(", apdefine1=").append(apdefine1);
        sb.append(", apdefine2=").append(apdefine2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCE
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<RESOURCEID>").append(this.resourceid).append("</RESOURCEID>");
        sb.append("<RESOURCENO>").append(this.resourceno).append("</RESOURCENO>");
        sb.append("<SAFEDEFINEFUNCTIONLIST>").append(this.safedefinefunctionlist).append("</SAFEDEFINEFUNCTIONLIST>");
        sb.append("<USERDEFINEFUNCTIONLIST>").append(this.userdefinefunctionlist).append("</USERDEFINEFUNCTIONLIST>");
        sb.append("<RESOURCEURL>").append(this.resourceurl).append("</RESOURCEURL>");
        sb.append("<EFFECTDATE>").append(this.effectdate).append("</EFFECTDATE>");
        sb.append("<EXPIREDDATE>").append(this.expireddate).append("</EXPIREDDATE>");
        sb.append("<UPDATEUSERID>").append(this.updateuserid).append("</UPDATEUSERID>");
        sb.append("<UPDATETIME>").append(this.updatetime).append("</UPDATETIME>");
        sb.append("<APPLICATIONID>").append(this.applicationid).append("</APPLICATIONID>");
        sb.append("<INCLUDEPERSONALDATA>").append(this.includepersonaldata).append("</INCLUDEPERSONALDATA>");
        sb.append("<APDEFINE1>").append(this.apdefine1).append("</APDEFINE1>");
        sb.append("<APDEFINE2>").append(this.apdefine2).append("</APDEFINE2>");
        return sb.toString();
    }
}