package com.syscom.safeaa.mybatis.model;

import com.syscom.safeaa.mybatis.vo.BaseModel;
import java.util.Date;

public class Syscombasemessage extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMBASEMESSAGE.BASEMESSAGENO
     *
     * @mbg.generated
     */
    private String basemessageno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMBASEMESSAGE.ERRORLEVEL
     *
     * @mbg.generated
     */
    private String errorlevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMBASEMESSAGE.MONITOR
     *
     * @mbg.generated
     */
    private Short monitor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMBASEMESSAGE.ISPROTECTED
     *
     * @mbg.generated
     */
    private Short isprotected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMBASEMESSAGE.UPDATEUSERID
     *
     * @mbg.generated
     */
    private Integer updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMBASEMESSAGE.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCOMBASEMESSAGE
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMBASEMESSAGE
     *
     * @mbg.generated
     */
    public Syscombasemessage(String basemessageno, String errorlevel, Short monitor, Short isprotected, Integer updateuserid, Date updatetime) {
        this.basemessageno = basemessageno;
        this.errorlevel = errorlevel;
        this.monitor = monitor;
        this.isprotected = isprotected;
        this.updateuserid = updateuserid;
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMBASEMESSAGE
     *
     * @mbg.generated
     */
    public Syscombasemessage() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMBASEMESSAGE.BASEMESSAGENO
     *
     * @return the value of SYSCOMBASEMESSAGE.BASEMESSAGENO
     *
     * @mbg.generated
     */
    public String getBasemessageno() {
        return basemessageno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMBASEMESSAGE.BASEMESSAGENO
     *
     * @param basemessageno the value for SYSCOMBASEMESSAGE.BASEMESSAGENO
     *
     * @mbg.generated
     */
    public void setBasemessageno(String basemessageno) {
        this.basemessageno = basemessageno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMBASEMESSAGE.ERRORLEVEL
     *
     * @return the value of SYSCOMBASEMESSAGE.ERRORLEVEL
     *
     * @mbg.generated
     */
    public String getErrorlevel() {
        return errorlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMBASEMESSAGE.ERRORLEVEL
     *
     * @param errorlevel the value for SYSCOMBASEMESSAGE.ERRORLEVEL
     *
     * @mbg.generated
     */
    public void setErrorlevel(String errorlevel) {
        this.errorlevel = errorlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMBASEMESSAGE.MONITOR
     *
     * @return the value of SYSCOMBASEMESSAGE.MONITOR
     *
     * @mbg.generated
     */
    public Short getMonitor() {
        return monitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMBASEMESSAGE.MONITOR
     *
     * @param monitor the value for SYSCOMBASEMESSAGE.MONITOR
     *
     * @mbg.generated
     */
    public void setMonitor(Short monitor) {
        this.monitor = monitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMBASEMESSAGE.ISPROTECTED
     *
     * @return the value of SYSCOMBASEMESSAGE.ISPROTECTED
     *
     * @mbg.generated
     */
    public Short getIsprotected() {
        return isprotected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMBASEMESSAGE.ISPROTECTED
     *
     * @param isprotected the value for SYSCOMBASEMESSAGE.ISPROTECTED
     *
     * @mbg.generated
     */
    public void setIsprotected(Short isprotected) {
        this.isprotected = isprotected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMBASEMESSAGE.UPDATEUSERID
     *
     * @return the value of SYSCOMBASEMESSAGE.UPDATEUSERID
     *
     * @mbg.generated
     */
    public Integer getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMBASEMESSAGE.UPDATEUSERID
     *
     * @param updateuserid the value for SYSCOMBASEMESSAGE.UPDATEUSERID
     *
     * @mbg.generated
     */
    public void setUpdateuserid(Integer updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMBASEMESSAGE.UPDATETIME
     *
     * @return the value of SYSCOMBASEMESSAGE.UPDATETIME
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMBASEMESSAGE.UPDATETIME
     *
     * @param updatetime the value for SYSCOMBASEMESSAGE.UPDATETIME
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMBASEMESSAGE
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Syscombasemessage other = (Syscombasemessage) that;
        return (this.getBasemessageno() == null ? other.getBasemessageno() == null : this.getBasemessageno().equals(other.getBasemessageno()))
            && (this.getErrorlevel() == null ? other.getErrorlevel() == null : this.getErrorlevel().equals(other.getErrorlevel()))
            && (this.getMonitor() == null ? other.getMonitor() == null : this.getMonitor().equals(other.getMonitor()))
            && (this.getIsprotected() == null ? other.getIsprotected() == null : this.getIsprotected().equals(other.getIsprotected()))
            && (this.getUpdateuserid() == null ? other.getUpdateuserid() == null : this.getUpdateuserid().equals(other.getUpdateuserid()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMBASEMESSAGE
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBasemessageno() == null) ? 0 : getBasemessageno().hashCode());
        result = prime * result + ((getErrorlevel() == null) ? 0 : getErrorlevel().hashCode());
        result = prime * result + ((getMonitor() == null) ? 0 : getMonitor().hashCode());
        result = prime * result + ((getIsprotected() == null) ? 0 : getIsprotected().hashCode());
        result = prime * result + ((getUpdateuserid() == null) ? 0 : getUpdateuserid().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMBASEMESSAGE
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", basemessageno=").append(basemessageno);
        sb.append(", errorlevel=").append(errorlevel);
        sb.append(", monitor=").append(monitor);
        sb.append(", isprotected=").append(isprotected);
        sb.append(", updateuserid=").append(updateuserid);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMBASEMESSAGE
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<BASEMESSAGENO>").append(this.basemessageno).append("</BASEMESSAGENO>");
        sb.append("<ERRORLEVEL>").append(this.errorlevel).append("</ERRORLEVEL>");
        sb.append("<MONITOR>").append(this.monitor).append("</MONITOR>");
        sb.append("<ISPROTECTED>").append(this.isprotected).append("</ISPROTECTED>");
        sb.append("<UPDATEUSERID>").append(this.updateuserid).append("</UPDATEUSERID>");
        sb.append("<UPDATETIME>").append(this.updatetime).append("</UPDATETIME>");
        return sb.toString();
    }
}