-- ----------------------------
-- Table structure for DESKEY
-- ----------------------------
DROP TABLE "DESKEY";
CREATE TABLE "DESKEY" (
  "BANKID" VARCHAR(8) NOT NULL,
  "KEYTYPE" CHARACTER(2) NOT NULL,
  "KEYKIND" VARCHAR(8) NOT NULL,
  "KEYFN" VARCHAR(8) NOT NULL,
  "CURKEY" VARCHAR(48),
  "PENDINGKEY" VARCHAR(48),
  "BEGINDATE" VARCHAR(8),
  "UPDATEDATE" TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  "UPDATEUSER" INTEGER,
  "KEYDESC" VARCHAR(40)
);
COMMENT ON COLUMN "DESKEY"."BANKID" IS '行庫代碼';
COMMENT ON COLUMN "DESKEY"."KEYTYPE" IS 'KEY種類';
COMMENT ON COLUMN "DESKEY"."KEYKIND" IS 'KEY類別';
COMMENT ON COLUMN "DESKEY"."KEYFN" IS 'KEY功能';
COMMENT ON COLUMN "DESKEY"."CURKEY" IS '目前使用KEY值';
COMMENT ON COLUMN "DESKEY"."PENDINGKEY" IS 'PENDING KEY';
COMMENT ON COLUMN "DESKEY"."BEGINDATE" IS 'KEY的生效開始日期';
COMMENT ON COLUMN "DESKEY"."UPDATEDATE" IS '更新時間';
COMMENT ON COLUMN "DESKEY"."UPDATEUSER" IS '更新使用者';
COMMENT ON COLUMN "DESKEY"."KEYDESC" IS 'KEY 說明';

-- ----------------------------
-- Primary Key structure for table DESKEY
-- ----------------------------
ALTER TABLE "DESKEY" ADD CONSTRAINT "PK_DESKEY" PRIMARY KEY ("BANKID", "KEYTYPE", "KEYKIND", "KEYFN");