ALTER TABLE DBO.DESLOG1 ALTER COLUMN DESLOG_PROGRAMNAME SET DATA TYPE VARCHAR(100);
ALTER TABLE DBO.DESLOG2 ALTER COLUMN DESLOG_PROGRAMNAME SET DATA TYPE VARCHAR(100);
ALTER TABLE DBO.DESLOG3 ALTER COLUMN DESLOG_PROGRAMNAME SET DATA TYPE VARCHAR(100);
ALTER TABLE DBO.DESLOG4 ALTER COLUMN DESLOG_PROGRAMNAME SET DATA TYPE VARCHAR(100);
ALTER TABLE DBO.DESLOG5 ALTER COLUMN DESLOG_PROGRAMNAME SET DATA TYPE VARCHAR(100);
ALTER TABLE DBO.DESLOG6 ALTER COLUMN DESLOG_PROGRAMNAME SET DATA TYPE VARCHAR(100);
ALTER TABLE DBO.DESLOG7 ALTER COLUMN DESLOG_PROGRAMNAME SET DATA TYPE VARCHAR(100);

ALTER TABLE DBO.DESLOG1 ADD COLUMN TXRQUID VARCHAR(50);
ALTER TABLE DBO.DESLOG1 ADD COLUMN HOSTNAME VARCHAR(20);

ALTER TABLE DBO.DESLOG2 ADD COLUMN TXRQUID VARCHAR(50);
ALTER TABLE DBO.DESLOG2 ADD COLUMN HOSTNAME VARCHAR(20);

ALTER TABLE DBO.DESLOG3 ADD COLUMN TXRQUID VARCHAR(50);
ALTER TABLE DBO.DESLOG3 ADD COLUMN HOSTNAME VARCHAR(20);

ALTER TABLE DBO.DESLOG4 ADD COLUMN TXRQUID VARCHAR(50);
ALTER TABLE DBO.DESLOG4 ADD COLUMN HOSTNAME VARCHAR(20);

ALTER TABLE DBO.DESLOG5 ADD COLUMN TXRQUID VARCHAR(50);
ALTER TABLE DBO.DESLOG5 ADD COLUMN HOSTNAME VARCHAR(20);

ALTER TABLE DBO.DESLOG6 ADD COLUMN TXRQUID VARCHAR(50);
ALTER TABLE DBO.DESLOG6 ADD COLUMN HOSTNAME VARCHAR(20);

ALTER TABLE DBO.DESLOG7 ADD COLUMN TXRQUID VARCHAR(50);
ALTER TABLE DBO.DESLOG7 ADD COLUMN HOSTNAME VARCHAR(20);

CALL SYSPROC.ADMIN_CMD('REORG TABLE DBO.DESLOG1');
CALL SYSPROC.ADMIN_CMD('REORG TABLE DBO.DESLOG2');
CALL SYSPROC.ADMIN_CMD('REORG TABLE DBO.DESLOG3');
CALL SYSPROC.ADMIN_CMD('REORG TABLE DBO.DESLOG4');
CALL SYSPROC.ADMIN_CMD('REORG TABLE DBO.DESLOG5');
CALL SYSPROC.ADMIN_CMD('REORG TABLE DBO.DESLOG6');
CALL SYSPROC.ADMIN_CMD('REORG TABLE DBO.DESLOG7');