DROP TABLE "FEPLOG1";
CREATE TABLE "FEPLOG1" (
	"LOGNO" BIGINT NOT NULL, 
	"LOGDATE" TIMESTAMP, 
	"THREADID" VARCHAR(50), 
	"EJ" DECIMAL(10,0), 
	"CHANNEL" VARCHAR(7), 
	"MESSAGEID" VARCHAR(30), 
	"MESSAGEFLOW" VARCHAR(25), 
	"PROGRAMFLOW" VARCHAR(15), 
	"PROGRAMNAME" VARCHAR(100), 
	"STAN" VARCHAR(8), 
	"ATMSEQ" VARCHAR(8), 
	"ATMNO" VARCHAR(8), 
	"TRINBANK" VARCHAR(6), 
	"TRINACTNO" VARCHAR(16), 
	"TROUTBANK" VARCHAR(6), 
	"TROUTACTNO" VARCHAR(16), 
	"TXDATE" VARCHAR(10), 
	"TXMESSAGE" CLOB, 
	"REMARK" CLOB, 
	"BKNO" CHAR(3), 
	"STEPS" DECIMAL(10,0)
	);
ALTER TABLE "FEPLOG1" ADD CONSTRAINT "PK_FEPLOG1" PRIMARY KEY ("LOGNO");

DROP SEQUENCE "FEPLOG1_LOGNO_SEQ";
CREATE SEQUENCE "FEPLOG1_LOGNO_SEQ" AS BIGINT START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 20;

CREATE OR REPLACE TRIGGER "FEPLOG1_LOGNO_SEQ_TRIG"
  BEFORE INSERT ON "FEPLOG1"
  REFERENCING NEW AS "NEW"
  FOR EACH ROW
BEGIN
  DECLARE V_NEWVAL BIGINT DEFAULT 0;
  DECLARE V_INCVAL BIGINT DEFAULT 0;
  SELECT NEXTVAL FOR FEPLOG1_LOGNO_SEQ INTO V_NEWVAL FROM SYSIBM.SYSDUMMY1;
  -- If this is the first time this table have been inserted into (sequence == 1)
  IF V_NEWVAL = 1 THEN
    --get the max indentity value from the table
    SELECT NVL(MAX(LOGNO), 0) INTO V_NEWVAL FROM FEPLOG1;
    SET V_NEWVAL = V_NEWVAL + 1;
    --set the sequence to that value
    FETCH_LOOP :
    LOOP 
      IF V_INCVAL >= V_NEWVAL THEN
        LEAVE FETCH_LOOP;
      END IF;
      SELECT NEXTVAL FOR FEPLOG1_LOGNO_SEQ INTO V_INCVAL FROM SYSIBM.SYSDUMMY1;
     END LOOP FETCH_LOOP;
  END IF;
  -- assign the value from the sequence to emulate the identity column
  SET NEW.LOGNO = V_NEWVAL;
END;


DROP TABLE "FEPLOG2";
CREATE TABLE "FEPLOG2" (
	"LOGNO" BIGINT NOT NULL, 
	"LOGDATE" TIMESTAMP, 
	"THREADID" VARCHAR(50), 
	"EJ" DECIMAL(10,0), 
	"CHANNEL" VARCHAR(7), 
	"MESSAGEID" VARCHAR(30), 
	"MESSAGEFLOW" VARCHAR(25), 
	"PROGRAMFLOW" VARCHAR(15), 
	"PROGRAMNAME" VARCHAR(100), 
	"STAN" VARCHAR(8), 
	"ATMSEQ" VARCHAR(8), 
	"ATMNO" VARCHAR(8), 
	"TRINBANK" VARCHAR(6), 
	"TRINACTNO" VARCHAR(16), 
	"TROUTBANK" VARCHAR(6), 
	"TROUTACTNO" VARCHAR(16), 
	"TXDATE" VARCHAR(10), 
	"TXMESSAGE" CLOB, 
	"REMARK" CLOB, 
	"BKNO" CHAR(3), 
	"STEPS" DECIMAL(10,0)
	);
ALTER TABLE "FEPLOG2" ADD CONSTRAINT "PK_FEPLOG2" PRIMARY KEY ("LOGNO");

DROP SEQUENCE "FEPLOG2_LOGNO_SEQ";
CREATE SEQUENCE "FEPLOG2_LOGNO_SEQ" AS BIGINT START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 20;

CREATE OR REPLACE TRIGGER "FEPLOG2_LOGNO_SEQ_TRIG"
  BEFORE INSERT ON "FEPLOG2"
  REFERENCING NEW AS "NEW"
  FOR EACH ROW
BEGIN
  DECLARE V_NEWVAL BIGINT DEFAULT 0;
  DECLARE V_INCVAL BIGINT DEFAULT 0;
  SELECT NEXTVAL FOR FEPLOG2_LOGNO_SEQ INTO V_NEWVAL FROM SYSIBM.SYSDUMMY1;
  -- If this is the first time this table have been inserted into (sequence == 1)
  IF V_NEWVAL = 1 THEN
    --get the max indentity value from the table
    SELECT NVL(MAX(LOGNO), 0) INTO V_NEWVAL FROM FEPLOG2;
    SET V_NEWVAL = V_NEWVAL + 1;
    --set the sequence to that value
    FETCH_LOOP :
    LOOP 
      IF V_INCVAL >= V_NEWVAL THEN
        LEAVE FETCH_LOOP;
      END IF;
      SELECT NEXTVAL FOR FEPLOG2_LOGNO_SEQ INTO V_INCVAL FROM SYSIBM.SYSDUMMY1;
     END LOOP FETCH_LOOP;
  END IF;
  -- assign the value from the sequence to emulate the identity column
  SET NEW.LOGNO = V_NEWVAL;
END;


DROP TABLE "FEPLOG3";
CREATE TABLE "FEPLOG3" (
	"LOGNO" BIGINT NOT NULL, 
	"LOGDATE" TIMESTAMP, 
	"THREADID" VARCHAR(50), 
	"EJ" DECIMAL(10,0), 
	"CHANNEL" VARCHAR(7), 
	"MESSAGEID" VARCHAR(30), 
	"MESSAGEFLOW" VARCHAR(25), 
	"PROGRAMFLOW" VARCHAR(15), 
	"PROGRAMNAME" VARCHAR(100), 
	"STAN" VARCHAR(8), 
	"ATMSEQ" VARCHAR(8), 
	"ATMNO" VARCHAR(8), 
	"TRINBANK" VARCHAR(6), 
	"TRINACTNO" VARCHAR(16), 
	"TROUTBANK" VARCHAR(6), 
	"TROUTACTNO" VARCHAR(16), 
	"TXDATE" VARCHAR(10), 
	"TXMESSAGE" CLOB, 
	"REMARK" CLOB, 
	"BKNO" CHAR(3), 
	"STEPS" DECIMAL(10,0)
	);
ALTER TABLE "FEPLOG3" ADD CONSTRAINT "PK_FEPLOG3" PRIMARY KEY ("LOGNO");

DROP SEQUENCE "FEPLOG3_LOGNO_SEQ";
CREATE SEQUENCE "FEPLOG3_LOGNO_SEQ" AS BIGINT START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 20;

CREATE OR REPLACE TRIGGER "FEPLOG3_LOGNO_SEQ_TRIG"
  BEFORE INSERT ON "FEPLOG3"
  REFERENCING NEW AS "NEW"
  FOR EACH ROW
BEGIN
  DECLARE V_NEWVAL BIGINT DEFAULT 0;
  DECLARE V_INCVAL BIGINT DEFAULT 0;
  SELECT NEXTVAL FOR FEPLOG3_LOGNO_SEQ INTO V_NEWVAL FROM SYSIBM.SYSDUMMY1;
  -- If this is the first time this table have been inserted into (sequence == 1)
  IF V_NEWVAL = 1 THEN
    --get the max indentity value from the table
    SELECT NVL(MAX(LOGNO), 0) INTO V_NEWVAL FROM FEPLOG3;
    SET V_NEWVAL = V_NEWVAL + 1;
    --set the sequence to that value
    FETCH_LOOP :
    LOOP 
      IF V_INCVAL >= V_NEWVAL THEN
        LEAVE FETCH_LOOP;
      END IF;
      SELECT NEXTVAL FOR FEPLOG3_LOGNO_SEQ INTO V_INCVAL FROM SYSIBM.SYSDUMMY1;
     END LOOP FETCH_LOOP;
  END IF;
  -- assign the value from the sequence to emulate the identity column
  SET NEW.LOGNO = V_NEWVAL;
END;


DROP TABLE "FEPLOG4";
CREATE TABLE "FEPLOG4" (
	"LOGNO" BIGINT NOT NULL, 
	"LOGDATE" TIMESTAMP, 
	"THREADID" VARCHAR(50), 
	"EJ" DECIMAL(10,0), 
	"CHANNEL" VARCHAR(7), 
	"MESSAGEID" VARCHAR(30), 
	"MESSAGEFLOW" VARCHAR(25), 
	"PROGRAMFLOW" VARCHAR(15), 
	"PROGRAMNAME" VARCHAR(100), 
	"STAN" VARCHAR(8), 
	"ATMSEQ" VARCHAR(8), 
	"ATMNO" VARCHAR(8), 
	"TRINBANK" VARCHAR(6), 
	"TRINACTNO" VARCHAR(16), 
	"TROUTBANK" VARCHAR(6), 
	"TROUTACTNO" VARCHAR(16), 
	"TXDATE" VARCHAR(10), 
	"TXMESSAGE" CLOB, 
	"REMARK" CLOB, 
	"BKNO" CHAR(3), 
	"STEPS" DECIMAL(10,0)
	);
ALTER TABLE "FEPLOG4" ADD CONSTRAINT "PK_FEPLOG4" PRIMARY KEY ("LOGNO");

DROP SEQUENCE "FEPLOG4_LOGNO_SEQ";
CREATE SEQUENCE "FEPLOG4_LOGNO_SEQ" AS BIGINT START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 20;

CREATE OR REPLACE TRIGGER "FEPLOG4_LOGNO_SEQ_TRIG"
  BEFORE INSERT ON "FEPLOG4"
  REFERENCING NEW AS "NEW"
  FOR EACH ROW
BEGIN
  DECLARE V_NEWVAL BIGINT DEFAULT 0;
  DECLARE V_INCVAL BIGINT DEFAULT 0;
  SELECT NEXTVAL FOR FEPLOG4_LOGNO_SEQ INTO V_NEWVAL FROM SYSIBM.SYSDUMMY1;
  -- If this is the first time this table have been inserted into (sequence == 1)
  IF V_NEWVAL = 1 THEN
    --get the max indentity value from the table
    SELECT NVL(MAX(LOGNO), 0) INTO V_NEWVAL FROM FEPLOG4;
    SET V_NEWVAL = V_NEWVAL + 1;
    --set the sequence to that value
    FETCH_LOOP :
    LOOP 
      IF V_INCVAL >= V_NEWVAL THEN
        LEAVE FETCH_LOOP;
      END IF;
      SELECT NEXTVAL FOR FEPLOG4_LOGNO_SEQ INTO V_INCVAL FROM SYSIBM.SYSDUMMY1;
     END LOOP FETCH_LOOP;
  END IF;
  -- assign the value from the sequence to emulate the identity column
  SET NEW.LOGNO = V_NEWVAL;
END;


DROP TABLE "FEPLOG5";
CREATE TABLE "FEPLOG5" (
	"LOGNO" BIGINT NOT NULL, 
	"LOGDATE" TIMESTAMP, 
	"THREADID" VARCHAR(50), 
	"EJ" DECIMAL(10,0), 
	"CHANNEL" VARCHAR(7), 
	"MESSAGEID" VARCHAR(30), 
	"MESSAGEFLOW" VARCHAR(25), 
	"PROGRAMFLOW" VARCHAR(15), 
	"PROGRAMNAME" VARCHAR(100), 
	"STAN" VARCHAR(8), 
	"ATMSEQ" VARCHAR(8), 
	"ATMNO" VARCHAR(8), 
	"TRINBANK" VARCHAR(6), 
	"TRINACTNO" VARCHAR(16), 
	"TROUTBANK" VARCHAR(6), 
	"TROUTACTNO" VARCHAR(16), 
	"TXDATE" VARCHAR(10), 
	"TXMESSAGE" CLOB, 
	"REMARK" CLOB, 
	"BKNO" CHAR(3), 
	"STEPS" DECIMAL(10,0)
	);
ALTER TABLE "FEPLOG5" ADD CONSTRAINT "PK_FEPLOG5" PRIMARY KEY ("LOGNO");

DROP SEQUENCE "FEPLOG5_LOGNO_SEQ";
CREATE SEQUENCE "FEPLOG5_LOGNO_SEQ" AS BIGINT START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 20;

CREATE OR REPLACE TRIGGER "FEPLOG5_LOGNO_SEQ_TRIG"
  BEFORE INSERT ON "FEPLOG5"
  REFERENCING NEW AS "NEW"
  FOR EACH ROW
BEGIN
  DECLARE V_NEWVAL BIGINT DEFAULT 0;
  DECLARE V_INCVAL BIGINT DEFAULT 0;
  SELECT NEXTVAL FOR FEPLOG5_LOGNO_SEQ INTO V_NEWVAL FROM SYSIBM.SYSDUMMY1;
  -- If this is the first time this table have been inserted into (sequence == 1)
  IF V_NEWVAL = 1 THEN
    --get the max indentity value from the table
    SELECT NVL(MAX(LOGNO), 0) INTO V_NEWVAL FROM FEPLOG5;
    SET V_NEWVAL = V_NEWVAL + 1;
    --set the sequence to that value
    FETCH_LOOP :
    LOOP 
      IF V_INCVAL >= V_NEWVAL THEN
        LEAVE FETCH_LOOP;
      END IF;
      SELECT NEXTVAL FOR FEPLOG5_LOGNO_SEQ INTO V_INCVAL FROM SYSIBM.SYSDUMMY1;
     END LOOP FETCH_LOOP;
  END IF;
  -- assign the value from the sequence to emulate the identity column
  SET NEW.LOGNO = V_NEWVAL;
END;


DROP TABLE "FEPLOG6";
CREATE TABLE "FEPLOG6" (
	"LOGNO" BIGINT NOT NULL, 
	"LOGDATE" TIMESTAMP, 
	"THREADID" VARCHAR(50), 
	"EJ" DECIMAL(10,0), 
	"CHANNEL" VARCHAR(7), 
	"MESSAGEID" VARCHAR(30), 
	"MESSAGEFLOW" VARCHAR(25), 
	"PROGRAMFLOW" VARCHAR(15), 
	"PROGRAMNAME" VARCHAR(100), 
	"STAN" VARCHAR(8), 
	"ATMSEQ" VARCHAR(8), 
	"ATMNO" VARCHAR(8), 
	"TRINBANK" VARCHAR(6), 
	"TRINACTNO" VARCHAR(16), 
	"TROUTBANK" VARCHAR(6), 
	"TROUTACTNO" VARCHAR(16), 
	"TXDATE" VARCHAR(10), 
	"TXMESSAGE" CLOB, 
	"REMARK" CLOB, 
	"BKNO" CHAR(3), 
	"STEPS" DECIMAL(10,0)
	);
ALTER TABLE "FEPLOG6" ADD CONSTRAINT "PK_FEPLOG6" PRIMARY KEY ("LOGNO");

DROP SEQUENCE "FEPLOG6_LOGNO_SEQ";
CREATE SEQUENCE "FEPLOG6_LOGNO_SEQ" AS BIGINT START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 20;

CREATE OR REPLACE TRIGGER "FEPLOG6_LOGNO_SEQ_TRIG"
  BEFORE INSERT ON "FEPLOG6"
  REFERENCING NEW AS "NEW"
  FOR EACH ROW
BEGIN
  DECLARE V_NEWVAL BIGINT DEFAULT 0;
  DECLARE V_INCVAL BIGINT DEFAULT 0;
  SELECT NEXTVAL FOR FEPLOG6_LOGNO_SEQ INTO V_NEWVAL FROM SYSIBM.SYSDUMMY1;
  -- If this is the first time this table have been inserted into (sequence == 1)
  IF V_NEWVAL = 1 THEN
    --get the max indentity value from the table
    SELECT NVL(MAX(LOGNO), 0) INTO V_NEWVAL FROM FEPLOG6;
    SET V_NEWVAL = V_NEWVAL + 1;
    --set the sequence to that value
    FETCH_LOOP :
    LOOP 
      IF V_INCVAL >= V_NEWVAL THEN
        LEAVE FETCH_LOOP;
      END IF;
      SELECT NEXTVAL FOR FEPLOG6_LOGNO_SEQ INTO V_INCVAL FROM SYSIBM.SYSDUMMY1;
     END LOOP FETCH_LOOP;
  END IF;
  -- assign the value from the sequence to emulate the identity column
  SET NEW.LOGNO = V_NEWVAL;
END;


DROP TABLE "FEPLOG7";
CREATE TABLE "FEPLOG7" (
	"LOGNO" BIGINT NOT NULL, 
	"LOGDATE" TIMESTAMP, 
	"THREADID" VARCHAR(50), 
	"EJ" DECIMAL(10,0), 
	"CHANNEL" VARCHAR(7), 
	"MESSAGEID" VARCHAR(30), 
	"MESSAGEFLOW" VARCHAR(25), 
	"PROGRAMFLOW" VARCHAR(15), 
	"PROGRAMNAME" VARCHAR(100), 
	"STAN" VARCHAR(8), 
	"ATMSEQ" VARCHAR(8), 
	"ATMNO" VARCHAR(8), 
	"TRINBANK" VARCHAR(6), 
	"TRINACTNO" VARCHAR(16), 
	"TROUTBANK" VARCHAR(6), 
	"TROUTACTNO" VARCHAR(16), 
	"TXDATE" VARCHAR(10), 
	"TXMESSAGE" CLOB, 
	"REMARK" CLOB, 
	"BKNO" CHAR(3), 
	"STEPS" DECIMAL(10,0)
	);
ALTER TABLE "FEPLOG7" ADD CONSTRAINT "PK_FEPLOG7" PRIMARY KEY ("LOGNO");

DROP SEQUENCE "FEPLOG7_LOGNO_SEQ";
CREATE SEQUENCE "FEPLOG7_LOGNO_SEQ" AS BIGINT START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 20;

CREATE OR REPLACE TRIGGER "FEPLOG7_LOGNO_SEQ_TRIG"
  BEFORE INSERT ON "FEPLOG7"
  REFERENCING NEW AS "NEW"
  FOR EACH ROW
BEGIN
  DECLARE V_NEWVAL BIGINT DEFAULT 0;
  DECLARE V_INCVAL BIGINT DEFAULT 0;
  SELECT NEXTVAL FOR FEPLOG7_LOGNO_SEQ INTO V_NEWVAL FROM SYSIBM.SYSDUMMY1;
  -- If this is the first time this table have been inserted into (sequence == 1)
  IF V_NEWVAL = 1 THEN
    --get the max indentity value from the table
    SELECT NVL(MAX(LOGNO), 0) INTO V_NEWVAL FROM FEPLOG7;
    SET V_NEWVAL = V_NEWVAL + 1;
    --set the sequence to that value
    FETCH_LOOP :
    LOOP 
      IF V_INCVAL >= V_NEWVAL THEN
        LEAVE FETCH_LOOP;
      END IF;
      SELECT NEXTVAL FOR FEPLOG7_LOGNO_SEQ INTO V_INCVAL FROM SYSIBM.SYSDUMMY1;
     END LOOP FETCH_LOOP;
  END IF;
  -- assign the value from the sequence to emulate the identity column
  SET NEW.LOGNO = V_NEWVAL;
END;


