ALTER TABLE EMS.FEPLOG1 ALTER COLUMN THREADID
 SET DATA TYPE  VARCHAR(50) ;
CALL SYSPROC.ADMIN_CMD('REORG TABLE EMS.FEPLOG1');

ALTER TABLE EMS.FEPLOG2 ALTER COLUMN THREADID
 SET DATA TYPE  VARCHAR(50) ;
CALL SYSPROC.ADMIN_CMD('REORG TABLE EMS.FEPLOG2');

ALTER TABLE EMS.FEPLOG3 ALTER COLUMN THREADID
 SET DATA TYPE  VARCHAR(50) ;
CALL SYSPROC.ADMIN_CMD('REORG TABLE EMS.FEPLOG3');

ALTER TABLE EMS.FEPLOG4 ALTER COLUMN THREADID
 SET DATA TYPE  VARCHAR(50) ;
CALL SYSPROC.ADMIN_CMD('REORG TABLE EMS.FEPLOG4');

ALTER TABLE EMS.FEPLOG5 ALTER COLUMN THREADID
 SET DATA TYPE  VARCHAR(50) ;
CALL SYSPROC.ADMIN_CMD('REORG TABLE EMS.FEPLOG5');

ALTER TABLE EMS.FEPLOG6 ALTER COLUMN THREADID
 SET DATA TYPE  VARCHAR(50) ;
CALL SYSPROC.ADMIN_CMD('REORG TABLE EMS.FEPLOG6');

ALTER TABLE EMS.FEPLOG7 ALTER COLUMN THREADID
 SET DATA TYPE  VARCHAR(50) ;
CALL SYSPROC.ADMIN_CMD('REORG TABLE EMS.FEPLOG7');

ALTER TABLE EMS.FEPLOG1 ADD COLUMN TXRQUID VARCHAR(50);
ALTER TABLE EMS.FEPLOG1 ADD COLUMN HOSTNAME VARCHAR(20);
CALL SYSPROC.ADMIN_CMD('REORG TABLE EMS.FEPLOG1');

ALTER TABLE EMS.FEPLOG2 ADD COLUMN TXRQUID VARCHAR(50);
ALTER TABLE EMS.FEPLOG2 ADD COLUMN HOSTNAME VARCHAR(20);
CALL SYSPROC.ADMIN_CMD('REORG TABLE EMS.FEPLOG2');

ALTER TABLE EMS.FEPLOG3 ADD COLUMN TXRQUID VARCHAR(50);
ALTER TABLE EMS.FEPLOG3 ADD COLUMN HOSTNAME VARCHAR(20);
CALL SYSPROC.ADMIN_CMD('REORG TABLE EMS.FEPLOG3');

ALTER TABLE EMS.FEPLOG4 ADD COLUMN TXRQUID VARCHAR(50);
ALTER TABLE EMS.FEPLOG4 ADD COLUMN HOSTNAME VARCHAR(20);
CALL SYSPROC.ADMIN_CMD('REORG TABLE EMS.FEPLOG4');

ALTER TABLE EMS.FEPLOG5 ADD COLUMN TXRQUID VARCHAR(50);
ALTER TABLE EMS.FEPLOG5 ADD COLUMN HOSTNAME VARCHAR(20);
CALL SYSPROC.ADMIN_CMD('REORG TABLE EMS.FEPLOG5');

ALTER TABLE EMS.FEPLOG6 ADD COLUMN TXRQUID VARCHAR(50);
ALTER TABLE EMS.FEPLOG6 ADD COLUMN HOSTNAME VARCHAR(20);
CALL SYSPROC.ADMIN_CMD('REORG TABLE EMS.FEPLOG6');

ALTER TABLE EMS.FEPLOG7 ADD COLUMN TXRQUID VARCHAR(50);
ALTER TABLE EMS.FEPLOG7 ADD COLUMN HOSTNAME VARCHAR(20);
CALL SYSPROC.ADMIN_CMD('REORG TABLE EMS.FEPLOG7');