ALTER TABLE "WEBAUTHLOG" ADD "LOGNO" BIGINT NOT NULL DEFAULT 0;

ALTER TABLE "WEBAUTHLOG" DROP CONSTRAINT "PK_WEBAUTHLOG";

ALTER TABLE "WEBAUTHLOG" ADD CONSTRAINT "PK_WEBAUTHLOG" PRIMARY KEY("LOGNO");

DROP SEQUENCE "WEBAUTHLOG_LOGNO_SEQ";
CREATE SEQUENCE "WEBAUTHLOG_LOGNO_SEQ" AS BIGINT START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 20;

CREATE OR REPLACE TRIGGER "WEBAUTHLOG_LOGNO_SEQ_TRIG"
  BEFORE INSERT ON "WEBAUTHLOG"
  REFERENCING NEW AS "NEW"
  FOR EACH ROW
BEGIN
  DECLARE V_NEWVAL BIGINT DEFAULT 0;
  DECLARE V_INCVAL BIGINT DEFAULT 0;
  SELECT NEXTVAL FOR WEBAUTHLOG_LOGNO_SEQ INTO V_NEWVAL FROM SYSIBM.SYSDUMMY1;
  -- If this is the first time this table have been inserted into (sequence == 1)
  IF V_NEWVAL = 1 THEN
    --get the max indentity value from the table
    SELECT NVL(MAX(LOGNO), 0) INTO V_NEWVAL FROM WEBAUTHLOG;
    SET V_NEWVAL = V_NEWVAL + 1;
    --set the sequence to that value
    FETCH_LOOP :
    LOOP 
      IF V_INCVAL >= V_NEWVAL THEN
        LEAVE FETCH_LOOP;
      END IF;
      SELECT NEXTVAL FOR WEBAUTHLOG_LOGNO_SEQ INTO V_INCVAL FROM SYSIBM.SYSDUMMY1;
     END LOOP FETCH_LOOP;
  END IF;
  -- assign the value from the sequence to emulate the identity column
  SET NEW.LOGNO = V_NEWVAL;
END;