package com.syscom.safeaa.mybatis.vo;

import java.io.Serializable;
import java.util.Date;

import com.syscom.safeaa.constant.CommonConstants;
import com.syscom.safeaa.mybatis.model.Syscomgroup;

public class SyscomgroupmembersAndGroupLevel implements Serializable {
	

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.GROUPID
     *
     * @mbg.generated
     */
    private Integer groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.CHILDID
     *
     * @mbg.generated
     */
    private Integer childid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.CHILDTYPE
     *
     * @mbg.generated
     */
    private String childtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.LOCATIONNO
     *
     * @mbg.generated
     */
    private Integer locationno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.EFFECTDATE
     *
     * @mbg.generated
     */
    private Date effectdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.EXPIREDDATE
     *
     * @mbg.generated
     */
    private Date expireddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.UPDATEUSERID
     *
     * @mbg.generated
     */
    private Integer updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.SAFEDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    private String safedefinefunctionlist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMGROUPMEMBERS.USERDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    private String userdefinefunctionlist;
    
    private Integer grouplevel;
    
    public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getChildname() {
		return childname;
	}

	public void setChildname(String childname) {
		this.childname = childname;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	private String remark;
    private String childname;
    
    private String url;
    private String childno;
    

	public String getChildno() {
		return childno;
	}

	public void setChildno(String childno) {
		this.childno = childno;
	}

	public Integer getGrouplevel() {
		return grouplevel;
	}

	public void setGrouplevel(Integer grouplevel) {
		this.grouplevel = grouplevel;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCOMGROUPMEMBERS
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPMEMBERS
     *
     * @mbg.generated
     */
    public SyscomgroupmembersAndGroupLevel(Integer groupid, Integer childid, String childtype, Integer locationno, Date effectdate, Date expireddate, Integer updateuserid, Date updatetime, String safedefinefunctionlist, String userdefinefunctionlist) {
        this.groupid = groupid;
        this.childid = childid;
        this.childtype = childtype;
        this.locationno = locationno;
        this.effectdate = effectdate;
        this.expireddate = expireddate;
        this.updateuserid = updateuserid;
        this.updatetime = updatetime;
        this.safedefinefunctionlist = safedefinefunctionlist;
        this.userdefinefunctionlist = userdefinefunctionlist;
    }
    
    public SyscomgroupmembersAndGroupLevel(Integer groupid, Integer childid, String childtype, Integer locationno, Integer grouplevel ) {
        this.groupid = groupid;
        this.childid = childid;
        this.childtype = childtype;
        this.locationno = locationno;
        this.grouplevel = grouplevel;
    }
    
    public SyscomgroupmembersAndGroupLevel(Syscomgroup group ) {
        this.groupid = group.getGroupid();
        this.childid = group.getGroupid();
        this.childno = group.getGroupno();
        this.childname = "";
        this.grouplevel = 0;
        this.childtype =  CommonConstants.ChildTypeGroup;
        this.locationno = group.getLocationno();
        this.url = "";
    }    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPMEMBERS
     *
     * @mbg.generated
     */
    public SyscomgroupmembersAndGroupLevel() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.GROUPID
     *
     * @return the value of SYSCOMGROUPMEMBERS.GROUPID
     *
     * @mbg.generated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.GROUPID
     *
     * @param groupid the value for SYSCOMGROUPMEMBERS.GROUPID
     *
     * @mbg.generated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.CHILDID
     *
     * @return the value of SYSCOMGROUPMEMBERS.CHILDID
     *
     * @mbg.generated
     */
    public Integer getChildid() {
        return childid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.CHILDID
     *
     * @param childid the value for SYSCOMGROUPMEMBERS.CHILDID
     *
     * @mbg.generated
     */
    public void setChildid(Integer childid) {
        this.childid = childid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.CHILDTYPE
     *
     * @return the value of SYSCOMGROUPMEMBERS.CHILDTYPE
     *
     * @mbg.generated
     */
    public String getChildtype() {
        return childtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.CHILDTYPE
     *
     * @param childtype the value for SYSCOMGROUPMEMBERS.CHILDTYPE
     *
     * @mbg.generated
     */
    public void setChildtype(String childtype) {
        this.childtype = childtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.LOCATIONNO
     *
     * @return the value of SYSCOMGROUPMEMBERS.LOCATIONNO
     *
     * @mbg.generated
     */
    public Integer getLocationno() {
        return locationno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.LOCATIONNO
     *
     * @param locationno the value for SYSCOMGROUPMEMBERS.LOCATIONNO
     *
     * @mbg.generated
     */
    public void setLocationno(Integer locationno) {
        this.locationno = locationno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.EFFECTDATE
     *
     * @return the value of SYSCOMGROUPMEMBERS.EFFECTDATE
     *
     * @mbg.generated
     */
    public Date getEffectdate() {
        return effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.EFFECTDATE
     *
     * @param effectdate the value for SYSCOMGROUPMEMBERS.EFFECTDATE
     *
     * @mbg.generated
     */
    public void setEffectdate(Date effectdate) {
        this.effectdate = effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.EXPIREDDATE
     *
     * @return the value of SYSCOMGROUPMEMBERS.EXPIREDDATE
     *
     * @mbg.generated
     */
    public Date getExpireddate() {
        return expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.EXPIREDDATE
     *
     * @param expireddate the value for SYSCOMGROUPMEMBERS.EXPIREDDATE
     *
     * @mbg.generated
     */
    public void setExpireddate(Date expireddate) {
        this.expireddate = expireddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.UPDATEUSERID
     *
     * @return the value of SYSCOMGROUPMEMBERS.UPDATEUSERID
     *
     * @mbg.generated
     */
    public Integer getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.UPDATEUSERID
     *
     * @param updateuserid the value for SYSCOMGROUPMEMBERS.UPDATEUSERID
     *
     * @mbg.generated
     */
    public void setUpdateuserid(Integer updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.UPDATETIME
     *
     * @return the value of SYSCOMGROUPMEMBERS.UPDATETIME
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.UPDATETIME
     *
     * @param updatetime the value for SYSCOMGROUPMEMBERS.UPDATETIME
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.SAFEDEFINEFUNCTIONLIST
     *
     * @return the value of SYSCOMGROUPMEMBERS.SAFEDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    public String getSafedefinefunctionlist() {
        return safedefinefunctionlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.SAFEDEFINEFUNCTIONLIST
     *
     * @param safedefinefunctionlist the value for SYSCOMGROUPMEMBERS.SAFEDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    public void setSafedefinefunctionlist(String safedefinefunctionlist) {
        this.safedefinefunctionlist = safedefinefunctionlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSCOMGROUPMEMBERS.USERDEFINEFUNCTIONLIST
     *
     * @return the value of SYSCOMGROUPMEMBERS.USERDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    public String getUserdefinefunctionlist() {
        return userdefinefunctionlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSCOMGROUPMEMBERS.USERDEFINEFUNCTIONLIST
     *
     * @param userdefinefunctionlist the value for SYSCOMGROUPMEMBERS.USERDEFINEFUNCTIONLIST
     *
     * @mbg.generated
     */
    public void setUserdefinefunctionlist(String userdefinefunctionlist) {
        this.userdefinefunctionlist = userdefinefunctionlist;
    }



	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((childid == null) ? 0 : childid.hashCode());
		result = prime * result + ((childname == null) ? 0 : childname.hashCode());
		result = prime * result + ((childtype == null) ? 0 : childtype.hashCode());
		result = prime * result + ((effectdate == null) ? 0 : effectdate.hashCode());
		result = prime * result + ((expireddate == null) ? 0 : expireddate.hashCode());
		result = prime * result + ((groupid == null) ? 0 : groupid.hashCode());
		result = prime * result + ((grouplevel == null) ? 0 : grouplevel.hashCode());
		result = prime * result + ((childno == null) ? 0 : childno.hashCode());
		result = prime * result + ((locationno == null) ? 0 : locationno.hashCode());
		result = prime * result + ((remark == null) ? 0 : remark.hashCode());
		result = prime * result + ((safedefinefunctionlist == null) ? 0 : safedefinefunctionlist.hashCode());
		result = prime * result + ((updatetime == null) ? 0 : updatetime.hashCode());
		result = prime * result + ((updateuserid == null) ? 0 : updateuserid.hashCode());
		result = prime * result + ((url == null) ? 0 : url.hashCode());
		result = prime * result + ((userdefinefunctionlist == null) ? 0 : userdefinefunctionlist.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SyscomgroupmembersAndGroupLevel other = (SyscomgroupmembersAndGroupLevel) obj;
		if (childid == null) {
			if (other.childid != null)
				return false;
		} else if (!childid.equals(other.childid))
			return false;
		if (childname == null) {
			if (other.childname != null)
				return false;
		} else if (!childname.equals(other.childname))
			return false;
		if (childtype == null) {
			if (other.childtype != null)
				return false;
		} else if (!childtype.equals(other.childtype))
			return false;
		if (effectdate == null) {
			if (other.effectdate != null)
				return false;
		} else if (!effectdate.equals(other.effectdate))
			return false;
		if (expireddate == null) {
			if (other.expireddate != null)
				return false;
		} else if (!expireddate.equals(other.expireddate))
			return false;
		if (groupid == null) {
			if (other.groupid != null)
				return false;
		} else if (!groupid.equals(other.groupid))
			return false;
		if (grouplevel == null) {
			if (other.grouplevel != null)
				return false;
		} else if (!grouplevel.equals(other.grouplevel))
			return false;
		if (childno == null) {
			if (other.childno != null)
				return false;
		} else if (!childno.equals(other.childno))
			return false;
		if (locationno == null) {
			if (other.locationno != null)
				return false;
		} else if (!locationno.equals(other.locationno))
			return false;
		if (remark == null) {
			if (other.remark != null)
				return false;
		} else if (!remark.equals(other.remark))
			return false;
		if (safedefinefunctionlist == null) {
			if (other.safedefinefunctionlist != null)
				return false;
		} else if (!safedefinefunctionlist.equals(other.safedefinefunctionlist))
			return false;
		if (updatetime == null) {
			if (other.updatetime != null)
				return false;
		} else if (!updatetime.equals(other.updatetime))
			return false;
		if (updateuserid == null) {
			if (other.updateuserid != null)
				return false;
		} else if (!updateuserid.equals(other.updateuserid))
			return false;
		if (url == null) {
			if (other.url != null)
				return false;
		} else if (!url.equals(other.url))
			return false;
		if (userdefinefunctionlist == null) {
			if (other.userdefinefunctionlist != null)
				return false;
		} else if (!userdefinefunctionlist.equals(other.userdefinefunctionlist))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "SyscomgroupmembersAndGroupLevel [groupid=" + groupid + ", childid=" + childid + ", childtype="
				+ childtype + ", locationno=" + locationno + ", effectdate=" + effectdate + ", expireddate="
				+ expireddate + ", updateuserid=" + updateuserid + ", updatetime=" + updatetime
				+ ", safedefinefunctionlist=" + safedefinefunctionlist + ", userdefinefunctionlist="
				+ userdefinefunctionlist + ", grouplevel=" + grouplevel + ", remark=" + remark + ", childname="
				+ childname + ", url=" + url + ", childno=" + childno + "]";
	}






}