package com.syscom.safeaa.mybatis.vo;

import java.util.Date;

import com.syscom.safeaa.mybatis.model.Syscomrole;
import com.syscom.safeaa.mybatis.model.Syscomroleculture;

public class SyscomroleAndCulture {
	
    public SyscomroleAndCulture(Integer roleid, String roleno, String roletype, Date effectdate, Date expireddate, Integer updateuserid, Date updatetime, String culture, String rolename, String remark) {
        this.roleid = roleid;
        this.roleno = roleno;
        this.roletype = roletype;
        this.effectdate = effectdate;
        this.expireddate = expireddate;
        this.updateuserid = updateuserid;
        this.updatetime = updatetime;
        this.culture = culture;
        this.rolename = rolename;
        this.remark = remark;        
    }
    
    public SyscomroleAndCulture() {
        super();
    }
    
	public SyscomroleAndCulture (String culture) {
		this.culture = culture;
	}
	
	public SyscomroleAndCulture (int roleId, String culture) {
		this.roleid = roleId;
		this.culture = culture;
	}
	
	public SyscomroleAndCulture ( String roleName,String culture) {
		this.culture = culture;
		this.rolename = roleName;
	}
	
	public SyscomroleAndCulture (Syscomrole role, Syscomroleculture culture) {
		this.roleid = role.getRoleid();
		this.roleno = role.getRoleno();
		this.roletype = role.getRoletype();
		this.effectdate = role.getEffectdate();
		this.expireddate = role.getExpireddate();
		this.culture = culture.getCulture();
		this.rolename = culture.getRolename();
		this.remark = culture.getRemark();
		this.updateuserid = role.getUpdateuserid();
		this.updatetime = role.getUpdatetime();
	}

    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSCOMROLE.ROLENO
     *
     * @mbg.generated
     */
    private String roleno;
    
    /**
    *
    * This field corresponds to the database column SYSCOMROLE.ROLETYPE
    *
    * @mbg.generated
    */
   private String roletype;    

    public Integer getRoleid() {
		return roleid;
	}


	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}


	public String getRoleno() {
		return roleno;
	}


	public void setRoleno(String roleno) {
		this.roleno = roleno;
	}


	public String getRoletype() {
		return roletype;
	}


	public void setRoletype(String roletype) {
		this.roletype = roletype;
	}


	public Date getEffectdate() {
		return effectdate;
	}


	public void setEffectdate(Date effectdate) {
		this.effectdate = effectdate;
	}


	public Date getExpireddate() {
		return expireddate;
	}


	public void setExpireddate(Date expireddate) {
		this.expireddate = expireddate;
	}


	public Integer getUpdateuserid() {
		return updateuserid;
	}


	public void setUpdateuserid(Integer updateuserid) {
		this.updateuserid = updateuserid;
	}


	public Date getUpdatetime() {
		return updatetime;
	}


	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}


	public String getRolename() {
		return rolename;
	}


	public void setRolename(String rolename) {
		this.rolename = rolename;
	}


	public String getCulture() {
		return culture;
	}


	public void setCulture(String culture) {
		this.culture = culture;
	}


	public String getRemark() {
		return remark;
	}


	public void setRemark(String remark) {
		this.remark = remark;
	}


	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column SYSCOMROLE.EFFECTDATE
    *
    * @mbg.generated
    */
   private Date effectdate;
   

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column SYSCOMROLE.EXPIREDDATE
    *
    * @mbg.generated
    */
   private Date expireddate;
   /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column SYSCOMROLE.UPDATEUSERID
   *
   * @mbg.generated
   */
  private Integer updateuserid;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column SYSCOMROLE.UPDATETIME
   *
   * @mbg.generated
   */
  private Date updatetime;
  
  /**
  *
  * This field was generated by MyBatis Generator.
  * This field corresponds to the database column SYSCOMROLECULTURE.ROLENAME
  *
  * @mbg.generated
  */
  private String rolename;
  
  /**
  *
  * This field was generated by MyBatis Generator.
  * This field corresponds to the database column SYSCOMROLECULTURE.CULTURE
  *
  * @mbg.generated
  */
  private String culture;  
  
  
  /**
  *
  * This field was generated by MyBatis Generator.
  * This field corresponds to the database column SYSCOMROLECULTURE.REMARK
  *
  * @mbg.generated
  */
  private String remark;

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((culture == null) ? 0 : culture.hashCode());
		result = prime * result + ((effectdate == null) ? 0 : effectdate.hashCode());
		result = prime * result + ((expireddate == null) ? 0 : expireddate.hashCode());
		result = prime * result + ((remark == null) ? 0 : remark.hashCode());
		result = prime * result + ((roleid == null) ? 0 : roleid.hashCode());
		result = prime * result + ((rolename == null) ? 0 : rolename.hashCode());
		result = prime * result + ((roleno == null) ? 0 : roleno.hashCode());
		result = prime * result + ((roletype == null) ? 0 : roletype.hashCode());
		result = prime * result + ((updatetime == null) ? 0 : updatetime.hashCode());
		result = prime * result + ((updateuserid == null) ? 0 : updateuserid.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SyscomroleAndCulture other = (SyscomroleAndCulture) obj;
		if (culture == null) {
			if (other.culture != null)
				return false;
		} else if (!culture.equals(other.culture))
			return false;
		if (effectdate == null) {
			if (other.effectdate != null)
				return false;
		} else if (!effectdate.equals(other.effectdate))
			return false;
		if (expireddate == null) {
			if (other.expireddate != null)
				return false;
		} else if (!expireddate.equals(other.expireddate))
			return false;
		if (remark == null) {
			if (other.remark != null)
				return false;
		} else if (!remark.equals(other.remark))
			return false;
		if (roleid == null) {
			if (other.roleid != null)
				return false;
		} else if (!roleid.equals(other.roleid))
			return false;
		if (rolename == null) {
			if (other.rolename != null)
				return false;
		} else if (!rolename.equals(other.rolename))
			return false;
		if (roleno == null) {
			if (other.roleno != null)
				return false;
		} else if (!roleno.equals(other.roleno))
			return false;
		if (roletype == null) {
			if (other.roletype != null)
				return false;
		} else if (!roletype.equals(other.roletype))
			return false;
		if (updatetime == null) {
			if (other.updatetime != null)
				return false;
		} else if (!updatetime.equals(other.updatetime))
			return false;
		if (updateuserid == null) {
			if (other.updateuserid != null)
				return false;
		} else if (!updateuserid.equals(other.updateuserid))
			return false;
		return true;
	}


	@Override
	public String toString() {
		return "SyscomroleAndCulture [roleid=" + roleid + ", roleno=" + roleno + ", roletype=" + roletype
				+ ", effectdate=" + effectdate + ", expireddate=" + expireddate + ", updateuserid=" + updateuserid
				+ ", updatetime=" + updatetime + ", rolename=" + rolename + ", culture=" + culture + ", remark="
				+ remark + "]";
	}
    
	
}
