package com.syscom.safeaa.mybatis.vo;

import java.util.Date;

public class SyscomrolegroupAndCulture {

	public SyscomrolegroupAndCulture() {}
	
	    /**
	    *
	    * This field corresponds to the database column SYSCOMROLEDENY.ROLEID
	    *
	    * @mbg.generated
	    */
	   private Integer roleid;
	
	   /**
	    *
	    * This field corresponds to the database column SYSCOMROLEDENY.CHILDID
	    *
	    * @mbg.generated
	    */
	   private Integer childid;

	    /**
	     *
	     * This field corresponds to the database column SYSCOMROLEGROUP.GROUPID
	     */
	    private Integer groupid;

	    /**
	     * This field corresponds to the database column SYSCOMROLEGROUP.CHILDTYPE
	     *
	     * @mbg.generated
	     */
	    private String childtype;

	    /**
	     *
	     * This field corresponds to the database column SYSCOMGROUP.GROUPNO
	     *
	     * @mbg.generated
	     */
	    private String groupno;
	    
	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column SYSCOMGROUPCULTURE.CULTURE
	     *
	     * @mbg.generated
	     */
	    private String culture;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column SYSCOMGROUPCULTURE.GROUPNAME
	     *
	     * @mbg.generated
	     */
	    private String groupname;
	    
	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column SYSCOMGROUP.EFFECTDATE
	     *
	     * @mbg.generated
	     */
	    private Date effectdate;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column SYSCOMGROUP.EXPIREDDATE
	     *
	     * @mbg.generated
	     */
	    private Date expireddate;
	    
	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column SYSCOMGROUPCULTURE.REMARK
	     *
	     * @mbg.generated
	     */
	    private String remark;	    

		public String getRemark() {
			return remark;
		}

		public void setRemark(String remark) {
			this.remark = remark;
		}

		public String getCulture() {
			return culture;
		}

		public void setCulture(String culture) {
			this.culture = culture;
		}

		public Integer getRoleid() {
			return roleid;
		}

		public void setRoleid(Integer roleid) {
			this.roleid = roleid;
		}

		public Integer getGroupid() {
			return groupid;
		}

		public void setGroupid(Integer groupid) {
			this.groupid = groupid;
		}

		public String getChildtype() {
			return childtype;
		}

		public void setChildtype(String childtype) {
			this.childtype = childtype;
		}

		public String getGroupno() {
			return groupno;
		}

		public void setGroupno(String groupno) {
			this.groupno = groupno;
		}

		public String getGroupname() {
			return groupname;
		}

		public void setGroupname(String groupname) {
			this.groupname = groupname;
		}

		public Date getEffectdate() {
			return effectdate;
		}

		public void setEffectdate(Date effectdate) {
			this.effectdate = effectdate;
		}

		public Date getExpireddate() {
			return expireddate;
		}

		public void setExpireddate(Date expireddate) {
			this.expireddate = expireddate;
		}	    
}
