package com.syscom.safeaa.mybatis.vo;

import java.util.Date;

public class SyscomrolemembersAndCulture {

	private Integer userid;
	private String logonid;
	private String username;
	private Integer roleid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column SYSCOMROLE.ROLENO
	 *
	 * @mbg.generated
	 */
	private String roleno;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column SYSCOMROLEMEMBERS.CHILDID
	 *
	 * @mbg.generated
	 */
	private Integer childid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column SYSCOMROLEMEMBERS.CHILDTYPE
	 *
	 * @mbg.generated
	 */
	private String childtype;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column SYSCOMROLECULTURE.ROLENAME
	 *
	 * @mbg.generated
	 */
	private String rolename;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column SYSCOMROLE.EFFECTDATE
	 *
	 * @mbg.generated
	 */
	private Date effectdate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column SYSCOMROLE.EXPIREDDATE
	 *
	 * @mbg.generated
	 */
	private Date expireddate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column SYSCOMROLECULTURE.CULTURE
	 *
	 * @mbg.generated
	 */
	private String culture;

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getLogonid() {
		return logonid;
	}

	public void setLogonid(String logonid) {
		this.logonid = logonid;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getRoleid() {
		return roleid;
	}

	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	public String getRoleno() {
		return roleno;
	}

	public void setRoleno(String roleno) {
		this.roleno = roleno;
	}

	public Integer getChildid() {
		return childid;
	}

	public void setChildid(Integer childid) {
		this.childid = childid;
	}

	public String getChildtype() {
		return childtype;
	}

	public void setChildtype(String childtype) {
		this.childtype = childtype;
	}

	public String getRolename() {
		return rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public Date getEffectdate() {
		return effectdate;
	}

	public void setEffectdate(Date effectdate) {
		this.effectdate = effectdate;
	}

	public Date getExpireddate() {
		return expireddate;
	}

	public void setExpireddate(Date expireddate) {
		this.expireddate = expireddate;
	}

	public String getCulture() {
		return culture;
	}

	public void setCulture(String culture) {
		this.culture = culture;
	}

	public SyscomrolemembersAndCulture() {
	}

	@Override
	public int hashCode() {
//		final int 31 = 31;
		int result = 1;
		result = 31 * result + ((childid == null) ? 0 : childid.hashCode());
		result = 31 * result + ((childtype == null) ? 0 : childtype.hashCode());
		result = 31 * result + ((culture == null) ? 0 : culture.hashCode());
		result = 31 * result + ((effectdate == null) ? 0 : effectdate.hashCode());
		result = 31 * result + ((expireddate == null) ? 0 : expireddate.hashCode());
		result = 31 * result + ((logonid == null) ? 0 : logonid.hashCode());
		result = 31 * result + ((roleid == null) ? 0 : roleid.hashCode());
		result = 31 * result + ((rolename == null) ? 0 : rolename.hashCode());
		result = 31 * result + ((roleno == null) ? 0 : roleno.hashCode());
		result = 31 * result + ((userid == null) ? 0 : userid.hashCode());
		result = 31 * result + ((username == null) ? 0 : username.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SyscomrolemembersAndCulture other = (SyscomrolemembersAndCulture) obj;
		if (childid == null) {
			if (other.childid != null)
				return false;
		} else if (!childid.equals(other.childid))
			return false;
		if (childtype == null) {
			if (other.childtype != null)
				return false;
		} else if (!childtype.equals(other.childtype))
			return false;
		if (culture == null) {
			if (other.culture != null)
				return false;
		} else if (!culture.equals(other.culture))
			return false;
		if (effectdate == null) {
			if (other.effectdate != null)
				return false;
		} else if (!effectdate.equals(other.effectdate))
			return false;
		if (expireddate == null) {
			if (other.expireddate != null)
				return false;
		} else if (!expireddate.equals(other.expireddate))
			return false;
		if (logonid == null) {
			if (other.logonid != null)
				return false;
		} else if (!logonid.equals(other.logonid))
			return false;
		if (roleid == null) {
			if (other.roleid != null)
				return false;
		} else if (!roleid.equals(other.roleid))
			return false;
		if (rolename == null) {
			if (other.rolename != null)
				return false;
		} else if (!rolename.equals(other.rolename))
			return false;
		if (roleno == null) {
			if (other.roleno != null)
				return false;
		} else if (!roleno.equals(other.roleno))
			return false;
		if (userid == null) {
			if (other.userid != null)
				return false;
		} else if (!userid.equals(other.userid))
			return false;
		if (username == null) {
			if (other.username != null)
				return false;
		} else if (!username.equals(other.username))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "SyscomrolemembersAndCulture [userid=" + userid + ", logonid=" + logonid + ", username=" + username
				+ ", roleid=" + roleid + ", roleno=" + roleno + ", childid=" + childid + ", childtype=" + childtype
				+ ", rolename=" + rolename + ", effectdate=" + effectdate + ", expireddate=" + expireddate
				+ ", culture=" + culture + "]";
	}

}
