package com.syscom.fep.mybatis.model;

import com.syscom.fep.mybatis.vo.BaseModel;
import java.util.Date;
import org.apache.commons.lang3.StringUtils;

public class Sysstat extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_HBKNO
     *
     * @mbg.generated
     */
    private String sysstatHbkno = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_FBKNO
     *
     * @mbg.generated
     */
    private String sysstatFbkno = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_SCBKNO
     *
     * @mbg.generated
     */
    private String sysstatScbkno = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_LBSDY_FISC
     *
     * @mbg.generated
     */
    private String sysstatLbsdyFisc = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_TBSDY_FISC
     *
     * @mbg.generated
     */
    private String sysstatTbsdyFisc = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_NBSDY_FISC
     *
     * @mbg.generated
     */
    private String sysstatNbsdyFisc = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_FOPCSYNC
     *
     * @mbg.generated
     */
    private String sysstatFopcsync;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_TOPCSYNC
     *
     * @mbg.generated
     */
    private String sysstatTopcsync;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_FCDSYNC
     *
     * @mbg.generated
     */
    private String sysstatFcdsync;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_TCDSYNC
     *
     * @mbg.generated
     */
    private String sysstatTcdsync;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_FRMSYNC
     *
     * @mbg.generated
     */
    private String sysstatFrmsync;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_TRMSYNC
     *
     * @mbg.generated
     */
    private String sysstatTrmsync;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_FPPSYNC
     *
     * @mbg.generated
     */
    private String sysstatFppsync;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_TPPSYNC
     *
     * @mbg.generated
     */
    private String sysstatTppsync;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_F3DESSYNC
     *
     * @mbg.generated
     */
    private String sysstatF3dessync;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_T3DESSYNC
     *
     * @mbg.generated
     */
    private String sysstatT3dessync;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_SOCT
     *
     * @mbg.generated
     */
    private String sysstatSoct = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_AOCT_2000
     *
     * @mbg.generated
     */
    private String sysstatAoct2000 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_AOCT_2200
     *
     * @mbg.generated
     */
    private String sysstatAoct2200 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_AOCT_2500
     *
     * @mbg.generated
     */
    private String sysstatAoct2500 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_AOCT_2510
     *
     * @mbg.generated
     */
    private String sysstatAoct2510 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_AOCT_2520
     *
     * @mbg.generated
     */
    private String sysstatAoct2520 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_AOCT_2530
     *
     * @mbg.generated
     */
    private String sysstatAoct2530 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_AOCT_2540
     *
     * @mbg.generated
     */
    private String sysstatAoct2540 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_AOCT_2550
     *
     * @mbg.generated
     */
    private String sysstatAoct2550 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_AOCT_2560
     *
     * @mbg.generated
     */
    private String sysstatAoct2560 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_AOCT_7100
     *
     * @mbg.generated
     */
    private String sysstatAoct7100 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_AOCT_1000
     *
     * @mbg.generated
     */
    private String sysstatAoct1000 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_AOCT_1100
     *
     * @mbg.generated
     */
    private String sysstatAoct1100 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_AOCT_1200
     *
     * @mbg.generated
     */
    private String sysstatAoct1200 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_AOCT_1300
     *
     * @mbg.generated
     */
    private String sysstatAoct1300 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_AOCT_1400
     *
     * @mbg.generated
     */
    private String sysstatAoct1400 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_MBOCT
     *
     * @mbg.generated
     */
    private String sysstatMboct = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_MBACT_2000
     *
     * @mbg.generated
     */
    private String sysstatMbact2000 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_MBACT_2200
     *
     * @mbg.generated
     */
    private String sysstatMbact2200 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_MBACT_2500
     *
     * @mbg.generated
     */
    private String sysstatMbact2500 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_MBACT_2510
     *
     * @mbg.generated
     */
    private String sysstatMbact2510 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_MBACT_2520
     *
     * @mbg.generated
     */
    private String sysstatMbact2520 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_MBACT_2530
     *
     * @mbg.generated
     */
    private String sysstatMbact2530 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_MBACT_2540
     *
     * @mbg.generated
     */
    private String sysstatMbact2540 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_MBACT_2550
     *
     * @mbg.generated
     */
    private String sysstatMbact2550 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_MBACT_2560
     *
     * @mbg.generated
     */
    private String sysstatMbact2560 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_MBACT_7100
     *
     * @mbg.generated
     */
    private String sysstatMbact7100 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_MBACT_1000
     *
     * @mbg.generated
     */
    private String sysstatMbact1000 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_MBACT_1100
     *
     * @mbg.generated
     */
    private String sysstatMbact1100 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_MBACT_1200
     *
     * @mbg.generated
     */
    private String sysstatMbact1200 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_MBACT_1300
     *
     * @mbg.generated
     */
    private String sysstatMbact1300 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_MBACT_1400
     *
     * @mbg.generated
     */
    private String sysstatMbact1400 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_OPCKEYST
     *
     * @mbg.generated
     */
    private Short sysstatOpckeyst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_ATMKEYST
     *
     * @mbg.generated
     */
    private Short sysstatAtmkeyst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_RMKEYST
     *
     * @mbg.generated
     */
    private Short sysstatRmkeyst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_PPKEYST
     *
     * @mbg.generated
     */
    private Short sysstatPpkeyst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_3ENCKEYST
     *
     * @mbg.generated
     */
    private Short sysstat3enckeyst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_CBS
     *
     * @mbg.generated
     */
    private Short sysstatCbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.UPDATE_USERID
     *
     * @mbg.generated
     */
    private Integer updateUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_AOCT_7300
     *
     * @mbg.generated
     */
    private String sysstatAoct7300 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_MBACT_7300
     *
     * @mbg.generated
     */
    private String sysstatMbact7300 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_T24_TWN
     *
     * @mbg.generated
     */
    private Short sysstatT24Twn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_AOCT_2570
     *
     * @mbg.generated
     */
    private String sysstatAoct2570 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_MBACT_2570
     *
     * @mbg.generated
     */
    private String sysstatMbact2570 = StringUtils.SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_KEYBLOCKST
     *
     * @mbg.generated
     */
    private Short sysstatKeyblockst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_KEYDIV
     *
     * @mbg.generated
     */
    private Short sysstatKeydiv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_CHECKVALUE
     *
     * @mbg.generated
     */
    private String sysstatCheckvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_FCS
     *
     * @mbg.generated
     */
    private Short sysstatFcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_CREDIT
     *
     * @mbg.generated
     */
    private Short sysstatCredit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_MTP
     *
     * @mbg.generated
     */
    private Short sysstatMtp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSSTAT.SYSSTAT_TWMP
     *
     * @mbg.generated
     */
    private Short sysstatTwmp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSSTAT
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSSTAT
     *
     * @mbg.generated
     */
    public Sysstat(String sysstatHbkno, String sysstatFbkno, String sysstatScbkno, String sysstatLbsdyFisc, String sysstatTbsdyFisc, String sysstatNbsdyFisc, String sysstatFopcsync, String sysstatTopcsync, String sysstatFcdsync, String sysstatTcdsync, String sysstatFrmsync, String sysstatTrmsync, String sysstatFppsync, String sysstatTppsync, String sysstatF3dessync, String sysstatT3dessync, String sysstatSoct, String sysstatAoct2000, String sysstatAoct2200, String sysstatAoct2500, String sysstatAoct2510, String sysstatAoct2520, String sysstatAoct2530, String sysstatAoct2540, String sysstatAoct2550, String sysstatAoct2560, String sysstatAoct7100, String sysstatAoct1000, String sysstatAoct1100, String sysstatAoct1200, String sysstatAoct1300, String sysstatAoct1400, String sysstatMboct, String sysstatMbact2000, String sysstatMbact2200, String sysstatMbact2500, String sysstatMbact2510, String sysstatMbact2520, String sysstatMbact2530, String sysstatMbact2540, String sysstatMbact2550, String sysstatMbact2560, String sysstatMbact7100, String sysstatMbact1000, String sysstatMbact1100, String sysstatMbact1200, String sysstatMbact1300, String sysstatMbact1400, Short sysstatOpckeyst, Short sysstatAtmkeyst, Short sysstatRmkeyst, Short sysstatPpkeyst, Short sysstat3enckeyst, Short sysstatCbs, Integer updateUserid, Date updateTime, String sysstatAoct7300, String sysstatMbact7300, Short sysstatT24Twn, String sysstatAoct2570, String sysstatMbact2570, Short sysstatKeyblockst, Short sysstatKeydiv, String sysstatCheckvalue, Short sysstatFcs, Short sysstatCredit, Short sysstatMtp, Short sysstatTwmp) {
        this.sysstatHbkno = sysstatHbkno;
        this.sysstatFbkno = sysstatFbkno;
        this.sysstatScbkno = sysstatScbkno;
        this.sysstatLbsdyFisc = sysstatLbsdyFisc;
        this.sysstatTbsdyFisc = sysstatTbsdyFisc;
        this.sysstatNbsdyFisc = sysstatNbsdyFisc;
        this.sysstatFopcsync = sysstatFopcsync;
        this.sysstatTopcsync = sysstatTopcsync;
        this.sysstatFcdsync = sysstatFcdsync;
        this.sysstatTcdsync = sysstatTcdsync;
        this.sysstatFrmsync = sysstatFrmsync;
        this.sysstatTrmsync = sysstatTrmsync;
        this.sysstatFppsync = sysstatFppsync;
        this.sysstatTppsync = sysstatTppsync;
        this.sysstatF3dessync = sysstatF3dessync;
        this.sysstatT3dessync = sysstatT3dessync;
        this.sysstatSoct = sysstatSoct;
        this.sysstatAoct2000 = sysstatAoct2000;
        this.sysstatAoct2200 = sysstatAoct2200;
        this.sysstatAoct2500 = sysstatAoct2500;
        this.sysstatAoct2510 = sysstatAoct2510;
        this.sysstatAoct2520 = sysstatAoct2520;
        this.sysstatAoct2530 = sysstatAoct2530;
        this.sysstatAoct2540 = sysstatAoct2540;
        this.sysstatAoct2550 = sysstatAoct2550;
        this.sysstatAoct2560 = sysstatAoct2560;
        this.sysstatAoct7100 = sysstatAoct7100;
        this.sysstatAoct1000 = sysstatAoct1000;
        this.sysstatAoct1100 = sysstatAoct1100;
        this.sysstatAoct1200 = sysstatAoct1200;
        this.sysstatAoct1300 = sysstatAoct1300;
        this.sysstatAoct1400 = sysstatAoct1400;
        this.sysstatMboct = sysstatMboct;
        this.sysstatMbact2000 = sysstatMbact2000;
        this.sysstatMbact2200 = sysstatMbact2200;
        this.sysstatMbact2500 = sysstatMbact2500;
        this.sysstatMbact2510 = sysstatMbact2510;
        this.sysstatMbact2520 = sysstatMbact2520;
        this.sysstatMbact2530 = sysstatMbact2530;
        this.sysstatMbact2540 = sysstatMbact2540;
        this.sysstatMbact2550 = sysstatMbact2550;
        this.sysstatMbact2560 = sysstatMbact2560;
        this.sysstatMbact7100 = sysstatMbact7100;
        this.sysstatMbact1000 = sysstatMbact1000;
        this.sysstatMbact1100 = sysstatMbact1100;
        this.sysstatMbact1200 = sysstatMbact1200;
        this.sysstatMbact1300 = sysstatMbact1300;
        this.sysstatMbact1400 = sysstatMbact1400;
        this.sysstatOpckeyst = sysstatOpckeyst;
        this.sysstatAtmkeyst = sysstatAtmkeyst;
        this.sysstatRmkeyst = sysstatRmkeyst;
        this.sysstatPpkeyst = sysstatPpkeyst;
        this.sysstat3enckeyst = sysstat3enckeyst;
        this.sysstatCbs = sysstatCbs;
        this.updateUserid = updateUserid;
        this.updateTime = updateTime;
        this.sysstatAoct7300 = sysstatAoct7300;
        this.sysstatMbact7300 = sysstatMbact7300;
        this.sysstatT24Twn = sysstatT24Twn;
        this.sysstatAoct2570 = sysstatAoct2570;
        this.sysstatMbact2570 = sysstatMbact2570;
        this.sysstatKeyblockst = sysstatKeyblockst;
        this.sysstatKeydiv = sysstatKeydiv;
        this.sysstatCheckvalue = sysstatCheckvalue;
        this.sysstatFcs = sysstatFcs;
        this.sysstatCredit = sysstatCredit;
        this.sysstatMtp = sysstatMtp;
        this.sysstatTwmp = sysstatTwmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSSTAT
     *
     * @mbg.generated
     */
    public Sysstat() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_HBKNO
     *
     * @return the value of SYSSTAT.SYSSTAT_HBKNO
     *
     * @mbg.generated
     */
    public String getSysstatHbkno() {
        return sysstatHbkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_HBKNO
     *
     * @param sysstatHbkno the value for SYSSTAT.SYSSTAT_HBKNO
     *
     * @mbg.generated
     */
    public void setSysstatHbkno(String sysstatHbkno) {
        this.sysstatHbkno = sysstatHbkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_FBKNO
     *
     * @return the value of SYSSTAT.SYSSTAT_FBKNO
     *
     * @mbg.generated
     */
    public String getSysstatFbkno() {
        return sysstatFbkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_FBKNO
     *
     * @param sysstatFbkno the value for SYSSTAT.SYSSTAT_FBKNO
     *
     * @mbg.generated
     */
    public void setSysstatFbkno(String sysstatFbkno) {
        this.sysstatFbkno = sysstatFbkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_SCBKNO
     *
     * @return the value of SYSSTAT.SYSSTAT_SCBKNO
     *
     * @mbg.generated
     */
    public String getSysstatScbkno() {
        return sysstatScbkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_SCBKNO
     *
     * @param sysstatScbkno the value for SYSSTAT.SYSSTAT_SCBKNO
     *
     * @mbg.generated
     */
    public void setSysstatScbkno(String sysstatScbkno) {
        this.sysstatScbkno = sysstatScbkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_LBSDY_FISC
     *
     * @return the value of SYSSTAT.SYSSTAT_LBSDY_FISC
     *
     * @mbg.generated
     */
    public String getSysstatLbsdyFisc() {
        return sysstatLbsdyFisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_LBSDY_FISC
     *
     * @param sysstatLbsdyFisc the value for SYSSTAT.SYSSTAT_LBSDY_FISC
     *
     * @mbg.generated
     */
    public void setSysstatLbsdyFisc(String sysstatLbsdyFisc) {
        this.sysstatLbsdyFisc = sysstatLbsdyFisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_TBSDY_FISC
     *
     * @return the value of SYSSTAT.SYSSTAT_TBSDY_FISC
     *
     * @mbg.generated
     */
    public String getSysstatTbsdyFisc() {
        return sysstatTbsdyFisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_TBSDY_FISC
     *
     * @param sysstatTbsdyFisc the value for SYSSTAT.SYSSTAT_TBSDY_FISC
     *
     * @mbg.generated
     */
    public void setSysstatTbsdyFisc(String sysstatTbsdyFisc) {
        this.sysstatTbsdyFisc = sysstatTbsdyFisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_NBSDY_FISC
     *
     * @return the value of SYSSTAT.SYSSTAT_NBSDY_FISC
     *
     * @mbg.generated
     */
    public String getSysstatNbsdyFisc() {
        return sysstatNbsdyFisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_NBSDY_FISC
     *
     * @param sysstatNbsdyFisc the value for SYSSTAT.SYSSTAT_NBSDY_FISC
     *
     * @mbg.generated
     */
    public void setSysstatNbsdyFisc(String sysstatNbsdyFisc) {
        this.sysstatNbsdyFisc = sysstatNbsdyFisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_FOPCSYNC
     *
     * @return the value of SYSSTAT.SYSSTAT_FOPCSYNC
     *
     * @mbg.generated
     */
    public String getSysstatFopcsync() {
        return sysstatFopcsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_FOPCSYNC
     *
     * @param sysstatFopcsync the value for SYSSTAT.SYSSTAT_FOPCSYNC
     *
     * @mbg.generated
     */
    public void setSysstatFopcsync(String sysstatFopcsync) {
        this.sysstatFopcsync = sysstatFopcsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_TOPCSYNC
     *
     * @return the value of SYSSTAT.SYSSTAT_TOPCSYNC
     *
     * @mbg.generated
     */
    public String getSysstatTopcsync() {
        return sysstatTopcsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_TOPCSYNC
     *
     * @param sysstatTopcsync the value for SYSSTAT.SYSSTAT_TOPCSYNC
     *
     * @mbg.generated
     */
    public void setSysstatTopcsync(String sysstatTopcsync) {
        this.sysstatTopcsync = sysstatTopcsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_FCDSYNC
     *
     * @return the value of SYSSTAT.SYSSTAT_FCDSYNC
     *
     * @mbg.generated
     */
    public String getSysstatFcdsync() {
        return sysstatFcdsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_FCDSYNC
     *
     * @param sysstatFcdsync the value for SYSSTAT.SYSSTAT_FCDSYNC
     *
     * @mbg.generated
     */
    public void setSysstatFcdsync(String sysstatFcdsync) {
        this.sysstatFcdsync = sysstatFcdsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_TCDSYNC
     *
     * @return the value of SYSSTAT.SYSSTAT_TCDSYNC
     *
     * @mbg.generated
     */
    public String getSysstatTcdsync() {
        return sysstatTcdsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_TCDSYNC
     *
     * @param sysstatTcdsync the value for SYSSTAT.SYSSTAT_TCDSYNC
     *
     * @mbg.generated
     */
    public void setSysstatTcdsync(String sysstatTcdsync) {
        this.sysstatTcdsync = sysstatTcdsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_FRMSYNC
     *
     * @return the value of SYSSTAT.SYSSTAT_FRMSYNC
     *
     * @mbg.generated
     */
    public String getSysstatFrmsync() {
        return sysstatFrmsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_FRMSYNC
     *
     * @param sysstatFrmsync the value for SYSSTAT.SYSSTAT_FRMSYNC
     *
     * @mbg.generated
     */
    public void setSysstatFrmsync(String sysstatFrmsync) {
        this.sysstatFrmsync = sysstatFrmsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_TRMSYNC
     *
     * @return the value of SYSSTAT.SYSSTAT_TRMSYNC
     *
     * @mbg.generated
     */
    public String getSysstatTrmsync() {
        return sysstatTrmsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_TRMSYNC
     *
     * @param sysstatTrmsync the value for SYSSTAT.SYSSTAT_TRMSYNC
     *
     * @mbg.generated
     */
    public void setSysstatTrmsync(String sysstatTrmsync) {
        this.sysstatTrmsync = sysstatTrmsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_FPPSYNC
     *
     * @return the value of SYSSTAT.SYSSTAT_FPPSYNC
     *
     * @mbg.generated
     */
    public String getSysstatFppsync() {
        return sysstatFppsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_FPPSYNC
     *
     * @param sysstatFppsync the value for SYSSTAT.SYSSTAT_FPPSYNC
     *
     * @mbg.generated
     */
    public void setSysstatFppsync(String sysstatFppsync) {
        this.sysstatFppsync = sysstatFppsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_TPPSYNC
     *
     * @return the value of SYSSTAT.SYSSTAT_TPPSYNC
     *
     * @mbg.generated
     */
    public String getSysstatTppsync() {
        return sysstatTppsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_TPPSYNC
     *
     * @param sysstatTppsync the value for SYSSTAT.SYSSTAT_TPPSYNC
     *
     * @mbg.generated
     */
    public void setSysstatTppsync(String sysstatTppsync) {
        this.sysstatTppsync = sysstatTppsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_F3DESSYNC
     *
     * @return the value of SYSSTAT.SYSSTAT_F3DESSYNC
     *
     * @mbg.generated
     */
    public String getSysstatF3dessync() {
        return sysstatF3dessync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_F3DESSYNC
     *
     * @param sysstatF3dessync the value for SYSSTAT.SYSSTAT_F3DESSYNC
     *
     * @mbg.generated
     */
    public void setSysstatF3dessync(String sysstatF3dessync) {
        this.sysstatF3dessync = sysstatF3dessync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_T3DESSYNC
     *
     * @return the value of SYSSTAT.SYSSTAT_T3DESSYNC
     *
     * @mbg.generated
     */
    public String getSysstatT3dessync() {
        return sysstatT3dessync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_T3DESSYNC
     *
     * @param sysstatT3dessync the value for SYSSTAT.SYSSTAT_T3DESSYNC
     *
     * @mbg.generated
     */
    public void setSysstatT3dessync(String sysstatT3dessync) {
        this.sysstatT3dessync = sysstatT3dessync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_SOCT
     *
     * @return the value of SYSSTAT.SYSSTAT_SOCT
     *
     * @mbg.generated
     */
    public String getSysstatSoct() {
        return sysstatSoct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_SOCT
     *
     * @param sysstatSoct the value for SYSSTAT.SYSSTAT_SOCT
     *
     * @mbg.generated
     */
    public void setSysstatSoct(String sysstatSoct) {
        this.sysstatSoct = sysstatSoct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_AOCT_2000
     *
     * @return the value of SYSSTAT.SYSSTAT_AOCT_2000
     *
     * @mbg.generated
     */
    public String getSysstatAoct2000() {
        return sysstatAoct2000;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_AOCT_2000
     *
     * @param sysstatAoct2000 the value for SYSSTAT.SYSSTAT_AOCT_2000
     *
     * @mbg.generated
     */
    public void setSysstatAoct2000(String sysstatAoct2000) {
        this.sysstatAoct2000 = sysstatAoct2000;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_AOCT_2200
     *
     * @return the value of SYSSTAT.SYSSTAT_AOCT_2200
     *
     * @mbg.generated
     */
    public String getSysstatAoct2200() {
        return sysstatAoct2200;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_AOCT_2200
     *
     * @param sysstatAoct2200 the value for SYSSTAT.SYSSTAT_AOCT_2200
     *
     * @mbg.generated
     */
    public void setSysstatAoct2200(String sysstatAoct2200) {
        this.sysstatAoct2200 = sysstatAoct2200;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_AOCT_2500
     *
     * @return the value of SYSSTAT.SYSSTAT_AOCT_2500
     *
     * @mbg.generated
     */
    public String getSysstatAoct2500() {
        return sysstatAoct2500;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_AOCT_2500
     *
     * @param sysstatAoct2500 the value for SYSSTAT.SYSSTAT_AOCT_2500
     *
     * @mbg.generated
     */
    public void setSysstatAoct2500(String sysstatAoct2500) {
        this.sysstatAoct2500 = sysstatAoct2500;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_AOCT_2510
     *
     * @return the value of SYSSTAT.SYSSTAT_AOCT_2510
     *
     * @mbg.generated
     */
    public String getSysstatAoct2510() {
        return sysstatAoct2510;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_AOCT_2510
     *
     * @param sysstatAoct2510 the value for SYSSTAT.SYSSTAT_AOCT_2510
     *
     * @mbg.generated
     */
    public void setSysstatAoct2510(String sysstatAoct2510) {
        this.sysstatAoct2510 = sysstatAoct2510;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_AOCT_2520
     *
     * @return the value of SYSSTAT.SYSSTAT_AOCT_2520
     *
     * @mbg.generated
     */
    public String getSysstatAoct2520() {
        return sysstatAoct2520;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_AOCT_2520
     *
     * @param sysstatAoct2520 the value for SYSSTAT.SYSSTAT_AOCT_2520
     *
     * @mbg.generated
     */
    public void setSysstatAoct2520(String sysstatAoct2520) {
        this.sysstatAoct2520 = sysstatAoct2520;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_AOCT_2530
     *
     * @return the value of SYSSTAT.SYSSTAT_AOCT_2530
     *
     * @mbg.generated
     */
    public String getSysstatAoct2530() {
        return sysstatAoct2530;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_AOCT_2530
     *
     * @param sysstatAoct2530 the value for SYSSTAT.SYSSTAT_AOCT_2530
     *
     * @mbg.generated
     */
    public void setSysstatAoct2530(String sysstatAoct2530) {
        this.sysstatAoct2530 = sysstatAoct2530;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_AOCT_2540
     *
     * @return the value of SYSSTAT.SYSSTAT_AOCT_2540
     *
     * @mbg.generated
     */
    public String getSysstatAoct2540() {
        return sysstatAoct2540;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_AOCT_2540
     *
     * @param sysstatAoct2540 the value for SYSSTAT.SYSSTAT_AOCT_2540
     *
     * @mbg.generated
     */
    public void setSysstatAoct2540(String sysstatAoct2540) {
        this.sysstatAoct2540 = sysstatAoct2540;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_AOCT_2550
     *
     * @return the value of SYSSTAT.SYSSTAT_AOCT_2550
     *
     * @mbg.generated
     */
    public String getSysstatAoct2550() {
        return sysstatAoct2550;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_AOCT_2550
     *
     * @param sysstatAoct2550 the value for SYSSTAT.SYSSTAT_AOCT_2550
     *
     * @mbg.generated
     */
    public void setSysstatAoct2550(String sysstatAoct2550) {
        this.sysstatAoct2550 = sysstatAoct2550;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_AOCT_2560
     *
     * @return the value of SYSSTAT.SYSSTAT_AOCT_2560
     *
     * @mbg.generated
     */
    public String getSysstatAoct2560() {
        return sysstatAoct2560;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_AOCT_2560
     *
     * @param sysstatAoct2560 the value for SYSSTAT.SYSSTAT_AOCT_2560
     *
     * @mbg.generated
     */
    public void setSysstatAoct2560(String sysstatAoct2560) {
        this.sysstatAoct2560 = sysstatAoct2560;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_AOCT_7100
     *
     * @return the value of SYSSTAT.SYSSTAT_AOCT_7100
     *
     * @mbg.generated
     */
    public String getSysstatAoct7100() {
        return sysstatAoct7100;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_AOCT_7100
     *
     * @param sysstatAoct7100 the value for SYSSTAT.SYSSTAT_AOCT_7100
     *
     * @mbg.generated
     */
    public void setSysstatAoct7100(String sysstatAoct7100) {
        this.sysstatAoct7100 = sysstatAoct7100;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_AOCT_1000
     *
     * @return the value of SYSSTAT.SYSSTAT_AOCT_1000
     *
     * @mbg.generated
     */
    public String getSysstatAoct1000() {
        return sysstatAoct1000;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_AOCT_1000
     *
     * @param sysstatAoct1000 the value for SYSSTAT.SYSSTAT_AOCT_1000
     *
     * @mbg.generated
     */
    public void setSysstatAoct1000(String sysstatAoct1000) {
        this.sysstatAoct1000 = sysstatAoct1000;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_AOCT_1100
     *
     * @return the value of SYSSTAT.SYSSTAT_AOCT_1100
     *
     * @mbg.generated
     */
    public String getSysstatAoct1100() {
        return sysstatAoct1100;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_AOCT_1100
     *
     * @param sysstatAoct1100 the value for SYSSTAT.SYSSTAT_AOCT_1100
     *
     * @mbg.generated
     */
    public void setSysstatAoct1100(String sysstatAoct1100) {
        this.sysstatAoct1100 = sysstatAoct1100;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_AOCT_1200
     *
     * @return the value of SYSSTAT.SYSSTAT_AOCT_1200
     *
     * @mbg.generated
     */
    public String getSysstatAoct1200() {
        return sysstatAoct1200;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_AOCT_1200
     *
     * @param sysstatAoct1200 the value for SYSSTAT.SYSSTAT_AOCT_1200
     *
     * @mbg.generated
     */
    public void setSysstatAoct1200(String sysstatAoct1200) {
        this.sysstatAoct1200 = sysstatAoct1200;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_AOCT_1300
     *
     * @return the value of SYSSTAT.SYSSTAT_AOCT_1300
     *
     * @mbg.generated
     */
    public String getSysstatAoct1300() {
        return sysstatAoct1300;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_AOCT_1300
     *
     * @param sysstatAoct1300 the value for SYSSTAT.SYSSTAT_AOCT_1300
     *
     * @mbg.generated
     */
    public void setSysstatAoct1300(String sysstatAoct1300) {
        this.sysstatAoct1300 = sysstatAoct1300;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_AOCT_1400
     *
     * @return the value of SYSSTAT.SYSSTAT_AOCT_1400
     *
     * @mbg.generated
     */
    public String getSysstatAoct1400() {
        return sysstatAoct1400;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_AOCT_1400
     *
     * @param sysstatAoct1400 the value for SYSSTAT.SYSSTAT_AOCT_1400
     *
     * @mbg.generated
     */
    public void setSysstatAoct1400(String sysstatAoct1400) {
        this.sysstatAoct1400 = sysstatAoct1400;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_MBOCT
     *
     * @return the value of SYSSTAT.SYSSTAT_MBOCT
     *
     * @mbg.generated
     */
    public String getSysstatMboct() {
        return sysstatMboct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_MBOCT
     *
     * @param sysstatMboct the value for SYSSTAT.SYSSTAT_MBOCT
     *
     * @mbg.generated
     */
    public void setSysstatMboct(String sysstatMboct) {
        this.sysstatMboct = sysstatMboct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_MBACT_2000
     *
     * @return the value of SYSSTAT.SYSSTAT_MBACT_2000
     *
     * @mbg.generated
     */
    public String getSysstatMbact2000() {
        return sysstatMbact2000;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_MBACT_2000
     *
     * @param sysstatMbact2000 the value for SYSSTAT.SYSSTAT_MBACT_2000
     *
     * @mbg.generated
     */
    public void setSysstatMbact2000(String sysstatMbact2000) {
        this.sysstatMbact2000 = sysstatMbact2000;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_MBACT_2200
     *
     * @return the value of SYSSTAT.SYSSTAT_MBACT_2200
     *
     * @mbg.generated
     */
    public String getSysstatMbact2200() {
        return sysstatMbact2200;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_MBACT_2200
     *
     * @param sysstatMbact2200 the value for SYSSTAT.SYSSTAT_MBACT_2200
     *
     * @mbg.generated
     */
    public void setSysstatMbact2200(String sysstatMbact2200) {
        this.sysstatMbact2200 = sysstatMbact2200;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_MBACT_2500
     *
     * @return the value of SYSSTAT.SYSSTAT_MBACT_2500
     *
     * @mbg.generated
     */
    public String getSysstatMbact2500() {
        return sysstatMbact2500;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_MBACT_2500
     *
     * @param sysstatMbact2500 the value for SYSSTAT.SYSSTAT_MBACT_2500
     *
     * @mbg.generated
     */
    public void setSysstatMbact2500(String sysstatMbact2500) {
        this.sysstatMbact2500 = sysstatMbact2500;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_MBACT_2510
     *
     * @return the value of SYSSTAT.SYSSTAT_MBACT_2510
     *
     * @mbg.generated
     */
    public String getSysstatMbact2510() {
        return sysstatMbact2510;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_MBACT_2510
     *
     * @param sysstatMbact2510 the value for SYSSTAT.SYSSTAT_MBACT_2510
     *
     * @mbg.generated
     */
    public void setSysstatMbact2510(String sysstatMbact2510) {
        this.sysstatMbact2510 = sysstatMbact2510;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_MBACT_2520
     *
     * @return the value of SYSSTAT.SYSSTAT_MBACT_2520
     *
     * @mbg.generated
     */
    public String getSysstatMbact2520() {
        return sysstatMbact2520;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_MBACT_2520
     *
     * @param sysstatMbact2520 the value for SYSSTAT.SYSSTAT_MBACT_2520
     *
     * @mbg.generated
     */
    public void setSysstatMbact2520(String sysstatMbact2520) {
        this.sysstatMbact2520 = sysstatMbact2520;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_MBACT_2530
     *
     * @return the value of SYSSTAT.SYSSTAT_MBACT_2530
     *
     * @mbg.generated
     */
    public String getSysstatMbact2530() {
        return sysstatMbact2530;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_MBACT_2530
     *
     * @param sysstatMbact2530 the value for SYSSTAT.SYSSTAT_MBACT_2530
     *
     * @mbg.generated
     */
    public void setSysstatMbact2530(String sysstatMbact2530) {
        this.sysstatMbact2530 = sysstatMbact2530;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_MBACT_2540
     *
     * @return the value of SYSSTAT.SYSSTAT_MBACT_2540
     *
     * @mbg.generated
     */
    public String getSysstatMbact2540() {
        return sysstatMbact2540;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_MBACT_2540
     *
     * @param sysstatMbact2540 the value for SYSSTAT.SYSSTAT_MBACT_2540
     *
     * @mbg.generated
     */
    public void setSysstatMbact2540(String sysstatMbact2540) {
        this.sysstatMbact2540 = sysstatMbact2540;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_MBACT_2550
     *
     * @return the value of SYSSTAT.SYSSTAT_MBACT_2550
     *
     * @mbg.generated
     */
    public String getSysstatMbact2550() {
        return sysstatMbact2550;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_MBACT_2550
     *
     * @param sysstatMbact2550 the value for SYSSTAT.SYSSTAT_MBACT_2550
     *
     * @mbg.generated
     */
    public void setSysstatMbact2550(String sysstatMbact2550) {
        this.sysstatMbact2550 = sysstatMbact2550;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_MBACT_2560
     *
     * @return the value of SYSSTAT.SYSSTAT_MBACT_2560
     *
     * @mbg.generated
     */
    public String getSysstatMbact2560() {
        return sysstatMbact2560;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_MBACT_2560
     *
     * @param sysstatMbact2560 the value for SYSSTAT.SYSSTAT_MBACT_2560
     *
     * @mbg.generated
     */
    public void setSysstatMbact2560(String sysstatMbact2560) {
        this.sysstatMbact2560 = sysstatMbact2560;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_MBACT_7100
     *
     * @return the value of SYSSTAT.SYSSTAT_MBACT_7100
     *
     * @mbg.generated
     */
    public String getSysstatMbact7100() {
        return sysstatMbact7100;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_MBACT_7100
     *
     * @param sysstatMbact7100 the value for SYSSTAT.SYSSTAT_MBACT_7100
     *
     * @mbg.generated
     */
    public void setSysstatMbact7100(String sysstatMbact7100) {
        this.sysstatMbact7100 = sysstatMbact7100;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_MBACT_1000
     *
     * @return the value of SYSSTAT.SYSSTAT_MBACT_1000
     *
     * @mbg.generated
     */
    public String getSysstatMbact1000() {
        return sysstatMbact1000;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_MBACT_1000
     *
     * @param sysstatMbact1000 the value for SYSSTAT.SYSSTAT_MBACT_1000
     *
     * @mbg.generated
     */
    public void setSysstatMbact1000(String sysstatMbact1000) {
        this.sysstatMbact1000 = sysstatMbact1000;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_MBACT_1100
     *
     * @return the value of SYSSTAT.SYSSTAT_MBACT_1100
     *
     * @mbg.generated
     */
    public String getSysstatMbact1100() {
        return sysstatMbact1100;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_MBACT_1100
     *
     * @param sysstatMbact1100 the value for SYSSTAT.SYSSTAT_MBACT_1100
     *
     * @mbg.generated
     */
    public void setSysstatMbact1100(String sysstatMbact1100) {
        this.sysstatMbact1100 = sysstatMbact1100;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_MBACT_1200
     *
     * @return the value of SYSSTAT.SYSSTAT_MBACT_1200
     *
     * @mbg.generated
     */
    public String getSysstatMbact1200() {
        return sysstatMbact1200;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_MBACT_1200
     *
     * @param sysstatMbact1200 the value for SYSSTAT.SYSSTAT_MBACT_1200
     *
     * @mbg.generated
     */
    public void setSysstatMbact1200(String sysstatMbact1200) {
        this.sysstatMbact1200 = sysstatMbact1200;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_MBACT_1300
     *
     * @return the value of SYSSTAT.SYSSTAT_MBACT_1300
     *
     * @mbg.generated
     */
    public String getSysstatMbact1300() {
        return sysstatMbact1300;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_MBACT_1300
     *
     * @param sysstatMbact1300 the value for SYSSTAT.SYSSTAT_MBACT_1300
     *
     * @mbg.generated
     */
    public void setSysstatMbact1300(String sysstatMbact1300) {
        this.sysstatMbact1300 = sysstatMbact1300;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_MBACT_1400
     *
     * @return the value of SYSSTAT.SYSSTAT_MBACT_1400
     *
     * @mbg.generated
     */
    public String getSysstatMbact1400() {
        return sysstatMbact1400;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_MBACT_1400
     *
     * @param sysstatMbact1400 the value for SYSSTAT.SYSSTAT_MBACT_1400
     *
     * @mbg.generated
     */
    public void setSysstatMbact1400(String sysstatMbact1400) {
        this.sysstatMbact1400 = sysstatMbact1400;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_OPCKEYST
     *
     * @return the value of SYSSTAT.SYSSTAT_OPCKEYST
     *
     * @mbg.generated
     */
    public Short getSysstatOpckeyst() {
        return sysstatOpckeyst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_OPCKEYST
     *
     * @param sysstatOpckeyst the value for SYSSTAT.SYSSTAT_OPCKEYST
     *
     * @mbg.generated
     */
    public void setSysstatOpckeyst(Short sysstatOpckeyst) {
        this.sysstatOpckeyst = sysstatOpckeyst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_ATMKEYST
     *
     * @return the value of SYSSTAT.SYSSTAT_ATMKEYST
     *
     * @mbg.generated
     */
    public Short getSysstatAtmkeyst() {
        return sysstatAtmkeyst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_ATMKEYST
     *
     * @param sysstatAtmkeyst the value for SYSSTAT.SYSSTAT_ATMKEYST
     *
     * @mbg.generated
     */
    public void setSysstatAtmkeyst(Short sysstatAtmkeyst) {
        this.sysstatAtmkeyst = sysstatAtmkeyst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_RMKEYST
     *
     * @return the value of SYSSTAT.SYSSTAT_RMKEYST
     *
     * @mbg.generated
     */
    public Short getSysstatRmkeyst() {
        return sysstatRmkeyst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_RMKEYST
     *
     * @param sysstatRmkeyst the value for SYSSTAT.SYSSTAT_RMKEYST
     *
     * @mbg.generated
     */
    public void setSysstatRmkeyst(Short sysstatRmkeyst) {
        this.sysstatRmkeyst = sysstatRmkeyst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_PPKEYST
     *
     * @return the value of SYSSTAT.SYSSTAT_PPKEYST
     *
     * @mbg.generated
     */
    public Short getSysstatPpkeyst() {
        return sysstatPpkeyst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_PPKEYST
     *
     * @param sysstatPpkeyst the value for SYSSTAT.SYSSTAT_PPKEYST
     *
     * @mbg.generated
     */
    public void setSysstatPpkeyst(Short sysstatPpkeyst) {
        this.sysstatPpkeyst = sysstatPpkeyst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_3ENCKEYST
     *
     * @return the value of SYSSTAT.SYSSTAT_3ENCKEYST
     *
     * @mbg.generated
     */
    public Short getSysstat3enckeyst() {
        return sysstat3enckeyst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_3ENCKEYST
     *
     * @param sysstat3enckeyst the value for SYSSTAT.SYSSTAT_3ENCKEYST
     *
     * @mbg.generated
     */
    public void setSysstat3enckeyst(Short sysstat3enckeyst) {
        this.sysstat3enckeyst = sysstat3enckeyst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_CBS
     *
     * @return the value of SYSSTAT.SYSSTAT_CBS
     *
     * @mbg.generated
     */
    public Short getSysstatCbs() {
        return sysstatCbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_CBS
     *
     * @param sysstatCbs the value for SYSSTAT.SYSSTAT_CBS
     *
     * @mbg.generated
     */
    public void setSysstatCbs(Short sysstatCbs) {
        this.sysstatCbs = sysstatCbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.UPDATE_USERID
     *
     * @return the value of SYSSTAT.UPDATE_USERID
     *
     * @mbg.generated
     */
    public Integer getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.UPDATE_USERID
     *
     * @param updateUserid the value for SYSSTAT.UPDATE_USERID
     *
     * @mbg.generated
     */
    public void setUpdateUserid(Integer updateUserid) {
        this.updateUserid = updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.UPDATE_TIME
     *
     * @return the value of SYSSTAT.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.UPDATE_TIME
     *
     * @param updateTime the value for SYSSTAT.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_AOCT_7300
     *
     * @return the value of SYSSTAT.SYSSTAT_AOCT_7300
     *
     * @mbg.generated
     */
    public String getSysstatAoct7300() {
        return sysstatAoct7300;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_AOCT_7300
     *
     * @param sysstatAoct7300 the value for SYSSTAT.SYSSTAT_AOCT_7300
     *
     * @mbg.generated
     */
    public void setSysstatAoct7300(String sysstatAoct7300) {
        this.sysstatAoct7300 = sysstatAoct7300;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_MBACT_7300
     *
     * @return the value of SYSSTAT.SYSSTAT_MBACT_7300
     *
     * @mbg.generated
     */
    public String getSysstatMbact7300() {
        return sysstatMbact7300;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_MBACT_7300
     *
     * @param sysstatMbact7300 the value for SYSSTAT.SYSSTAT_MBACT_7300
     *
     * @mbg.generated
     */
    public void setSysstatMbact7300(String sysstatMbact7300) {
        this.sysstatMbact7300 = sysstatMbact7300;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_T24_TWN
     *
     * @return the value of SYSSTAT.SYSSTAT_T24_TWN
     *
     * @mbg.generated
     */
    public Short getSysstatT24Twn() {
        return sysstatT24Twn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_T24_TWN
     *
     * @param sysstatT24Twn the value for SYSSTAT.SYSSTAT_T24_TWN
     *
     * @mbg.generated
     */
    public void setSysstatT24Twn(Short sysstatT24Twn) {
        this.sysstatT24Twn = sysstatT24Twn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_AOCT_2570
     *
     * @return the value of SYSSTAT.SYSSTAT_AOCT_2570
     *
     * @mbg.generated
     */
    public String getSysstatAoct2570() {
        return sysstatAoct2570;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_AOCT_2570
     *
     * @param sysstatAoct2570 the value for SYSSTAT.SYSSTAT_AOCT_2570
     *
     * @mbg.generated
     */
    public void setSysstatAoct2570(String sysstatAoct2570) {
        this.sysstatAoct2570 = sysstatAoct2570;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_MBACT_2570
     *
     * @return the value of SYSSTAT.SYSSTAT_MBACT_2570
     *
     * @mbg.generated
     */
    public String getSysstatMbact2570() {
        return sysstatMbact2570;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_MBACT_2570
     *
     * @param sysstatMbact2570 the value for SYSSTAT.SYSSTAT_MBACT_2570
     *
     * @mbg.generated
     */
    public void setSysstatMbact2570(String sysstatMbact2570) {
        this.sysstatMbact2570 = sysstatMbact2570;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_KEYBLOCKST
     *
     * @return the value of SYSSTAT.SYSSTAT_KEYBLOCKST
     *
     * @mbg.generated
     */
    public Short getSysstatKeyblockst() {
        return sysstatKeyblockst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_KEYBLOCKST
     *
     * @param sysstatKeyblockst the value for SYSSTAT.SYSSTAT_KEYBLOCKST
     *
     * @mbg.generated
     */
    public void setSysstatKeyblockst(Short sysstatKeyblockst) {
        this.sysstatKeyblockst = sysstatKeyblockst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_KEYDIV
     *
     * @return the value of SYSSTAT.SYSSTAT_KEYDIV
     *
     * @mbg.generated
     */
    public Short getSysstatKeydiv() {
        return sysstatKeydiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_KEYDIV
     *
     * @param sysstatKeydiv the value for SYSSTAT.SYSSTAT_KEYDIV
     *
     * @mbg.generated
     */
    public void setSysstatKeydiv(Short sysstatKeydiv) {
        this.sysstatKeydiv = sysstatKeydiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_CHECKVALUE
     *
     * @return the value of SYSSTAT.SYSSTAT_CHECKVALUE
     *
     * @mbg.generated
     */
    public String getSysstatCheckvalue() {
        return sysstatCheckvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_CHECKVALUE
     *
     * @param sysstatCheckvalue the value for SYSSTAT.SYSSTAT_CHECKVALUE
     *
     * @mbg.generated
     */
    public void setSysstatCheckvalue(String sysstatCheckvalue) {
        this.sysstatCheckvalue = sysstatCheckvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_FCS
     *
     * @return the value of SYSSTAT.SYSSTAT_FCS
     *
     * @mbg.generated
     */
    public Short getSysstatFcs() {
        return sysstatFcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_FCS
     *
     * @param sysstatFcs the value for SYSSTAT.SYSSTAT_FCS
     *
     * @mbg.generated
     */
    public void setSysstatFcs(Short sysstatFcs) {
        this.sysstatFcs = sysstatFcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_CREDIT
     *
     * @return the value of SYSSTAT.SYSSTAT_CREDIT
     *
     * @mbg.generated
     */
    public Short getSysstatCredit() {
        return sysstatCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_CREDIT
     *
     * @param sysstatCredit the value for SYSSTAT.SYSSTAT_CREDIT
     *
     * @mbg.generated
     */
    public void setSysstatCredit(Short sysstatCredit) {
        this.sysstatCredit = sysstatCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_MTP
     *
     * @return the value of SYSSTAT.SYSSTAT_MTP
     *
     * @mbg.generated
     */
    public Short getSysstatMtp() {
        return sysstatMtp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_MTP
     *
     * @param sysstatMtp the value for SYSSTAT.SYSSTAT_MTP
     *
     * @mbg.generated
     */
    public void setSysstatMtp(Short sysstatMtp) {
        this.sysstatMtp = sysstatMtp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSSTAT.SYSSTAT_TWMP
     *
     * @return the value of SYSSTAT.SYSSTAT_TWMP
     *
     * @mbg.generated
     */
    public Short getSysstatTwmp() {
        return sysstatTwmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSSTAT.SYSSTAT_TWMP
     *
     * @param sysstatTwmp the value for SYSSTAT.SYSSTAT_TWMP
     *
     * @mbg.generated
     */
    public void setSysstatTwmp(Short sysstatTwmp) {
        this.sysstatTwmp = sysstatTwmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSSTAT
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sysstatHbkno=").append(sysstatHbkno);
        sb.append(", sysstatFbkno=").append(sysstatFbkno);
        sb.append(", sysstatScbkno=").append(sysstatScbkno);
        sb.append(", sysstatLbsdyFisc=").append(sysstatLbsdyFisc);
        sb.append(", sysstatTbsdyFisc=").append(sysstatTbsdyFisc);
        sb.append(", sysstatNbsdyFisc=").append(sysstatNbsdyFisc);
        sb.append(", sysstatFopcsync=").append(sysstatFopcsync);
        sb.append(", sysstatTopcsync=").append(sysstatTopcsync);
        sb.append(", sysstatFcdsync=").append(sysstatFcdsync);
        sb.append(", sysstatTcdsync=").append(sysstatTcdsync);
        sb.append(", sysstatFrmsync=").append(sysstatFrmsync);
        sb.append(", sysstatTrmsync=").append(sysstatTrmsync);
        sb.append(", sysstatFppsync=").append(sysstatFppsync);
        sb.append(", sysstatTppsync=").append(sysstatTppsync);
        sb.append(", sysstatF3dessync=").append(sysstatF3dessync);
        sb.append(", sysstatT3dessync=").append(sysstatT3dessync);
        sb.append(", sysstatSoct=").append(sysstatSoct);
        sb.append(", sysstatAoct2000=").append(sysstatAoct2000);
        sb.append(", sysstatAoct2200=").append(sysstatAoct2200);
        sb.append(", sysstatAoct2500=").append(sysstatAoct2500);
        sb.append(", sysstatAoct2510=").append(sysstatAoct2510);
        sb.append(", sysstatAoct2520=").append(sysstatAoct2520);
        sb.append(", sysstatAoct2530=").append(sysstatAoct2530);
        sb.append(", sysstatAoct2540=").append(sysstatAoct2540);
        sb.append(", sysstatAoct2550=").append(sysstatAoct2550);
        sb.append(", sysstatAoct2560=").append(sysstatAoct2560);
        sb.append(", sysstatAoct7100=").append(sysstatAoct7100);
        sb.append(", sysstatAoct1000=").append(sysstatAoct1000);
        sb.append(", sysstatAoct1100=").append(sysstatAoct1100);
        sb.append(", sysstatAoct1200=").append(sysstatAoct1200);
        sb.append(", sysstatAoct1300=").append(sysstatAoct1300);
        sb.append(", sysstatAoct1400=").append(sysstatAoct1400);
        sb.append(", sysstatMboct=").append(sysstatMboct);
        sb.append(", sysstatMbact2000=").append(sysstatMbact2000);
        sb.append(", sysstatMbact2200=").append(sysstatMbact2200);
        sb.append(", sysstatMbact2500=").append(sysstatMbact2500);
        sb.append(", sysstatMbact2510=").append(sysstatMbact2510);
        sb.append(", sysstatMbact2520=").append(sysstatMbact2520);
        sb.append(", sysstatMbact2530=").append(sysstatMbact2530);
        sb.append(", sysstatMbact2540=").append(sysstatMbact2540);
        sb.append(", sysstatMbact2550=").append(sysstatMbact2550);
        sb.append(", sysstatMbact2560=").append(sysstatMbact2560);
        sb.append(", sysstatMbact7100=").append(sysstatMbact7100);
        sb.append(", sysstatMbact1000=").append(sysstatMbact1000);
        sb.append(", sysstatMbact1100=").append(sysstatMbact1100);
        sb.append(", sysstatMbact1200=").append(sysstatMbact1200);
        sb.append(", sysstatMbact1300=").append(sysstatMbact1300);
        sb.append(", sysstatMbact1400=").append(sysstatMbact1400);
        sb.append(", sysstatOpckeyst=").append(sysstatOpckeyst);
        sb.append(", sysstatAtmkeyst=").append(sysstatAtmkeyst);
        sb.append(", sysstatRmkeyst=").append(sysstatRmkeyst);
        sb.append(", sysstatPpkeyst=").append(sysstatPpkeyst);
        sb.append(", sysstat3enckeyst=").append(sysstat3enckeyst);
        sb.append(", sysstatCbs=").append(sysstatCbs);
        sb.append(", updateUserid=").append(updateUserid);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", sysstatAoct7300=").append(sysstatAoct7300);
        sb.append(", sysstatMbact7300=").append(sysstatMbact7300);
        sb.append(", sysstatT24Twn=").append(sysstatT24Twn);
        sb.append(", sysstatAoct2570=").append(sysstatAoct2570);
        sb.append(", sysstatMbact2570=").append(sysstatMbact2570);
        sb.append(", sysstatKeyblockst=").append(sysstatKeyblockst);
        sb.append(", sysstatKeydiv=").append(sysstatKeydiv);
        sb.append(", sysstatCheckvalue=").append(sysstatCheckvalue);
        sb.append(", sysstatFcs=").append(sysstatFcs);
        sb.append(", sysstatCredit=").append(sysstatCredit);
        sb.append(", sysstatMtp=").append(sysstatMtp);
        sb.append(", sysstatTwmp=").append(sysstatTwmp);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSSTAT
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Sysstat other = (Sysstat) that;
        return (this.getSysstatHbkno() == null ? other.getSysstatHbkno() == null : this.getSysstatHbkno().equals(other.getSysstatHbkno()))
            && (this.getSysstatFbkno() == null ? other.getSysstatFbkno() == null : this.getSysstatFbkno().equals(other.getSysstatFbkno()))
            && (this.getSysstatScbkno() == null ? other.getSysstatScbkno() == null : this.getSysstatScbkno().equals(other.getSysstatScbkno()))
            && (this.getSysstatLbsdyFisc() == null ? other.getSysstatLbsdyFisc() == null : this.getSysstatLbsdyFisc().equals(other.getSysstatLbsdyFisc()))
            && (this.getSysstatTbsdyFisc() == null ? other.getSysstatTbsdyFisc() == null : this.getSysstatTbsdyFisc().equals(other.getSysstatTbsdyFisc()))
            && (this.getSysstatNbsdyFisc() == null ? other.getSysstatNbsdyFisc() == null : this.getSysstatNbsdyFisc().equals(other.getSysstatNbsdyFisc()))
            && (this.getSysstatFopcsync() == null ? other.getSysstatFopcsync() == null : this.getSysstatFopcsync().equals(other.getSysstatFopcsync()))
            && (this.getSysstatTopcsync() == null ? other.getSysstatTopcsync() == null : this.getSysstatTopcsync().equals(other.getSysstatTopcsync()))
            && (this.getSysstatFcdsync() == null ? other.getSysstatFcdsync() == null : this.getSysstatFcdsync().equals(other.getSysstatFcdsync()))
            && (this.getSysstatTcdsync() == null ? other.getSysstatTcdsync() == null : this.getSysstatTcdsync().equals(other.getSysstatTcdsync()))
            && (this.getSysstatFrmsync() == null ? other.getSysstatFrmsync() == null : this.getSysstatFrmsync().equals(other.getSysstatFrmsync()))
            && (this.getSysstatTrmsync() == null ? other.getSysstatTrmsync() == null : this.getSysstatTrmsync().equals(other.getSysstatTrmsync()))
            && (this.getSysstatFppsync() == null ? other.getSysstatFppsync() == null : this.getSysstatFppsync().equals(other.getSysstatFppsync()))
            && (this.getSysstatTppsync() == null ? other.getSysstatTppsync() == null : this.getSysstatTppsync().equals(other.getSysstatTppsync()))
            && (this.getSysstatF3dessync() == null ? other.getSysstatF3dessync() == null : this.getSysstatF3dessync().equals(other.getSysstatF3dessync()))
            && (this.getSysstatT3dessync() == null ? other.getSysstatT3dessync() == null : this.getSysstatT3dessync().equals(other.getSysstatT3dessync()))
            && (this.getSysstatSoct() == null ? other.getSysstatSoct() == null : this.getSysstatSoct().equals(other.getSysstatSoct()))
            && (this.getSysstatAoct2000() == null ? other.getSysstatAoct2000() == null : this.getSysstatAoct2000().equals(other.getSysstatAoct2000()))
            && (this.getSysstatAoct2200() == null ? other.getSysstatAoct2200() == null : this.getSysstatAoct2200().equals(other.getSysstatAoct2200()))
            && (this.getSysstatAoct2500() == null ? other.getSysstatAoct2500() == null : this.getSysstatAoct2500().equals(other.getSysstatAoct2500()))
            && (this.getSysstatAoct2510() == null ? other.getSysstatAoct2510() == null : this.getSysstatAoct2510().equals(other.getSysstatAoct2510()))
            && (this.getSysstatAoct2520() == null ? other.getSysstatAoct2520() == null : this.getSysstatAoct2520().equals(other.getSysstatAoct2520()))
            && (this.getSysstatAoct2530() == null ? other.getSysstatAoct2530() == null : this.getSysstatAoct2530().equals(other.getSysstatAoct2530()))
            && (this.getSysstatAoct2540() == null ? other.getSysstatAoct2540() == null : this.getSysstatAoct2540().equals(other.getSysstatAoct2540()))
            && (this.getSysstatAoct2550() == null ? other.getSysstatAoct2550() == null : this.getSysstatAoct2550().equals(other.getSysstatAoct2550()))
            && (this.getSysstatAoct2560() == null ? other.getSysstatAoct2560() == null : this.getSysstatAoct2560().equals(other.getSysstatAoct2560()))
            && (this.getSysstatAoct7100() == null ? other.getSysstatAoct7100() == null : this.getSysstatAoct7100().equals(other.getSysstatAoct7100()))
            && (this.getSysstatAoct1000() == null ? other.getSysstatAoct1000() == null : this.getSysstatAoct1000().equals(other.getSysstatAoct1000()))
            && (this.getSysstatAoct1100() == null ? other.getSysstatAoct1100() == null : this.getSysstatAoct1100().equals(other.getSysstatAoct1100()))
            && (this.getSysstatAoct1200() == null ? other.getSysstatAoct1200() == null : this.getSysstatAoct1200().equals(other.getSysstatAoct1200()))
            && (this.getSysstatAoct1300() == null ? other.getSysstatAoct1300() == null : this.getSysstatAoct1300().equals(other.getSysstatAoct1300()))
            && (this.getSysstatAoct1400() == null ? other.getSysstatAoct1400() == null : this.getSysstatAoct1400().equals(other.getSysstatAoct1400()))
            && (this.getSysstatMboct() == null ? other.getSysstatMboct() == null : this.getSysstatMboct().equals(other.getSysstatMboct()))
            && (this.getSysstatMbact2000() == null ? other.getSysstatMbact2000() == null : this.getSysstatMbact2000().equals(other.getSysstatMbact2000()))
            && (this.getSysstatMbact2200() == null ? other.getSysstatMbact2200() == null : this.getSysstatMbact2200().equals(other.getSysstatMbact2200()))
            && (this.getSysstatMbact2500() == null ? other.getSysstatMbact2500() == null : this.getSysstatMbact2500().equals(other.getSysstatMbact2500()))
            && (this.getSysstatMbact2510() == null ? other.getSysstatMbact2510() == null : this.getSysstatMbact2510().equals(other.getSysstatMbact2510()))
            && (this.getSysstatMbact2520() == null ? other.getSysstatMbact2520() == null : this.getSysstatMbact2520().equals(other.getSysstatMbact2520()))
            && (this.getSysstatMbact2530() == null ? other.getSysstatMbact2530() == null : this.getSysstatMbact2530().equals(other.getSysstatMbact2530()))
            && (this.getSysstatMbact2540() == null ? other.getSysstatMbact2540() == null : this.getSysstatMbact2540().equals(other.getSysstatMbact2540()))
            && (this.getSysstatMbact2550() == null ? other.getSysstatMbact2550() == null : this.getSysstatMbact2550().equals(other.getSysstatMbact2550()))
            && (this.getSysstatMbact2560() == null ? other.getSysstatMbact2560() == null : this.getSysstatMbact2560().equals(other.getSysstatMbact2560()))
            && (this.getSysstatMbact7100() == null ? other.getSysstatMbact7100() == null : this.getSysstatMbact7100().equals(other.getSysstatMbact7100()))
            && (this.getSysstatMbact1000() == null ? other.getSysstatMbact1000() == null : this.getSysstatMbact1000().equals(other.getSysstatMbact1000()))
            && (this.getSysstatMbact1100() == null ? other.getSysstatMbact1100() == null : this.getSysstatMbact1100().equals(other.getSysstatMbact1100()))
            && (this.getSysstatMbact1200() == null ? other.getSysstatMbact1200() == null : this.getSysstatMbact1200().equals(other.getSysstatMbact1200()))
            && (this.getSysstatMbact1300() == null ? other.getSysstatMbact1300() == null : this.getSysstatMbact1300().equals(other.getSysstatMbact1300()))
            && (this.getSysstatMbact1400() == null ? other.getSysstatMbact1400() == null : this.getSysstatMbact1400().equals(other.getSysstatMbact1400()))
            && (this.getSysstatOpckeyst() == null ? other.getSysstatOpckeyst() == null : this.getSysstatOpckeyst().equals(other.getSysstatOpckeyst()))
            && (this.getSysstatAtmkeyst() == null ? other.getSysstatAtmkeyst() == null : this.getSysstatAtmkeyst().equals(other.getSysstatAtmkeyst()))
            && (this.getSysstatRmkeyst() == null ? other.getSysstatRmkeyst() == null : this.getSysstatRmkeyst().equals(other.getSysstatRmkeyst()))
            && (this.getSysstatPpkeyst() == null ? other.getSysstatPpkeyst() == null : this.getSysstatPpkeyst().equals(other.getSysstatPpkeyst()))
            && (this.getSysstat3enckeyst() == null ? other.getSysstat3enckeyst() == null : this.getSysstat3enckeyst().equals(other.getSysstat3enckeyst()))
            && (this.getSysstatCbs() == null ? other.getSysstatCbs() == null : this.getSysstatCbs().equals(other.getSysstatCbs()))
            && (this.getUpdateUserid() == null ? other.getUpdateUserid() == null : this.getUpdateUserid().equals(other.getUpdateUserid()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getSysstatAoct7300() == null ? other.getSysstatAoct7300() == null : this.getSysstatAoct7300().equals(other.getSysstatAoct7300()))
            && (this.getSysstatMbact7300() == null ? other.getSysstatMbact7300() == null : this.getSysstatMbact7300().equals(other.getSysstatMbact7300()))
            && (this.getSysstatT24Twn() == null ? other.getSysstatT24Twn() == null : this.getSysstatT24Twn().equals(other.getSysstatT24Twn()))
            && (this.getSysstatAoct2570() == null ? other.getSysstatAoct2570() == null : this.getSysstatAoct2570().equals(other.getSysstatAoct2570()))
            && (this.getSysstatMbact2570() == null ? other.getSysstatMbact2570() == null : this.getSysstatMbact2570().equals(other.getSysstatMbact2570()))
            && (this.getSysstatKeyblockst() == null ? other.getSysstatKeyblockst() == null : this.getSysstatKeyblockst().equals(other.getSysstatKeyblockst()))
            && (this.getSysstatKeydiv() == null ? other.getSysstatKeydiv() == null : this.getSysstatKeydiv().equals(other.getSysstatKeydiv()))
            && (this.getSysstatCheckvalue() == null ? other.getSysstatCheckvalue() == null : this.getSysstatCheckvalue().equals(other.getSysstatCheckvalue()))
            && (this.getSysstatFcs() == null ? other.getSysstatFcs() == null : this.getSysstatFcs().equals(other.getSysstatFcs()))
            && (this.getSysstatCredit() == null ? other.getSysstatCredit() == null : this.getSysstatCredit().equals(other.getSysstatCredit()))
            && (this.getSysstatMtp() == null ? other.getSysstatMtp() == null : this.getSysstatMtp().equals(other.getSysstatMtp()))
            && (this.getSysstatTwmp() == null ? other.getSysstatTwmp() == null : this.getSysstatTwmp().equals(other.getSysstatTwmp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSSTAT
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + ((getSysstatHbkno() == null) ? 0 : getSysstatHbkno().hashCode());
        result = 31 * result + ((getSysstatFbkno() == null) ? 0 : getSysstatFbkno().hashCode());
        result = 31 * result + ((getSysstatScbkno() == null) ? 0 : getSysstatScbkno().hashCode());
        result = 31 * result + ((getSysstatLbsdyFisc() == null) ? 0 : getSysstatLbsdyFisc().hashCode());
        result = 31 * result + ((getSysstatTbsdyFisc() == null) ? 0 : getSysstatTbsdyFisc().hashCode());
        result = 31 * result + ((getSysstatNbsdyFisc() == null) ? 0 : getSysstatNbsdyFisc().hashCode());
        result = 31 * result + ((getSysstatFopcsync() == null) ? 0 : getSysstatFopcsync().hashCode());
        result = 31 * result + ((getSysstatTopcsync() == null) ? 0 : getSysstatTopcsync().hashCode());
        result = 31 * result + ((getSysstatFcdsync() == null) ? 0 : getSysstatFcdsync().hashCode());
        result = 31 * result + ((getSysstatTcdsync() == null) ? 0 : getSysstatTcdsync().hashCode());
        result = 31 * result + ((getSysstatFrmsync() == null) ? 0 : getSysstatFrmsync().hashCode());
        result = 31 * result + ((getSysstatTrmsync() == null) ? 0 : getSysstatTrmsync().hashCode());
        result = 31 * result + ((getSysstatFppsync() == null) ? 0 : getSysstatFppsync().hashCode());
        result = 31 * result + ((getSysstatTppsync() == null) ? 0 : getSysstatTppsync().hashCode());
        result = 31 * result + ((getSysstatF3dessync() == null) ? 0 : getSysstatF3dessync().hashCode());
        result = 31 * result + ((getSysstatT3dessync() == null) ? 0 : getSysstatT3dessync().hashCode());
        result = 31 * result + ((getSysstatSoct() == null) ? 0 : getSysstatSoct().hashCode());
        result = 31 * result + ((getSysstatAoct2000() == null) ? 0 : getSysstatAoct2000().hashCode());
        result = 31 * result + ((getSysstatAoct2200() == null) ? 0 : getSysstatAoct2200().hashCode());
        result = 31 * result + ((getSysstatAoct2500() == null) ? 0 : getSysstatAoct2500().hashCode());
        result = 31 * result + ((getSysstatAoct2510() == null) ? 0 : getSysstatAoct2510().hashCode());
        result = 31 * result + ((getSysstatAoct2520() == null) ? 0 : getSysstatAoct2520().hashCode());
        result = 31 * result + ((getSysstatAoct2530() == null) ? 0 : getSysstatAoct2530().hashCode());
        result = 31 * result + ((getSysstatAoct2540() == null) ? 0 : getSysstatAoct2540().hashCode());
        result = 31 * result + ((getSysstatAoct2550() == null) ? 0 : getSysstatAoct2550().hashCode());
        result = 31 * result + ((getSysstatAoct2560() == null) ? 0 : getSysstatAoct2560().hashCode());
        result = 31 * result + ((getSysstatAoct7100() == null) ? 0 : getSysstatAoct7100().hashCode());
        result = 31 * result + ((getSysstatAoct1000() == null) ? 0 : getSysstatAoct1000().hashCode());
        result = 31 * result + ((getSysstatAoct1100() == null) ? 0 : getSysstatAoct1100().hashCode());
        result = 31 * result + ((getSysstatAoct1200() == null) ? 0 : getSysstatAoct1200().hashCode());
        result = 31 * result + ((getSysstatAoct1300() == null) ? 0 : getSysstatAoct1300().hashCode());
        result = 31 * result + ((getSysstatAoct1400() == null) ? 0 : getSysstatAoct1400().hashCode());
        result = 31 * result + ((getSysstatMboct() == null) ? 0 : getSysstatMboct().hashCode());
        result = 31 * result + ((getSysstatMbact2000() == null) ? 0 : getSysstatMbact2000().hashCode());
        result = 31 * result + ((getSysstatMbact2200() == null) ? 0 : getSysstatMbact2200().hashCode());
        result = 31 * result + ((getSysstatMbact2500() == null) ? 0 : getSysstatMbact2500().hashCode());
        result = 31 * result + ((getSysstatMbact2510() == null) ? 0 : getSysstatMbact2510().hashCode());
        result = 31 * result + ((getSysstatMbact2520() == null) ? 0 : getSysstatMbact2520().hashCode());
        result = 31 * result + ((getSysstatMbact2530() == null) ? 0 : getSysstatMbact2530().hashCode());
        result = 31 * result + ((getSysstatMbact2540() == null) ? 0 : getSysstatMbact2540().hashCode());
        result = 31 * result + ((getSysstatMbact2550() == null) ? 0 : getSysstatMbact2550().hashCode());
        result = 31 * result + ((getSysstatMbact2560() == null) ? 0 : getSysstatMbact2560().hashCode());
        result = 31 * result + ((getSysstatMbact7100() == null) ? 0 : getSysstatMbact7100().hashCode());
        result = 31 * result + ((getSysstatMbact1000() == null) ? 0 : getSysstatMbact1000().hashCode());
        result = 31 * result + ((getSysstatMbact1100() == null) ? 0 : getSysstatMbact1100().hashCode());
        result = 31 * result + ((getSysstatMbact1200() == null) ? 0 : getSysstatMbact1200().hashCode());
        result = 31 * result + ((getSysstatMbact1300() == null) ? 0 : getSysstatMbact1300().hashCode());
        result = 31 * result + ((getSysstatMbact1400() == null) ? 0 : getSysstatMbact1400().hashCode());
        result = 31 * result + ((getSysstatOpckeyst() == null) ? 0 : getSysstatOpckeyst().hashCode());
        result = 31 * result + ((getSysstatAtmkeyst() == null) ? 0 : getSysstatAtmkeyst().hashCode());
        result = 31 * result + ((getSysstatRmkeyst() == null) ? 0 : getSysstatRmkeyst().hashCode());
        result = 31 * result + ((getSysstatPpkeyst() == null) ? 0 : getSysstatPpkeyst().hashCode());
        result = 31 * result + ((getSysstat3enckeyst() == null) ? 0 : getSysstat3enckeyst().hashCode());
        result = 31 * result + ((getSysstatCbs() == null) ? 0 : getSysstatCbs().hashCode());
        result = 31 * result + ((getUpdateUserid() == null) ? 0 : getUpdateUserid().hashCode());
        result = 31 * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = 31 * result + ((getSysstatAoct7300() == null) ? 0 : getSysstatAoct7300().hashCode());
        result = 31 * result + ((getSysstatMbact7300() == null) ? 0 : getSysstatMbact7300().hashCode());
        result = 31 * result + ((getSysstatT24Twn() == null) ? 0 : getSysstatT24Twn().hashCode());
        result = 31 * result + ((getSysstatAoct2570() == null) ? 0 : getSysstatAoct2570().hashCode());
        result = 31 * result + ((getSysstatMbact2570() == null) ? 0 : getSysstatMbact2570().hashCode());
        result = 31 * result + ((getSysstatKeyblockst() == null) ? 0 : getSysstatKeyblockst().hashCode());
        result = 31 * result + ((getSysstatKeydiv() == null) ? 0 : getSysstatKeydiv().hashCode());
        result = 31 * result + ((getSysstatCheckvalue() == null) ? 0 : getSysstatCheckvalue().hashCode());
        result = 31 * result + ((getSysstatFcs() == null) ? 0 : getSysstatFcs().hashCode());
        result = 31 * result + ((getSysstatCredit() == null) ? 0 : getSysstatCredit().hashCode());
        result = 31 * result + ((getSysstatMtp() == null) ? 0 : getSysstatMtp().hashCode());
        result = 31 * result + ((getSysstatTwmp() == null) ? 0 : getSysstatTwmp().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSSTAT
     * 
     * @mbg.generated
     */
    @Override
    public String fieldsToXml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<SYSSTAT_HBKNO>").append(this.sysstatHbkno).append("</SYSSTAT_HBKNO>");
        sb.append("<SYSSTAT_FBKNO>").append(this.sysstatFbkno).append("</SYSSTAT_FBKNO>");
        sb.append("<SYSSTAT_SCBKNO>").append(this.sysstatScbkno).append("</SYSSTAT_SCBKNO>");
        sb.append("<SYSSTAT_LBSDY_FISC>").append(this.sysstatLbsdyFisc).append("</SYSSTAT_LBSDY_FISC>");
        sb.append("<SYSSTAT_TBSDY_FISC>").append(this.sysstatTbsdyFisc).append("</SYSSTAT_TBSDY_FISC>");
        sb.append("<SYSSTAT_NBSDY_FISC>").append(this.sysstatNbsdyFisc).append("</SYSSTAT_NBSDY_FISC>");
        sb.append("<SYSSTAT_FOPCSYNC>").append(this.sysstatFopcsync).append("</SYSSTAT_FOPCSYNC>");
        sb.append("<SYSSTAT_TOPCSYNC>").append(this.sysstatTopcsync).append("</SYSSTAT_TOPCSYNC>");
        sb.append("<SYSSTAT_FCDSYNC>").append(this.sysstatFcdsync).append("</SYSSTAT_FCDSYNC>");
        sb.append("<SYSSTAT_TCDSYNC>").append(this.sysstatTcdsync).append("</SYSSTAT_TCDSYNC>");
        sb.append("<SYSSTAT_FRMSYNC>").append(this.sysstatFrmsync).append("</SYSSTAT_FRMSYNC>");
        sb.append("<SYSSTAT_TRMSYNC>").append(this.sysstatTrmsync).append("</SYSSTAT_TRMSYNC>");
        sb.append("<SYSSTAT_FPPSYNC>").append(this.sysstatFppsync).append("</SYSSTAT_FPPSYNC>");
        sb.append("<SYSSTAT_TPPSYNC>").append(this.sysstatTppsync).append("</SYSSTAT_TPPSYNC>");
        sb.append("<SYSSTAT_F3DESSYNC>").append(this.sysstatF3dessync).append("</SYSSTAT_F3DESSYNC>");
        sb.append("<SYSSTAT_T3DESSYNC>").append(this.sysstatT3dessync).append("</SYSSTAT_T3DESSYNC>");
        sb.append("<SYSSTAT_SOCT>").append(this.sysstatSoct).append("</SYSSTAT_SOCT>");
        sb.append("<SYSSTAT_AOCT_2000>").append(this.sysstatAoct2000).append("</SYSSTAT_AOCT_2000>");
        sb.append("<SYSSTAT_AOCT_2200>").append(this.sysstatAoct2200).append("</SYSSTAT_AOCT_2200>");
        sb.append("<SYSSTAT_AOCT_2500>").append(this.sysstatAoct2500).append("</SYSSTAT_AOCT_2500>");
        sb.append("<SYSSTAT_AOCT_2510>").append(this.sysstatAoct2510).append("</SYSSTAT_AOCT_2510>");
        sb.append("<SYSSTAT_AOCT_2520>").append(this.sysstatAoct2520).append("</SYSSTAT_AOCT_2520>");
        sb.append("<SYSSTAT_AOCT_2530>").append(this.sysstatAoct2530).append("</SYSSTAT_AOCT_2530>");
        sb.append("<SYSSTAT_AOCT_2540>").append(this.sysstatAoct2540).append("</SYSSTAT_AOCT_2540>");
        sb.append("<SYSSTAT_AOCT_2550>").append(this.sysstatAoct2550).append("</SYSSTAT_AOCT_2550>");
        sb.append("<SYSSTAT_AOCT_2560>").append(this.sysstatAoct2560).append("</SYSSTAT_AOCT_2560>");
        sb.append("<SYSSTAT_AOCT_7100>").append(this.sysstatAoct7100).append("</SYSSTAT_AOCT_7100>");
        sb.append("<SYSSTAT_AOCT_1000>").append(this.sysstatAoct1000).append("</SYSSTAT_AOCT_1000>");
        sb.append("<SYSSTAT_AOCT_1100>").append(this.sysstatAoct1100).append("</SYSSTAT_AOCT_1100>");
        sb.append("<SYSSTAT_AOCT_1200>").append(this.sysstatAoct1200).append("</SYSSTAT_AOCT_1200>");
        sb.append("<SYSSTAT_AOCT_1300>").append(this.sysstatAoct1300).append("</SYSSTAT_AOCT_1300>");
        sb.append("<SYSSTAT_AOCT_1400>").append(this.sysstatAoct1400).append("</SYSSTAT_AOCT_1400>");
        sb.append("<SYSSTAT_MBOCT>").append(this.sysstatMboct).append("</SYSSTAT_MBOCT>");
        sb.append("<SYSSTAT_MBACT_2000>").append(this.sysstatMbact2000).append("</SYSSTAT_MBACT_2000>");
        sb.append("<SYSSTAT_MBACT_2200>").append(this.sysstatMbact2200).append("</SYSSTAT_MBACT_2200>");
        sb.append("<SYSSTAT_MBACT_2500>").append(this.sysstatMbact2500).append("</SYSSTAT_MBACT_2500>");
        sb.append("<SYSSTAT_MBACT_2510>").append(this.sysstatMbact2510).append("</SYSSTAT_MBACT_2510>");
        sb.append("<SYSSTAT_MBACT_2520>").append(this.sysstatMbact2520).append("</SYSSTAT_MBACT_2520>");
        sb.append("<SYSSTAT_MBACT_2530>").append(this.sysstatMbact2530).append("</SYSSTAT_MBACT_2530>");
        sb.append("<SYSSTAT_MBACT_2540>").append(this.sysstatMbact2540).append("</SYSSTAT_MBACT_2540>");
        sb.append("<SYSSTAT_MBACT_2550>").append(this.sysstatMbact2550).append("</SYSSTAT_MBACT_2550>");
        sb.append("<SYSSTAT_MBACT_2560>").append(this.sysstatMbact2560).append("</SYSSTAT_MBACT_2560>");
        sb.append("<SYSSTAT_MBACT_7100>").append(this.sysstatMbact7100).append("</SYSSTAT_MBACT_7100>");
        sb.append("<SYSSTAT_MBACT_1000>").append(this.sysstatMbact1000).append("</SYSSTAT_MBACT_1000>");
        sb.append("<SYSSTAT_MBACT_1100>").append(this.sysstatMbact1100).append("</SYSSTAT_MBACT_1100>");
        sb.append("<SYSSTAT_MBACT_1200>").append(this.sysstatMbact1200).append("</SYSSTAT_MBACT_1200>");
        sb.append("<SYSSTAT_MBACT_1300>").append(this.sysstatMbact1300).append("</SYSSTAT_MBACT_1300>");
        sb.append("<SYSSTAT_MBACT_1400>").append(this.sysstatMbact1400).append("</SYSSTAT_MBACT_1400>");
        sb.append("<SYSSTAT_OPCKEYST>").append(this.sysstatOpckeyst).append("</SYSSTAT_OPCKEYST>");
        sb.append("<SYSSTAT_ATMKEYST>").append(this.sysstatAtmkeyst).append("</SYSSTAT_ATMKEYST>");
        sb.append("<SYSSTAT_RMKEYST>").append(this.sysstatRmkeyst).append("</SYSSTAT_RMKEYST>");
        sb.append("<SYSSTAT_PPKEYST>").append(this.sysstatPpkeyst).append("</SYSSTAT_PPKEYST>");
        sb.append("<SYSSTAT_3ENCKEYST>").append(this.sysstat3enckeyst).append("</SYSSTAT_3ENCKEYST>");
        sb.append("<SYSSTAT_CBS>").append(this.sysstatCbs).append("</SYSSTAT_CBS>");
        sb.append("<UPDATE_USERID>").append(this.updateUserid).append("</UPDATE_USERID>");
        sb.append("<UPDATE_TIME>").append(this.updateTime).append("</UPDATE_TIME>");
        sb.append("<SYSSTAT_AOCT_7300>").append(this.sysstatAoct7300).append("</SYSSTAT_AOCT_7300>");
        sb.append("<SYSSTAT_MBACT_7300>").append(this.sysstatMbact7300).append("</SYSSTAT_MBACT_7300>");
        sb.append("<SYSSTAT_T24_TWN>").append(this.sysstatT24Twn).append("</SYSSTAT_T24_TWN>");
        sb.append("<SYSSTAT_AOCT_2570>").append(this.sysstatAoct2570).append("</SYSSTAT_AOCT_2570>");
        sb.append("<SYSSTAT_MBACT_2570>").append(this.sysstatMbact2570).append("</SYSSTAT_MBACT_2570>");
        sb.append("<SYSSTAT_KEYBLOCKST>").append(this.sysstatKeyblockst).append("</SYSSTAT_KEYBLOCKST>");
        sb.append("<SYSSTAT_KEYDIV>").append(this.sysstatKeydiv).append("</SYSSTAT_KEYDIV>");
        sb.append("<SYSSTAT_CHECKVALUE>").append(this.sysstatCheckvalue).append("</SYSSTAT_CHECKVALUE>");
        sb.append("<SYSSTAT_FCS>").append(this.sysstatFcs).append("</SYSSTAT_FCS>");
        sb.append("<SYSSTAT_CREDIT>").append(this.sysstatCredit).append("</SYSSTAT_CREDIT>");
        sb.append("<SYSSTAT_MTP>").append(this.sysstatMtp).append("</SYSSTAT_MTP>");
        sb.append("<SYSSTAT_TWMP>").append(this.sysstatTwmp).append("</SYSSTAT_TWMP>");
        return sb.toString();
    }
}