package com.syscom.fep.mybatis.mbg;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;

import org.apache.commons.io.FileUtils;
import org.apache.commons.lang3.StringUtils;
import org.junit.jupiter.api.Test;

import com.syscom.fep.common.log.LogHelperFactory;
import com.syscom.fep.frmcommon.util.CleanPathUtil;

public class FeptxnSchemaGeneartor {
	@Test
	public void test() throws IOException {
		StringBuilder sb = new StringBuilder();
		String tableName = "";
		for (int i = 1; i <= 31; i++) {
			tableName = "FEPTXN" + StringUtils.leftPad(String.valueOf(i), 2, '0');
			sb.append("DROP TABLE \"" + tableName + "\";\r\n");
			sb.append("CREATE TABLE \"" + tableName + "\" (\r\n"
					+ "	\"FEPTXN_TX_DATE\" CHAR(8 OCTETS) NOT NULL , \r\n"
					+ "	\"FEPTXN_EJFNO\" INTEGER NOT NULL , \r\n"
					+ "	\"FEPTXN_TXSEQ\" VARCHAR(11 OCTETS) NOT NULL WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_CON_TXSEQ\" VARCHAR(11 OCTETS) NOT NULL WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_VIR_TXSEQ\" VARCHAR(11 OCTETS) NOT NULL WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_CON_VIR_TXSEQ\" VARCHAR(11 OCTETS) NOT NULL WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_TX_DATE_ATM\" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_ATM_SEQNO\" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_CON_ATM_SEQNO1\" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_CON_ATM_SEQNO2\" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_CBS_TX_CODE\" VARCHAR(10 OCTETS) , \r\n"
					+ "	\"FEPTXN_CBS_RRN\" VARCHAR(20 OCTETS) WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_EC_CBS_RRN\" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_STAN\" VARCHAR(7 OCTETS) NOT NULL WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_ORI_STAN\" VARCHAR(7 OCTETS) NOT NULL WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_TX_CUR_ACT\" CHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_TX_CUR\" CHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_BKNO\" CHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_ATMNO\" VARCHAR(8 OCTETS) , \r\n"
					+ "	\"FEPTXN_TX_TIME\" VARCHAR(6 OCTETS) NOT NULL WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_CON_TX_TIME\" VARCHAR(6 OCTETS) , \r\n"
					+ "	\"FEPTXN_TX_CODE\" CHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_CON_TX_CODE\" CHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_TBSDY_FISC\" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_TBSDY\" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_TBSDY_ACT\" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_MAJOR_ACTNO\" CHAR(16 OCTETS) , \r\n"
					+ "	\"FEPTXN_CARD_SEQ\" DECIMAL(4,0) , \r\n"
					+ "	\"FEPTXN_TRIN_BKNO\" CHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_TRIN_ACTNO\" CHAR(16 OCTETS) , \r\n"
					+ "	\"FEPTXN_TRIN_ACTNO_ACTUAL\" CHAR(16 OCTETS) , \r\n"
					+ "	\"FEPTXN_TRIN_KIND\" CHAR(1 OCTETS) WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_TROUT_BKNO\" CHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_TROUT_ACTNO\" CHAR(16 OCTETS) , \r\n"
					+ "	\"FEPTXN_TROUT_KIND\" CHAR(1 OCTETS) WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_TX_AMT_ACT\" DECIMAL(13,2) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_TX_AMT\" DECIMAL(14,2) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_CBS_RC\" VARCHAR(6 OCTETS) , \r\n"
					+ "	\"FEPTXN_ASC_RC\" VARCHAR(6 OCTETS) , \r\n"
					+ "	\"FEPTXN_EXCP_CODE\" VARCHAR(6 OCTETS) , \r\n"
					+ "	\"FEPTXN_CON_EXCP_CODE\" VARCHAR(6 OCTETS) , \r\n"
					+ "	\"FEPTXN_REPLY_CODE\" VARCHAR(6 OCTETS) , \r\n"
					+ "	\"FEPTXN_CON_REPLY_CODE\" VARCHAR(6 OCTETS) , \r\n"
					+ "	\"FEPTXN_ACC_TYPE\" DECIMAL(4,0) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_CLR_TYPE\" DECIMAL(4,0) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_NEED_SEND_CBS\" DECIMAL(4,0) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_ATMOD\" DECIMAL(4,0) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_BALA\" DECIMAL(13,2) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_BALB\" DECIMAL(13,2) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_CBS_TIMEOUT\" SMALLINT NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_ASC_TIMEOUT\" SMALLINT NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_FISC_FLAG\" SMALLINT NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_PENDING\" DECIMAL(4,0) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_REQ_RC\" CHAR(4 OCTETS) , \r\n"
					+ "	\"FEPTXN_REP_RC\" CHAR(4 OCTETS) , \r\n"
					+ "	\"FEPTXN_CON_RC\" CHAR(4 OCTETS) , \r\n"
					+ "	\"FEPTXN_AA_RC\" INTEGER NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_FISC_TIMEOUT\" SMALLINT NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_MSGFLOW\" CHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_SUBSYS\" DECIMAL(4,0) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_CHANNEL\" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_PCODE\" CHAR(4 OCTETS) , \r\n"
					+ "	\"FEPTXN_TRACE_EJFNO\" INTEGER NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_CHANNEL_EJFNO\" VARCHAR(50 OCTETS) , \r\n"
					+ "	\"FEPTXN_TXRUST\" CHAR(1 OCTETS) NOT NULL WITH DEFAULT '0' , \r\n"
					+ "	\"FEPTXN_TXNMODE\" DECIMAL(4,0) , \r\n"
					+ "	\"FEPTXN_FEE_CUR\" CHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_FEE_CUSTPAY_ACT\" DECIMAL(7,2) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_FEE_CUSTPAY\" DECIMAL(7,2) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_DES_BKNO\" CHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_TX_DATETIME_FISC\" CHAR(14 OCTETS) , \r\n"
					+ "	\"FEPTXN_AA_COMPLETE\" SMALLINT NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_TMO_FLAG\" SMALLINT NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_FISCSNO\" CHAR(7 OCTETS) , \r\n"
					+ "	\"FEPTXN_RMSNO\" CHAR(7 OCTETS) , \r\n"
					+ "	\"FEPTXN_ORGRMSNO\" CHAR(7 OCTETS) , \r\n"
					+ "	\"FEPTXN_ORGDATE\" CHAR(8 OCTETS) , \r\n"
					+ "	\"FEPTXN_SENDER_BANK\" CHAR(7 OCTETS) , \r\n"
					+ "	\"FEPTXN_RECEIVER_BANK\" CHAR(7 OCTETS) , \r\n"
					+ "	\"FEPTXN_MSGID\" VARCHAR(10 OCTETS) , \r\n"
					+ "	\"FEPTXN_REQ_DATETIME\" CHAR(14 OCTETS) , \r\n"
					+ "	\"FEPTXN_CASH_AMT\" DECIMAL(14,2) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_COIN_AMT\" DECIMAL(14,2) NOT NULL WITH DEFAULT 0 , \r\n"

					+ "	\"FEPTXN_FISC_CUR_MEMO\" CHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_BRNO\" CHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_DEPT\" VARCHAR(6 OCTETS) , \r\n"
					+ "	\"FEPTXN_TRIN_BRNO\" CHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_TRIN_DEPT\" VARCHAR(6 OCTETS) , \r\n"
					+ "	\"FEPTXN_TX_BRNO\" CHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_TX_DEPT\" VARCHAR(6 OCTETS) , \r\n"
					+ "	\"FEPTXN_ZONE_CODE\" VARCHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_ATM_BRNO\" VARCHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_ATM_ZONE\" VARCHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_ATMNO_VIR\" VARCHAR(8 OCTETS) , \r\n"
					+ "	\"FEPTXN_ORDER_DATE\" VARCHAR(8 OCTETS) NOT NULL WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_ATM_CHK\" VARCHAR(8 OCTETS) , \r\n"
					+ "	\"FEPTXN_ATM_TYPE\" VARCHAR(4 OCTETS) , \r\n"
					+ "	\"FEPTXN_TBSDY_INTL\" VARCHAR(8 OCTETS) , \r\n"
					+ "	\"FEPTXN_ICMARK\" CHAR(30 OCTETS) , \r\n"
					+ "	\"FEPTXN_YYMMDD\" CHAR(6 OCTETS) , \r\n"
					+ "	\"FEPTXN_TRK2\" VARCHAR(50 OCTETS) , \r\n"
					+ "	\"FEPTXN_TRK3\" VARCHAR(104 OCTETS) , \r\n"
					+ "	\"FEPTXN_IC_SEQNO\" CHAR(8 OCTETS) , \r\n"
					+ "	\"FEPTXN_IC_TAC\" CHAR(16 OCTETS) , \r\n"
					+ "	\"FEPTXN_PINBLOCK\" CHAR(16 OCTETS) , \r\n"
					+ "	\"FEPTXN_INCRE\" CHAR(4 OCTETS) , \r\n"
					+ "	\"FEPTXN_AUTHCD\" CHAR(6 OCTETS) , \r\n"
					+ "	\"FEPTXN_TX_ACTNO\" CHAR(16 OCTETS) , \r\n"
					+ "	\"FEPTXN_EXRATE\" DECIMAL(12,7) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_SCASH\" DECIMAL(12,7) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_ACRATE\" DECIMAL(12,7) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_DIFRATE\" DECIMAL(12,7) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_CBS_DSCPT\" CHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_SELFCD\" DECIMAL(4,0) NOT NULL WITH DEFAULT 1 , \r\n"
					+ "	\"FEPTXN_TX_CODE_ATMC\" CHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_TX_FEE_DR\" DECIMAL(7,2) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_TX_FEE_CR\" DECIMAL(7,2) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_TX_FEE_MBNK_DR\" DECIMAL(7,2) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_TX_FEE_MBNK_CR\" DECIMAL(7,2) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_ATM_PROFIT\" DECIMAL(7,2) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_ACT_PROFIT\" DECIMAL(7,2) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_ACT_LOSS\" DECIMAL(7,2) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_APID\" VARCHAR(5 OCTETS) , \r\n"
					+ "	\"FEPTXN_NOTICE_ID\" CHAR(4 OCTETS) , \r\n"
					+ "	\"FEPTXN_WAY\" DECIMAL(4,0) NOT NULL WITH DEFAULT 3 , \r\n"
					+ "	\"FEPTXN_ORDER_NO\" VARCHAR(16 OCTETS) , \r\n"
					+ "	\"FEPTXN_MERCHANT_ID\" VARCHAR(30 OCTETS) , \r\n"
					+ "	\"FEPTXN_PAYTYPE\" CHAR(5 OCTETS) , \r\n"
					+ "	\"FEPTXN_PAYNO\" CHAR(4 OCTETS) , \r\n"
					+ "	\"FEPTXN_TAX_UNIT\" CHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_IDNO\" CHAR(11 OCTETS) , \r\n"
					+ "	\"FEPTXN_DUE_DATE\" CHAR(8 OCTETS) , \r\n"
					+ "	\"FEPTXN_RECON_SEQNO\" CHAR(16 OCTETS) , \r\n"
					+ "	\"FEPTXN_FISC_RRN\" VARCHAR(12 OCTETS) , \r\n"
					+ "	\"FEPTXN_BUSINESS_UNIT\" CHAR(8 OCTETS) , \r\n"
					+ "	\"FEPTXN_NPS_FEE_RCVR\" DECIMAL(4,1) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_NPS_FEE_AGENT\" DECIMAL(4,1) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_NPS_FEE_TROUT\" DECIMAL(4,1) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_NPS_FEE_TRIN\" DECIMAL(4,1) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_NPS_FEE_FISC\" DECIMAL(4,1) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_NPS_FEE_CUSTPAY\" DECIMAL(4,1) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_NPS_CLR\" DECIMAL(4,0) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_NPS_MONTHLY_FG\" SMALLINT NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_REMARK\" VARCHAR(55 OCTETS) , \r\n"
					+ "	\"FEPTXN_RS_CODE\" CHAR(2 OCTETS) , \r\n"
					+ "	\"FEPTXN_TX_DATETIME_PREAUTH\" CHAR(14 OCTETS) , \r\n"
					+ "	\"FEPTXN_IC_SEQNO_PREAUTH\" CHAR(8 OCTETS) , \r\n"
					+ "	\"FEPTXN_TX_AMT_PREAUTH\" DECIMAL(13,2) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_CBS_INT_ACTNO\" CHAR(16 OCTETS) , \r\n"
					+ "	\"FEPTXN_CBS_SUP_ACTNO\" CHAR(16 OCTETS) , \r\n"
					+ "	\"FEPTXN_CBS_FEE_ACTNO\" CHAR(16 OCTETS) , \r\n"
					+ "	\"FEPTXN_CBS_VALUE_DATE\" VARCHAR(8 OCTETS) , \r\n"
					+ "	\"FEPTXN_CBS_TX_TIME\" VARCHAR(6 OCTETS) , \r\n"
					+ "	\"FEPTXN_TX_CUR_SET\" CHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_TX_AMT_SET\" DECIMAL(13,2) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_ERR_MSG\" VARCHAR(256 OCTETS) , \r\n"
					+ "	\"FEPTXN_RWTSEQ\" INTEGER NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_BOX_CNT\" DECIMAL(4,0) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_DSPCNT1\" SMALLINT NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_DSPCNT2\" SMALLINT NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_DSPCNT3\" SMALLINT NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_DSPCNT4\" SMALLINT NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_DSPCNT5\" SMALLINT NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_DSPCNT6\" SMALLINT NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_DSPCNT7\" SMALLINT NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_DSPCNT8\" SMALLINT NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_VIR_CBS_TIMEOUT\" SMALLINT NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_VIR_ACC_TYPE\" DECIMAL(4,0) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_VIR_CBS_TX_CODE\" VARCHAR(10 OCTETS) , \r\n"
					+ "	\"FEPTXN_VIR_CBS_RRN\" VARCHAR(20 OCTETS) WITH DEFAULT '' , \r\n"
					+ "	\"FEPTXN_VIR_CBS_RC\" VARCHAR(6 OCTETS) , \r\n"
					+ "	\"FEPTXN_VIR_ERR_MSG\" VARCHAR(256 OCTETS) , \r\n"
					+ "	\"FEPTXN_VIR_BRNO\" VARCHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_VIR_TRIN_BRNO\" VARCHAR(3 OCTETS) , \r\n"
					+ "	\"FEPTXN_VIR_CBS_INT_ACTNO\" VARCHAR(16 OCTETS) , \r\n"
					+ "	\"FEPTXN_VIR_CBS_SUP_ACTNO\" VARCHAR(16 OCTETS) , \r\n"
					+ "	\"FEPTXN_PBTYPE\" CHAR(2 OCTETS) , \r\n"
					+ "	\"FEPTXN_TELEPHONE\" VARCHAR(10 OCTETS) , \r\n"
					+ "	\"FEPTXN_CLIENTIP\" VARCHAR(17 OCTETS) , \r\n"
					+ "	\"FEPTXN_CASH_WAMT\" DECIMAL(14,2) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_COIN_WAMT\" DECIMAL(14,2) NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"FEPTXN_ACCT_SUP\" VARCHAR(12 OCTETS) , \r\n"
					+ "	\"FEPTXN_BENEFIT\" CHAR(1 OCTETS) , \r\n"
					+ "	\"FEPTXN_CHREM\" VARCHAR(40 OCTETS) , \r\n"
					+ "	\"FEPTXN_PSBREM_F_D\" VARCHAR(30 OCTETS) , \r\n"
					+ "	\"FEPTXN_PSBREM_F_C\" VARCHAR(30 OCTETS) , \r\n"
					+ "	\"FEPTXN_ACTIVITY_CODE\" CHAR(2 OCTETS) , \r\n"
					+ "	\"FEPTXN_NONPROM_AMT\" INTEGER , \r\n"
					+ "	\"FEPTXN_FMREM\" VARCHAR(40 OCTETS) , \r\n"
					+ "	\"FEPTXN_NPS_AGB_FEE\" DECIMAL(4,1) ,\r\n"
					+ "	\"UPDATE_USERID\" INTEGER NOT NULL WITH DEFAULT 0 , \r\n"
					+ "	\"UPDATE_TIME\" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP );\r\n"
					+ "ALTER TABLE \"" + tableName + "\" ADD CONSTRAINT \"PK_" + tableName + "\" PRIMARY KEY (\"FEPTXN_TX_DATE\", \"FEPTXN_EJFNO\");\r\n\r\n\r\n");
		}

		FileUtils.writeStringToFile(new File(CleanPathUtil.cleanString("C:/Users/Richard/Desktop/FEPTXN_db2.sql")), sb.toString(), StandardCharsets.UTF_8);
	}
	
	@Test
	public void generateMBG() {
		String tableName = "";
		for (int i = 1; i <= 31; i++) {
			tableName = "FEPTXN" + StringUtils.leftPad(String.valueOf(i), 2, '0');
			LogHelperFactory.getTraceLogger().info(
					"<table tableName=\"" + tableName
							+ "\" enableCountByExample=\"false\" enableUpdateByExample=\"false\" enableDeleteByExample=\"false\" enableSelectByExample=\"false\" selectByExampleQueryId=\"false\" />");
		}
	}
}
