package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscomgroupmembers;
import org.apache.ibatis.annotations.Param;

public interface SyscomgroupmembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPMEMBERS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscomgroupmembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPMEMBERS
     *
     * @mbg.generated
     */
    int insert(Syscomgroupmembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPMEMBERS
     *
     * @mbg.generated
     */
    int insertSelective(Syscomgroupmembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPMEMBERS
     *
     * @mbg.generated
     */
    Syscomgroupmembers selectByPrimaryKey(@Param("groupid") Integer groupid, @Param("childid") Integer childid, @Param("childtype") String childtype);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPMEMBERS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscomgroupmembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPMEMBERS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscomgroupmembers record);
}