package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscomuser;
import org.apache.ibatis.annotations.Param;

public interface SyscomuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscomuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSER
     *
     * @mbg.generated
     */
    int insert(Syscomuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSER
     *
     * @mbg.generated
     */
    int insertSelective(Syscomuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSER
     *
     * @mbg.generated
     */
    Syscomuser selectByPrimaryKey(@Param("userid") Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscomuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscomuser record);
}