package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscomauditlog;
import org.apache.ibatis.annotations.Param;

public interface SyscomauditlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMAUDITLOG
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscomauditlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMAUDITLOG
     *
     * @mbg.generated
     */
    int insert(Syscomauditlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMAUDITLOG
     *
     * @mbg.generated
     */
    int insertSelective(Syscomauditlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMAUDITLOG
     *
     * @mbg.generated
     */
    Syscomauditlog selectByPrimaryKey(@Param("logid") String logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMAUDITLOG
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscomauditlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMAUDITLOG
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscomauditlog record);
}