package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscomrolegroup;
import org.apache.ibatis.annotations.Param;

public interface SyscomrolegroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEGROUP
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscomrolegroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEGROUP
     *
     * @mbg.generated
     */
    int insert(Syscomrolegroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEGROUP
     *
     * @mbg.generated
     */
    int insertSelective(Syscomrolegroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEGROUP
     *
     * @mbg.generated
     */
    Syscomrolegroup selectByPrimaryKey(@Param("roleid") Integer roleid, @Param("groupid") Integer groupid, @Param("childtype") String childtype);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEGROUP
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscomrolegroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEGROUP
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscomrolegroup record);
}