package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscomroleculture;
import org.apache.ibatis.annotations.Param;

public interface SyscomrolecultureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLECULTURE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscomroleculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLECULTURE
     *
     * @mbg.generated
     */
    int insert(Syscomroleculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLECULTURE
     *
     * @mbg.generated
     */
    int insertSelective(Syscomroleculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLECULTURE
     *
     * @mbg.generated
     */
    Syscomroleculture selectByPrimaryKey(@Param("roleid") Integer roleid, @Param("culture") String culture);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLECULTURE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscomroleculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLECULTURE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscomroleculture record);
}