package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscombasemessageculture;
import org.apache.ibatis.annotations.Param;

public interface SyscombasemessagecultureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMBASEMESSAGECULTURE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscombasemessageculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMBASEMESSAGECULTURE
     *
     * @mbg.generated
     */
    int insert(Syscombasemessageculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMBASEMESSAGECULTURE
     *
     * @mbg.generated
     */
    int insertSelective(Syscombasemessageculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMBASEMESSAGECULTURE
     *
     * @mbg.generated
     */
    Syscombasemessageculture selectByPrimaryKey(@Param("basemessageno") String basemessageno, @Param("culture") String culture);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMBASEMESSAGECULTURE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscombasemessageculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMBASEMESSAGECULTURE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscombasemessageculture record);
}