package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscomtemplate;
import org.apache.ibatis.annotations.Param;

public interface SyscomtemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscomtemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATE
     *
     * @mbg.generated
     */
    int insert(Syscomtemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATE
     *
     * @mbg.generated
     */
    int insertSelective(Syscomtemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATE
     *
     * @mbg.generated
     */
    Syscomtemplate selectByPrimaryKey(@Param("templateid") Integer templateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscomtemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscomtemplate record);
}