package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscomroletemplate;
import org.apache.ibatis.annotations.Param;

public interface SyscomroletemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLETEMPLATE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscomroletemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLETEMPLATE
     *
     * @mbg.generated
     */
    int insert(Syscomroletemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLETEMPLATE
     *
     * @mbg.generated
     */
    int insertSelective(Syscomroletemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLETEMPLATE
     *
     * @mbg.generated
     */
    Syscomroletemplate selectByPrimaryKey(@Param("roleid") Integer roleid, @Param("templateid") Integer templateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLETEMPLATE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscomroletemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLETEMPLATE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscomroletemplate record);
}