package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscomuserdeputy;
import org.apache.ibatis.annotations.Param;

public interface SyscomuserdeputyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSERDEPUTY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscomuserdeputy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSERDEPUTY
     *
     * @mbg.generated
     */
    int insert(Syscomuserdeputy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSERDEPUTY
     *
     * @mbg.generated
     */
    int insertSelective(Syscomuserdeputy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSERDEPUTY
     *
     * @mbg.generated
     */
    Syscomuserdeputy selectByPrimaryKey(@Param("userid") Integer userid, @Param("roleid") Integer roleid, @Param("deputyuserid") Integer deputyuserid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSERDEPUTY
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscomuserdeputy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMUSERDEPUTY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscomuserdeputy record);
}