package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscomgroupculture;
import org.apache.ibatis.annotations.Param;

public interface SyscomgroupcultureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPCULTURE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscomgroupculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPCULTURE
     *
     * @mbg.generated
     */
    int insert(Syscomgroupculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPCULTURE
     *
     * @mbg.generated
     */
    int insertSelective(Syscomgroupculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPCULTURE
     *
     * @mbg.generated
     */
    Syscomgroupculture selectByPrimaryKey(@Param("groupid") Integer groupid, @Param("culture") String culture);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPCULTURE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscomgroupculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUPCULTURE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscomgroupculture record);
}