package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscomroleresourcedeny;
import org.apache.ibatis.annotations.Param;

public interface SyscomroleresourcedenyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCEDENY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscomroleresourcedeny record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCEDENY
     *
     * @mbg.generated
     */
    int insert(Syscomroleresourcedeny record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCEDENY
     *
     * @mbg.generated
     */
    int insertSelective(Syscomroleresourcedeny record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCEDENY
     *
     * @mbg.generated
     */
    Syscomroleresourcedeny selectByPrimaryKey(@Param("roleid") Integer roleid, @Param("resourceid") Integer resourceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCEDENY
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscomroleresourcedeny record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCEDENY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscomroleresourcedeny record);
}