package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscomrole;
import org.apache.ibatis.annotations.Param;

public interface SyscomroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscomrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLE
     *
     * @mbg.generated
     */
    int insert(Syscomrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLE
     *
     * @mbg.generated
     */
    int insertSelective(Syscomrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLE
     *
     * @mbg.generated
     */
    Syscomrole selectByPrimaryKey(@Param("roleid") Integer roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscomrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscomrole record);
}