package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscomtemplateculture;
import org.apache.ibatis.annotations.Param;

public interface SyscomtemplatecultureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATECULTURE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscomtemplateculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATECULTURE
     *
     * @mbg.generated
     */
    int insert(Syscomtemplateculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATECULTURE
     *
     * @mbg.generated
     */
    int insertSelective(Syscomtemplateculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATECULTURE
     *
     * @mbg.generated
     */
    Syscomtemplateculture selectByPrimaryKey(@Param("templateid") Integer templateid, @Param("culture") String culture);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATECULTURE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscomtemplateculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMTEMPLATECULTURE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscomtemplateculture record);
}