package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscomresource;
import org.apache.ibatis.annotations.Param;

public interface SyscomresourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscomresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCE
     *
     * @mbg.generated
     */
    int insert(Syscomresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCE
     *
     * @mbg.generated
     */
    int insertSelective(Syscomresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCE
     *
     * @mbg.generated
     */
    Syscomresource selectByPrimaryKey(@Param("resourceid") Integer resourceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscomresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscomresource record);
}