package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscomroleresource;
import org.apache.ibatis.annotations.Param;

public interface SyscomroleresourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscomroleresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCE
     *
     * @mbg.generated
     */
    int insert(Syscomroleresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCE
     *
     * @mbg.generated
     */
    int insertSelective(Syscomroleresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCE
     *
     * @mbg.generated
     */
    Syscomroleresource selectByPrimaryKey(@Param("roleid") Integer roleid, @Param("resourceid") Integer resourceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscomroleresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLERESOURCE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscomroleresource record);
}