package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscombasemessage;
import org.apache.ibatis.annotations.Param;

public interface SyscombasemessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMBASEMESSAGE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscombasemessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMBASEMESSAGE
     *
     * @mbg.generated
     */
    int insert(Syscombasemessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMBASEMESSAGE
     *
     * @mbg.generated
     */
    int insertSelective(Syscombasemessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMBASEMESSAGE
     *
     * @mbg.generated
     */
    Syscombasemessage selectByPrimaryKey(@Param("basemessageno") String basemessageno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMBASEMESSAGE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscombasemessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMBASEMESSAGE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscombasemessage record);
}