package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscompolicyculture;
import org.apache.ibatis.annotations.Param;

public interface SyscompolicycultureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMPOLICYCULTURE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscompolicyculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMPOLICYCULTURE
     *
     * @mbg.generated
     */
    int insert(Syscompolicyculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMPOLICYCULTURE
     *
     * @mbg.generated
     */
    int insertSelective(Syscompolicyculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMPOLICYCULTURE
     *
     * @mbg.generated
     */
    Syscompolicyculture selectByPrimaryKey(@Param("policyid") Integer policyid, @Param("culture") String culture);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMPOLICYCULTURE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscompolicyculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMPOLICYCULTURE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscompolicyculture record);
}