package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscomresourceculture;
import org.apache.ibatis.annotations.Param;

public interface SyscomresourcecultureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCECULTURE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscomresourceculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCECULTURE
     *
     * @mbg.generated
     */
    int insert(Syscomresourceculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCECULTURE
     *
     * @mbg.generated
     */
    int insertSelective(Syscomresourceculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCECULTURE
     *
     * @mbg.generated
     */
    Syscomresourceculture selectByPrimaryKey(@Param("resourceid") Integer resourceid, @Param("culture") String culture);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCECULTURE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscomresourceculture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMRESOURCECULTURE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscomresourceculture record);
}