package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscomgroup;
import org.apache.ibatis.annotations.Param;

public interface SyscomgroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUP
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscomgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUP
     *
     * @mbg.generated
     */
    int insert(Syscomgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUP
     *
     * @mbg.generated
     */
    int insertSelective(Syscomgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUP
     *
     * @mbg.generated
     */
    Syscomgroup selectByPrimaryKey(@Param("groupid") Integer groupid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUP
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscomgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMGROUP
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscomgroup record);
}