package com.syscom.safeaa.mybatis.mapper;

import com.syscom.safeaa.mybatis.model.Syscomroledeny;
import org.apache.ibatis.annotations.Param;

public interface SyscomroledenyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEDENY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Syscomroledeny record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEDENY
     *
     * @mbg.generated
     */
    int insert(Syscomroledeny record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEDENY
     *
     * @mbg.generated
     */
    int insertSelective(Syscomroledeny record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEDENY
     *
     * @mbg.generated
     */
    Syscomroledeny selectByPrimaryKey(@Param("roleid") Integer roleid, @Param("childid") Integer childid, @Param("childtype") String childtype);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEDENY
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscomroledeny record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCOMROLEDENY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscomroledeny record);
}